import { Anime } from "@/lib/class/Anime";
import { Synopsis } from "./pSynopsis";

export const p_anime = [
    new Anime(
        "Pan de Peace!",
        "",
        "https://cdn.myanimelist.net/images/anime/4/79400.jpg",
        13,
        "PG-13 - Teens 13 or older",
        Synopsis.PanDePeace,
        [""],
        "TV",
        "Apr 3 2016 to Jun 26 2016",
        "Spring 2016",
        "Asahi Production",
        "4-koma manga",
        ["Comedy", "Gourmet", "Slice of Life"],
        ["CGDCT", "School"],
        "3 minutes",
    ),
    new Anime(
        "Panty & Stocking with Garterbelt",
        "",
        "https://cdn.myanimelist.net/images/anime/1296/142674.jpg",
        13,
        "R - 17+ (violence & profanity)",
        Synopsis.PantyStocking,
        [""],
        "TV",
        "Oct 2 2010 to Dec 25 2010",
        "Fall 2010",
        "Gainax",
        "Original",
        ["Action", "Comedy", "Supernatural", "Ecchi"],
        ["Gag Humor", "Parody"],
        "23 minutes",
    ),
    new Anime(
        "Peach Boy Riverside",
        "",
        "https://cdn.myanimelist.net/images/anime/1535/115023.jpg",
        12,
        "R - 17+ (violence & profanity)",
        Synopsis.PeachBoyRiverSide,
        [""],
        "TV",
        "Jul 1 2021 to Sep 16 2021",
        "Summer 2021",
        "Asahi Production",
        "Manga",
        ["Action", "Adventure", "Fantasy"],
        ["Gore"],
        "23 minutes",
    ),
    new Anime(
        "Princess Connect! Re:Dive",
        "",
        "https://cdn.myanimelist.net/images/anime/1810/106070.jpg",
        13,
        "PG-13 - Teens 13 or older",
        Synopsis.PrincessConnect,
        [""],
        "TV",
        "Apr 7 2020 to Jun 30 2020",
        "Spring 2020",
        "CygamesPicture",
        "Game",
        ["Adventure", "Comedy", "Fantasy", "Gourmet"],
        [""],
        "23 minutes",
    ),
    new Anime(
        "Princess Connect! Re:Dive Season 2",
        "",
        "https://cdn.myanimelist.net/images/anime/1906/117145.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.PrincessConnect2,
        [""],
        "TV",
        "Jan 11 2022 to Mar 29 2022",
        "Winter 2022",
        "CygamesPicture",
        "Game",
        ["Adventure", "Comedy", "Fantasy", "Gourmet"],
        [""],
        "23 minutes",
    ),
    new Anime(
        "Puella Magi Madoka Magica",
        "Mahou Shoujo Madoka★Magica",
        "https://cdn.myanimelist.net/images/anime/11/55225.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.MadokaMagica,
        [""],
        "TV",
        "Jan 7 2011 to Apr 2 2011",
        "Winter 2011",
        "Shaft",
        "Original",
        ["Award Winning", "Drama", "Fantasy", "Suspense"],
        ["Mahou Shoujo", "Psychological"],
        "24 minutes",
    ),
    new Anime(
        "Punch Line",
        "",
        "https://cdn.myanimelist.net/images/anime/4/74641.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.PunchLine,
        [""],
        "TV",
        "Apr 10 2015 to Jun 26 2015",
        "Spring 2015",
        "MAPPA",
        "Original",
        ["Comedy", "Sci-Fi", "Supernatural", "Ecchi"],
        ["Super Power", "Time Travel"],
        "23 minutes",
    ),
]