export const Synopsis = {
    PanDePeace: `For the airheaded Minami Tani, there is nothing more delightful than delicious bread for breakfast. Bonding over a mutual love for the food, Minami meets the dignified Yuu Aizawa and the upbeat Fuyumi Fukagawa. Joining them is Noa Sakura, a pint-sized girl who sees bread as the ultimate weapon of self-defense. Together, the girls strengthen their bonds of friendship, while striving to sample every kind of bread this world has to offer.`,

    PantyStocking: `The "Anarchy Sisters," Panty and Stocking, have been kicked out of Heaven for, to put it mildly, misbehaving. Led by a priest named Garterbelt, these angels must buy their way back by exterminating ghosts in Daten City. But this task requires unconventional weapons for these unorthodox angels—they transform their lingerie into weapons to dispatch the spirits. Unfortunately, neither of them take their duties seriously, as they rather spend their time in pursuit of other "hobbies": Panty prefers to sleep with anything that walks, and Stocking favors stuffing her face with sweets than hunting ghosts.
                    Follow these two unruly angels as they battle ghosts, an overflow of bodily fluids, and their own tendency to get side-tracked in Panty & Stocking with Garterbelt.`,

    PeachBoyRiverSide: `In a magical world where humans, demihumans, and oni are heavily at odds with each other, a princess named Saltorine "Sally" Aldike is on a journey to find a person named Mikoto Kibitsu. Traversing the world, Sally comes across many truths that she had been ignorant of due to her lineage—including the knowledge that the oni possess power potent enough to wipe out humanity.
                        Seemingly blessed with a way to counter the oni's might, Sally has a strange power that manifests itself as a sigil resembling a peach, giving her superhuman abilities capable of defeating powerful oni with ease. Even so, Sally refuses to discriminate between humans, demihumans, and oni as much as possible, believing that peace between the three factions could be attainable one day.
                        On the contrary, Mikoto—who also has the same ability as Sally's but with greater mastery—has a different goal. Mikoto is out to kill and torment all oni in existence, stopping at nothing to fulfill this objective. As Sally and Mikoto continue to cross paths, the power they possess will spell the difference between amicable coexistence and utter annihilation.`,

    PrincessConnect: `In the continent of Astraea, a man falls from the sky, possessing no memories other than his name, Yuuki. An elf named Kokkoro finds him, introducing herself as his guide in the world they are about to traverse. With Kokkoro's guidance, Yuuki is able to learn how this world works, from battling monsters to handling currency.
                      To earn money for their journey, Yuuki and Kokkoro decide to go to a nearby guild association to accept a simple quest. In their expedition, they meet Pecorine, a somewhat gluttonous but charming girl skilled in battle. The next day, they also meet Karyl, a cat girl specializing in magic.
                      After some time, a bond of friendship and camaraderie forms between them, and the four decide to create a guild of their own. As they continue their adventures, they explore the world, meet new people, and will perhaps uncover the mysteries behind Yuuki's missing memories.`,

    PrincessConnect2: `The members of the Gourmet Guild—Yuuki, Kokkoro, Pecorine, and Karyl—continue to scour the world in pursuit of their goal to seek out all delicious food in existence. However, as their adventures progress, the mysteries behind Yuuki's memories, Karyl's allegiance, and Pecorine's heritage begin to come together—seemingly forming the truth that makes up the world's very foundation.`,

    MadokaMagica: `Madoka Kaname and Sayaka Miki are regular middle school girls with regular lives, but all that changes when they encounter Kyuubey, a cat-like magical familiar, and Homura Akemi, the new transfer student.
                   Kyuubey offers them a proposition: he will grant any one of their wishes and in exchange, they will each become a magical girl, gaining enough power to fulfill their dreams. However, Homura Akemi, a magical girl herself, urges them not to accept the offer, stating that everything is not what it seems.
                   A story of hope, despair, and friendship, Mahou Shoujo Madoka★Magica deals with the difficulties of being a magical girl and the price one has to pay to make a dream come true.`,

    PunchLine: `After escaping a bus hijacking with the help of masked superhero Strange Juice, Yuuta Iridatsu finds his soul separated from his body and in the care of a perverse cat spirit, Chiranosuke. As a spirit, Yuuta wanders around his residence, the Korai House, aiming to regain his body and observe the other residents: Meika Daihatsu, a genius inventor; Mikatan Narugino, a cheerful idol; Ito Hikiotani, a shut-in NEET; and Rabura Chichibu, a spiritual medium. After catching a glimpse of Narugino's undergarments, Chiranosuke reveals to Yuuta that he becomes exponentially stronger upon seeing panties. However, if he sees another pair while he is still a spirit, his power will cause an asteroid to crash into the earth, ending the world and killing his friends.
                Punch Line follows Yuuta as he unravels the mysteries surrounding Korai House, its residents, and a villainous organization attempting to end the world. Will Yuuta be able to save everyone, or will the ever-present threat of panties result in their doom?`,


}