import { Anime } from "@/lib/class/Anime";
import { Synopsis } from "./iSynopsis";

export const i_anime = [
    new Anime(
        "I Can't Understand What My Husband Is Saying",
        "Danna ga Nani wo Itteiru ka Wakaranai Ken",
        "https://cdn.myanimelist.net/images/anime/7/75287.jpg",
        13,
        "PG-13 - Teens 13 or older",
        Synopsis.CantUnderstand,
        [""],
        "TV",
        "Oct 3 2014 to Dec 26 2014",
        "Fall 2014",
        "Seven",
        "4-koma manga",
        ["Comedy", "Romance"],
        ["Adult Cast", "Otaku Culture"],
        "3 minutes",
    ),
    new Anime(
        "I Can't Understand What My Husband Is Saying: 2nd Thread",
        "Danna ga Nani wo Itteiru ka Wakaranai Ken 2 Sure-me",
        "https://cdn.myanimelist.net/images/anime/9/73595.jpg",
        13,
        "PG-13 - Teens 13 or older",
        Synopsis.CantUnderstand2,
        [""],
        "TV",
        "Apr 3 2015 to Jun 26 2015",
        "Spring 2015",
        "Seven",
        "4-koma manga",
        ["Comedy", "Romance"],
        ["Adult Cast", "Otaku Culture"],
        "3 minutes",
    ),
    new Anime(
        "I Couldn't Become a Hero, so I Reluctantly Decided to get a Job",
        "Yuusha ni Narenakatta Ore wa Shibushibu Shuushoku wo Ketsui Shimashita.",
        "https://cdn.myanimelist.net/images/anime/13/54389.jpg",
        12,
        "R+ - Mild Nudity",
        Synopsis.Hero,
        [""],
        "TV",
        "Oct 5 2013 to Dec 21 2013",
        "Fall 2013",
        "asread",
        "Light novel",
        ["Comedy", "Fantasy", "Romance", "Ecchi"],
        [""],
        "24 minutes",
    ),
    new Anime(
        "Inferno Cop",
        "",
        "https://cdn.myanimelist.net/images/anime/2/47037.jpg",
        13,
        "R - 17+ (violence & profanity)",
        Synopsis.InfernoCop,
        [""],
        "ONA",
        "Dec 25 2012 to Mar 19 2013",
        "Winter 2012",
        "Trigger",
        "Original",
        ["Action", "Comedy"],
        ["Gag Humor"],
        "3 minutes",
    ),
    new Anime(
        "Initial D First Stage",
        "",
        "https://cdn.myanimelist.net/images/anime/1384/127972.jpg",
        26,
        "PG-13 - Teens 13 or older",
        Synopsis.InitialD,
        [""],
        "TV",
        "Apr 19 1998 to Dec 6 1998",
        "Spring 1998",
        "Gallop, Studio Comet",
        "Manga",
        ["Action", "Drama"],
        ["Racing"],
        "25 minutes",
    ),
    new Anime(
        "Initial D Second Stage",
        "",
        "https://cdn.myanimelist.net/images/anime/8/12750.jpg",
        13,
        "PG-13 - Teens 13 or older",
        Synopsis.InitialD2,
        [""],
        "TV",
        "Oct 15 1999 to Jan 21 2000",
        "Fall 1999",
        "Pastel",
        "Manga",
        ["Action", "Drama"],
        ["Racing"],
        "23 minutes",
    ),
    new Anime(
        "Initial D Third Stage",
        "",
        "https://cdn.myanimelist.net/images/anime/13/40397.jpg",
        1,
        "PG-13 - Teens 13 or older",
        Synopsis.InitialD3,
        [""],
        "Movie",
        "Jan 13 2001",
        "Winter 2001",
        "Studio Deen",
        "Manga",
        ["Action", "Drama", "Romance"],
        ["Racing"],
        "1 hour 44 minutes",
    ),
    new Anime(
        "Initial D Fourth Stage",
        "",
        "https://cdn.myanimelist.net/images/anime/9/10521.jpg",
        24,
        "PG-13 - Teens 13 or older",
        Synopsis.InitialD4,
        [""],
        "TV",
        "Apr 17 2004 to Feb 18 2006",
        "Spring 2004",
        "A.C.G.T.",
        "Manga",
        ["Action", "Drama"],
        ["Racing"],
        "27 minutes",
    ),
    new Anime(
        "Inugami-san to Nekoyama-san",
        "",
        "https://cdn.myanimelist.net/images/anime/4/61921.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.InuNeko,
        [""],
        "TV",
        "Apr 11 2014 to Jun 27 2014",
        "Spring 2014",
        "Seven",
        "4-koma manga",
        ["Comedy", "Girls Love"],
        ["School"],
        "3 minutes",
    ),
    new Anime(
        "Inu X Boku Secret Service",
        "Inu x Boku SS",
        "https://cdn.myanimelist.net/images/anime/1760/98794.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.InuBoku,
        [""],
        "TV",
        "Jan 13 2012 to Mar 30 2012",
        "Winter 2012",
        "David Production",
        "Manga",
        ["Comedy", "Romance", "Supernatural"],
        ["Mythology"],
        "24 minutes",
    ),
    new Anime(
        "Is the Order a Rabbit?",
        "Gochuumon wa Usagi desu ka?",
        "https://cdn.myanimelist.net/images/anime/6/79600.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.OrderRabbit,
        [""],
        "TV",
        "Apr 10 2014 to Jun 26 2014",
        "Spring 2014",
        "White Fox",
        "4-koma manga",
        ["Slice of Life"],
        ["CGDCT", "Iyashikei", "Workplace"],
        "23 minutes"
    ),
    new Anime(
        "Isekai Quartet",
        "",
        "https://cdn.myanimelist.net/images/anime/1965/99667.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Isekai,
        [""],
        "TV",
        "Apr 10 2019 to Jun 26 2019",
        "Spring 2019",
        "Studio PuYUKAI",
        "Original",
        ["Comedy", "Fantasy"],
        ["Isekai", "Parody"],
        "11 minutes",
    ),
    new Anime(
        "Isekai Quartet 2",
        "",
        "https://cdn.myanimelist.net/images/anime/1030/103383.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Isekai2,
        [""],
        "TV",
        "Jan 15 2020 to Apr 1 2020",
        "Winter 2020",
        "Studio PuYUKAI",
        "Original",
        ["Comedy", "Fantasy"],
        ["Isekai", "Parody"],
        "11 minutes",
    ),
    new Anime(
        "I've Been Killing Slimes For 300 Years And Maxed Out My Level",
        "Slime Taoshite 300-nen, Shiranai Uchi ni Level Max ni Nattemashita",
        "https://cdn.myanimelist.net/images/anime/1888/133089.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Slimes,
        [""],
        "TV",
        "Apr 10 2021 to Jun 26 2021",
        "Spring 2021",
        "Revoroot",
        "Light novel",
        ["Comedy", "Fantasy"],
        ["CGDCT", "Isekai", "Reincarnation"],
        "23 minutes",
    ),
    new Anime(
        "Izetta: The Last Witch",
        "Shuumatsu no Izetta",
        "https://cdn.myanimelist.net/images/anime/7/82119.jpg",
        12,
        "R - 17+ (violence & profanity)",
        Synopsis.Izetta,
        [""],
        "TV",
        "Oct 1 2016 to Dec 17 2016",
        "Fall 2016",
        "Ajia-do",
        "Original",
        ["Action", "Fantasy"],
        ["Historical", "Military"],
        "25 minutes",
    ),
]