export const Synopsis = {
    CantUnderstand: `Though they couldn't be any more different, love has managed to blossom between Hajime Tsunashi, a hardcore otaku who shuts himself in at home while making a living off his blog, and his wife Kaoru—a hard-working office lady who, in contrast, is fairly ordinary, albeit somewhat of a crazy drunk. As this unlikely couple discovers, love is much more than just a first kiss or a wedding; the years that come afterward in the journey of marriage brings with it many joys as well as challenges.
                     Whether due to their quirky personalities or the peculiar people surrounding them, Hajime and Kaoru find themselves caught up in a variety of baffling and ridiculous antics. But despite the struggles they face, the love that ties them together spurs them to move forward and strive to become better people in order to bring their partner happiness.`,

    CantUnderstand2: `The Tsunashi couple is as lively and offbeat as ever. Hardcore otaku shut-in Hajime and workaholic office lady Kaoru still get themselves into hilarious situations thanks to both their own eccentric natures and the bizarre group of friends surrounding them.
                      After learning about Kaoru's pregnancy, Hajime works harder than ever to become a good husband and a worthy father. Meanwhile, Kaoru reflects on their relationship and remembers all of the trials and tribulations that brought them closer. The two of them continue to put their best foot forward in their lives and their marriage—all for the sake of long-lasting, selfless love.`,

    Hero: `Dreaming of becoming a hero and vanquishing the Demon King, Raul Chaser enters the Hero Training Program in pursuit of his ambition. However, when the Demon King is defeated and peace returns to the world, the Hero Training Program is suspended indefinitely, making it impossible for anyone to become a hero.
           Two years later, Raul reluctantly works at a small electronics store called Magic Shop Leon. Though the former hero-in-training is plagued by the mundanity of working in retail, everything changes with the arrival of a new hire. Appearing at first to be just a boy with good looks, "he" turns out to be a female demon by the name of Fino Bloodstone. She is not just any old demon either—Raul's new coworker is in fact the daughter of the late Demon King! Handed the responsibility of training this eccentric new employee, Raul soon finds his life becoming livelier than it ever was before.`,

    InfernoCop: `Jack Knife Edge Town is as edgy as it sounds, and it's up to Inferno Cop to stop that edge from tearing his city apart. He's both law and outlaw, dispensing ungodly justice to evildoers like a candy machine. Lowlifes, gangsters, and even hellspawn all infest Inferno Cop's hunting ground, but that's the good news. The bad news? Prior to the story, his family was brutally murdered by Southern Cross, a shady organization that made the worst mistake imaginable by doing so. Now, Inferno Cop's limiters have been removed and his mercy rung more dry than the entrails of his victims.
                 Something is welling up in Inferno Cop's city, however, and soon he'll face the most daunting gauntlet of his life involving him literally falling into and escaping from Hell. A flaming head won't be enough to ward off the true evil that's rapidly approaching—Inferno Cop must call upon all his allies and his own wacky antics to conquer the trials that await him.`,

    InitialD: `Unlike his friends, Takumi Fujiwara is not particularly interested in cars, with little to no knowledge about the world of car enthusiasts and street racers. The son of a tofu shop owner, he is tasked to deliver tofu every morning without fail, driving along the mountain of Akina. Thus, conversations regarding cars or driving in general would only remind Takumi of the tiring daily routine forced upon him.
               One night, the Akagi Red Suns, an infamous team of street racers, visit the town of Akina to challenge the local mountain pass. Led by their two aces, Ryousuke and Keisuke Takahashi, the Red Suns plan to conquer every racing course in Kanto, establishing themselves as the fastest crew in the region. However, much to their disbelief, one of their aces is overtaken by an old Toyota AE86 during a drive back home from Akina. After the incident, the Takahashi brothers are cautious of a mysterious driver geared with remarkable technique and experience in the local roads—the AE86 of Mount Akina.`,

    InitialD2: `Accumulating an impressive series of victories with his AE86, Takumi Fujiwara has imposed himself as street racing's newest rising star. However, his newly found confidence of winning at his home turf of Mount Akina has been put in jeopardy by a new Emperor team exclusively using a car model favored by most professional racing pilots: the Mitsubishi four-wheel drive Lancer Evolutions—also known as Lan Evos. The Emperor team leader, Kyouichi Sudou, looks down on Takumi and regards him as an inferior pilot for driving an antique car that lacks the makings of a true modern race car. Kyouichi's elitist philosophy is also the reason why his team is only made of Lan Evo drivers.
                Will Takumi be able to keep his perfect track record intact against the highly skilled and mechanically superior Emperor team, or does his hot streak end here?`,

    InitialD3: `Takumi Fujiwara is a skilled street racer, but he suffers a crushing loss against the team Emperor's leader Kyoichi Sudou due to his AE86 experiencing an engine failure. Doubting his abilities, the recent high school graduate is then approached by the Akagi RedSuns' team leader Ryousuke Takahashi, who proposes the formation of a professional street racing team. Although it would be the ideal way to improve as a street racer, Takumi remains undecided.
                Does the young street racer have what it takes to become a professional? Perhaps Ryousuke and the RedSuns can help him reevaluate his own doubts and misconceptions concerning street racing. However, first and foremost, Takumi decides to settle the score with Kyoichi Sudou...`,

    InitialD4: `Takumi Fujiwara finally joins Ryousuke and Keisuke Takahashi to create "Project D." Their goal is twofold: Ryousuke wants to develop his "High-Speed Street Racing Theory," while Keisuke and Takumi aim at improving their driving skills by facing powerful opponents on dangerous roads. The idea of Project D is to challenge street racing teams from other prefectures to improve both their uphill and downhill records. In order to attract the attention of the best racing teams, Ryousuke creates a dedicated website to announce the future battles of Project D and post the team's results.
                The fourth season of Initial D details the hardships and successes of the members of Project D as they try to become the best street racing team outside of Gunma Prefecture.`,

    InuNeko: `Yachiyo Inugami, a cat-loving extrovert, and Suzu Nekoyama, a dog-loving introvert, are unexpectedly cast into a relationship on a day like any other. The pair find themselves drawn together through an inexplicable attraction of their opposite personalities. As they quickly begin to understand one another, Inugami's hardened resolve to gain Nekoyama's favor only leads to frenzied responses. Soon after their momentous union, the two begin to spend more time with one another, growing closer all the while.
              Their combined antics gain the attention of the mousy Mikine Nezu, a classmate of Inugami, and soon they join the "biology" club. There, they meet Ushikawa Ukiji, a passive, cow-like upperclassmen. Nezu and Nekoyama soon begin to build upon their relationship and a game of cat and mouse soon begins.
              Wild, explosive, and vibrant, Inugami-san to Nekoyama-san tells the comedic tale of two high school girls and their less-than-normal relationship.`,

    InuBoku: `Ririchiyo Shirakiin is the sheltered daughter of a renowned family. With her petite build and wealthy status, Ririchiyo has been a protected and dependent girl her entire life, but now she has decided to change all that. However, there is just one problem—the young girl has a sharp tongue she can't control, and terrible communication skills.
              With some help from a childhood friend, Ririchiyo takes up residence in Maison de Ayakashi, a secluded high-security apartment complex that, as the unsociable 15-year-old soon discovers, is home to a host of bizarre individuals. Furthermore, their quirky personalities are not the strangest things about them: each inhabitant of the Maison de Ayakashi, including Ririchiyo, is actually half-human, half-youkai.
              But Ririchiyo's troubles have only just begun. As a requirement of staying in her new home, she must be accompanied by a Secret Service agent. Ririchiyo's new partner, Soushi Miketsukami, is handsome, quiet... but ridiculously clingy and creepily submissive. With Soushi, her new supernatural neighbors, and the beginning of high school, Ririchiyo definitely seems to have a difficult path ahead of her.`,

    Isekai: `It is a normal day; everyone from deranged military girl Tanya Degurechaff and 16-year-old isekai protagonist Satou Kazuma to expansionist overlord Ainz Ooal Gown and demon sisters Rem and Ram go on with their daily lives. Suddenly, a conspicuous red button begging to be pressed appears before them. Overcome by curiosity, the otherworldly characters push the button, sending them to an unfamiliar world.
             With no way of escaping, the characters must lead a normal school life and make acquaintances with the others. One thing is certain: the classroom full of fan-favorite eccentric personalities never gets boring!`,

    Isekai2: `Despite completing all the tasks given to them, Ainz Ooal Gown, Tanya Degurechaff, Kazuma Satou, Subaru Natsuki, and the other members of Class 2 are surprised to find out that their role as students is far from over. With no means of returning home, the class of eccentric personalities is still mysteriously stuck in the unfamiliar world. Although, as they are becoming quite fond of each other, spending more time together does not sound that bad.
              With the unexpected arrival of new transfer students, the comedic antics of our beloved characters continue to grow. Thus, their bizarre yet nonchalant school life continues.`,

    Slimes: `In role-playing games, slimes are usually the easiest monster to kill, and because of that, they yield few experience points. But what would happen if you live long enough to keep defeating them for 300 years?
             After many years of being a corporate slave, Azusa Aizawa abruptly passes away due to severe exhaustion. Seemingly headed for the afterlife, she meets a goddess who bestows her with immortality alongside a peaceful life in another world. There, Azusa enjoys her days tending to her farm, protecting the nearby village, and killing about 25 slimes per day—a routine that continues for at least three centuries.
             However, this rather monotonous cycle begins to change when Azusa suddenly finds out that she has reached level 99—the maximum possible level—from slimes alone. Despite desperately trying to hide this fact in fear of ending her slow life, rumors of her strength spread nevertheless. Soon enough, various people throughout the continent, like the dragon Laika and the elf Halkara, start to appear at her doorstep—some seeking a battle, others asking for her assistance. Meeting friends and acquaintances who soon become family, Azusa finds she can live a life far better with others than when she was alone.`,

    Izetta: `After Germania invaded a neighboring country in 1939, Europe spiraled into a devastating war. During the war, Germania set its sights on the weak alpine country of Elystadt. Boasting a far superior military and having achieved profuse success earlier in the war, it was expected that Germania would conquer Elystadt with ease.
             Matters are only made worse for the small country when Germanian soldiers capture their princess, Ortfiné "Finé" Fredericka von Eylstadt, as she is heading to a crucial meeting with Britannia. Yet, when a concurrent Germanian transport mission goes awry, Izetta, the last witch alive, escapes. When she recognizes Princess Finé from her childhood, Izetta rescues her from the Germanian soldiers by making use of her magical abilities. Now reunited with the princess, Izetta pledges to protect Elystadt from Germania, and with the last surviving witch on their arsenal, Elystadt hopes to turn the tides against the imperialist war giant.`,


}