export const Synopsis = {

    Frieren: `During their decade-long quest to defeat the Demon King, the members of the hero's party—Himmel himself, the priest Heiter, the dwarf warrior Eisen, and the elven mage Frieren—forge bonds through adventures and battles, creating unforgettable precious memories for most of them.
              However, the time that Frieren spends with her comrades is equivalent to merely a fraction of her life, which has lasted over a thousand years. When the party disbands after their victory, Frieren casually returns to her "usual" routine of collecting spells across the continent. Due to her different sense of time, she seemingly holds no strong feelings toward the experiences she went through.
              As the years pass, Frieren gradually realizes how her days in the hero's party truly impacted her. Witnessing the deaths of two of her former companions, Frieren begins to regret having taken their presence for granted; she vows to better understand humans and create real personal connections. Although the story of that once memorable journey has long ended, a new tale is about to begin.`,

    MushokuTensei2: `After his relationship with Eris Boreas Greyrat reaches new heights, Rudeus Greyrat is ecstatic. Unfortunately, his joy is short-lived, as Eris suddenly abandons him to embark on her own journey. Believing that Eris has lost all interest in him, a heartbroken and depressed Rudeus sets forth to the Northern Territories. With his sole goal being to locate his mother on the vast continent, Rudeus wonders if persisting through daily life is worth the pain, falling into a robotic routine as he endlessly ruminates on his lost love.
                     However, the dangers of the North soon prove that one cannot survive with a dulled mind. While on a quest with the party Counter Arrow, with whom he recently became acquainted, Rudeus has a brush with death—an experience that forces him to finally snap out of his despair. With his newfound teammates, Rudeus rediscovers the pleasure of daily adventuring and moves forward with his original goal of living his second lease on life to the fullest.`,

    MushokuTensei2Part2: `Following the faceless god Hitogami's advice seems to have worked wonders for Rudeus Greyrat. After enrolling into the University of Magic as he was told, Rudeus reunites with his childhood friend Sylphiette, who put a valiant effort into curing his condition. The two grow ever closer together and decide to host a wedding party, inviting the friends they have made over the years to announce and formalize their relationship.
                          For all his recent blessings, however, Rudeus' troubles are far from over. The research he is helping Shizuka Nanahoshi conduct hits a bottleneck, sending her into a deep slump much like he experienced in his previous life. Furthermore, a letter from his father, Paul, brings complications to Rudeus' relationships, and Sylphiette still knows next to nothing about his real background. In the face of these issues, Rudeus will have to apply the lessons he has learned in this new world to navigate through the challenges that come with living a life to its fullest.`,

    Nokotan: `No one knows Torako used to be a delinquent. All of her classmates only know her as the perfect student. But everything changes when Nokotan, a transfer student with antlers, enters her life. Antlers aren't the only thing strange about Nokotan. Her deer nose can sniff out Torako's secret past! Whether it's at school or the zoo, chaos follows this doe-eyed girl's every step. Torako has so many questions! Is Nokotan a deer, a girl, or something in-between?`,

    RentAGirlfriend3: `With her late grandfather's inspiring words in mind, Chizuru Mizuhara teams up with her friend Kazuya Kinoshita to launch a crowdfunding campaign for an amateur film. The two hope that with the success of the project, Chizuru can honor her grandparents' wishes before she loses her grandmother as well. After their wild encounters with three girls—Kazuya's clingy "trial" girlfriend, Ruka Sarashina; their nosy new next-door neighbor, Mini Yaemori; and Chizuru's shy work friend, Sumi Sakurasawa—they all collaborate together to reach the campaign goal and begin production of the film. As their ambitious endeavor progresses, Chizuru and Kazuya grow closer and begin to struggle with their mutual feelings.`,

    IdolMasterU149: `Mature grade school student Arisu Tachibana is an aspiring idol who receives an invitation from her company president to participate in the Third Entertainment Section—a new idol project. Arisu and eight other young girls soon meet their producer before beginning idol-related activities.
                    To the girls' surprise, their producer appears to be a childlike adult and nothing like what they had imagined. The producer, who is taking on the position for the first time, also had no idea that he would be meeting a group of short, young idols. The awkward situation leaves Arisu disappointed, and she wishes for a producer change.
                    However, the producer, with his genuine love for idols and his desire to see them shine, will not let this opportunity pass and expresses that he is serious about working with the girls. Thankfully, the young idols accept the producer after seeing his unwavering passion for idols, serving as the start of their journey to the stage of dreams.`,

    CluelessFirstFriend: `Akane Nishimura's quiet nature makes her classmates perceive her as a gloomy and unlikeable person. Combined with her intimidating gaze, it earns Akane the ominous nickname "Grim Reaper," condemning her to endless bullying for her supposed cursed powers that bring misfortune to everyone around her.
                         However, none of these rumors deter transfer student Taiyou Takada from trying to befriend Akane. As someone who finds the supernatural fascinating, Taiyou approaches the Grim Reaper without hesitation, blissfully unaware of the complicated situation within the class. His bright personality and optimistic worldview may just bring about the change that Akane desperately needs.`,

    FightLeague: `Hot-blooded in nature, Adjust Wrench competes with her team Boltechs in a popular tournament known as the "Fight League," where two teams fight using personalized weapons called "Gadgets" until only one team is left standing. However, despite their best efforts, Wrench and her friends have only achieved moderate success in the Fight League—winning just as often as they lose.
                 Aiming to gain more strength, Wrench installs a mysterious computer chip that her grandfather possessed into her Gadget and inadvertently summons an overwhelmingly powerful girl. Naming herself Mona Chrome, she joins Boltechs, and together, the group starts rising through the ranks with their new teammate's abilities. But as the other teams push themselves to become stronger, everyone begins to question Chrome's identity and the source of her power.`,
}