export const Synopsis = {

    Zom100: `After graduating from a top university with an impressive extracurricular record in the rugby club, Akira Tendou has nailed every step of the way to securing his dream job. On top of that, a beautiful and kind co-worker always brightens his day in the office! Life seems to be going very well for Akira until he slowly realizes that sleepless nights and brutal work are his new reality.
             Due to three years of mind-numbing labor in an exploitative company, Akira is unable to recognize the tired, unaccomplished person he has become. On track to losing all passion in life like several of his overworked colleagues, Akira finds his saving grace in the most unexpected way possible—the breakout of a zombie apocalypse.
             With the free time he finally has, Akira decides to complete a bucket list of a hundred things he wants to do before he eventually gets turned into a zombie. Although he is surrounded by the dead, Akira has never felt more alive!`,

    RentAGirlfriend3: `With her late grandfather's inspiring words in mind, Chizuru Mizuhara teams up with her friend Kazuya Kinoshita to launch a crowdfunding campaign for an amateur film. The two hope that with the success of the project, Chizuru can honor her grandparents' wishes before she loses her grandmother as well. After their wild encounters with three girls—Kazuya's clingy "trial" girlfriend, Ruka Sarashina; their nosy new next-door neighbor, Mini Yaemori; and Chizuru's shy work friend, Sumi Sakurasawa—they all collaborate together to reach the campaign goal and begin production of the film. As their ambitious endeavor progresses, Chizuru and Kazuya grow closer and begin to struggle with their mutual feelings.`,

    IdolMasterU149: `Mature grade school student Arisu Tachibana is an aspiring idol who receives an invitation from her company president to participate in the Third Entertainment Section—a new idol project. Arisu and eight other young girls soon meet their producer before beginning idol-related activities.
                    To the girls' surprise, their producer appears to be a childlike adult and nothing like what they had imagined. The producer, who is taking on the position for the first time, also had no idea that he would be meeting a group of short, young idols. The awkward situation leaves Arisu disappointed, and she wishes for a producer change.
                    However, the producer, with his genuine love for idols and his desire to see them shine, will not let this opportunity pass and expresses that he is serious about working with the girls. Thankfully, the young idols accept the producer after seeing his unwavering passion for idols, serving as the start of their journey to the stage of dreams.`,

    CluelessFirstFriend: `Akane Nishimura's quiet nature makes her classmates perceive her as a gloomy and unlikeable person. Combined with her intimidating gaze, it earns Akane the ominous nickname "Grim Reaper," condemning her to endless bullying for her supposed cursed powers that bring misfortune to everyone around her.
                         However, none of these rumors deter transfer student Taiyou Takada from trying to befriend Akane. As someone who finds the supernatural fascinating, Taiyou approaches the Grim Reaper without hesitation, blissfully unaware of the complicated situation within the class. His bright personality and optimistic worldview may just bring about the change that Akane desperately needs.`,

    FightLeague: `Hot-blooded in nature, Adjust Wrench competes with her team Boltechs in a popular tournament known as the "Fight League," where two teams fight using personalized weapons called "Gadgets" until only one team is left standing. However, despite their best efforts, Wrench and her friends have only achieved moderate success in the Fight League—winning just as often as they lose.
                 Aiming to gain more strength, Wrench installs a mysterious computer chip that her grandfather possessed into her Gadget and inadvertently summons an overwhelmingly powerful girl. Naming herself Mona Chrome, she joins Boltechs, and together, the group starts rising through the ranks with their new teammate's abilities. But as the other teams push themselves to become stronger, everyone begins to question Chrome's identity and the source of her power.`,
}