export const Synopsis = {
       
    Oshinoko2: `With the help of producer Masaya Kaburagi, Aquamarine "Aqua" Hoshino and Kana Arima have landed the roles of Touki and Tsurugi in Lala Lai Theatrical Company's stage adaptation of the popular manga series Tokyo Blade. Co-starring with them is Aqua's girlfriend, Akane Kurokawa, who plays Touki's fiancée, Princess Saya. Due to the fanbase preferring Tsurugi as Touki's love interest, Saya has made fewer and fewer appearances in the manga, making it difficult for Akane to fully immerse herself in the role. Her struggles are compounded by differences between the play's script and the original work—differences that also frustrate Tokyo Blade's author, Abiko Samejima.
                Aqua, however, is more concerned with his personal goals than he is with the play. He has only one objective in mind: to grow closer to director Toshirou Kindaichi and find out what he knows about Aqua's mother, Ai.`,

    Nokotan: `Torako Koshi is the epitome of perfection. With her peerless beauty, top-notch grades, and position as student council president, her popularity in school is unrivaled. However, she harbors a dark secret—she was a delinquent back in middle school—and this is something she conceals to the best of her abilities.
              Unfortunately, when she meets the mysterious deer girl Noko Shikanoko, Torako's hidden shame is constantly on the precipice of being exposed due to Shikanoko's rather weird antics. To maintain the reputation she worked so hard for, Torako must go along with Shikanoko's whims, even going so far as to become president of the newly established Deer Club. All her efforts will be rewarded if she can prevent the menacing doe from accidentally blurting out damaging details about her personal history that will undoubtedly unleash Torako's greatest nightmare.`,

    RentAGirlfriend3: `With her late grandfather's inspiring words in mind, Chizuru Mizuhara teams up with her friend Kazuya Kinoshita to launch a crowdfunding campaign for an amateur film. The two hope that with the success of the project, Chizuru can honor her grandparents' wishes before she loses her grandmother as well. After their wild encounters with three girls—Kazuya's clingy "trial" girlfriend, Ruka Sarashina; their nosy new next-door neighbor, Mini Yaemori; and Chizuru's shy work friend, Sumi Sakurasawa—they all collaborate together to reach the campaign goal and begin production of the film. As their ambitious endeavor progresses, Chizuru and Kazuya grow closer and begin to struggle with their mutual feelings.`,

    IdolMasterU149: `Mature grade school student Arisu Tachibana is an aspiring idol who receives an invitation from her company president to participate in the Third Entertainment Section—a new idol project. Arisu and eight other young girls soon meet their producer before beginning idol-related activities.
                    To the girls' surprise, their producer appears to be a childlike adult and nothing like what they had imagined. The producer, who is taking on the position for the first time, also had no idea that he would be meeting a group of short, young idols. The awkward situation leaves Arisu disappointed, and she wishes for a producer change.
                    However, the producer, with his genuine love for idols and his desire to see them shine, will not let this opportunity pass and expresses that he is serious about working with the girls. Thankfully, the young idols accept the producer after seeing his unwavering passion for idols, serving as the start of their journey to the stage of dreams.`,

    CluelessFirstFriend: `Akane Nishimura's quiet nature makes her classmates perceive her as a gloomy and unlikeable person. Combined with her intimidating gaze, it earns Akane the ominous nickname "Grim Reaper," condemning her to endless bullying for her supposed cursed powers that bring misfortune to everyone around her.
                         However, none of these rumors deter transfer student Taiyou Takada from trying to befriend Akane. As someone who finds the supernatural fascinating, Taiyou approaches the Grim Reaper without hesitation, blissfully unaware of the complicated situation within the class. His bright personality and optimistic worldview may just bring about the change that Akane desperately needs.`,

    FightLeague: `Hot-blooded in nature, Adjust Wrench competes with her team Boltechs in a popular tournament known as the "Fight League," where two teams fight using personalized weapons called "Gadgets" until only one team is left standing. However, despite their best efforts, Wrench and her friends have only achieved moderate success in the Fight League—winning just as often as they lose.
                 Aiming to gain more strength, Wrench installs a mysterious computer chip that her grandfather possessed into her Gadget and inadvertently summons an overwhelmingly powerful girl. Naming herself Mona Chrome, she joins Boltechs, and together, the group starts rising through the ranks with their new teammate's abilities. But as the other teams push themselves to become stronger, everyone begins to question Chrome's identity and the source of her power.`,
}