import { Anime } from "./Anime";
import { Synopsis } from "./CurrentlyWatchingAnimeSynopsis";

export const currently_watching = [

    new Anime(
        "Frieren: Beyond Journey's End",
        "Sousou no Frieren",
        "https://cdn.myanimelist.net/images/anime/1015/138006.jpg",
        28,
        "PG-13 - Teens 13 or older",
        Synopsis.Frieren,
        [],
        "TV",
        "Sep 29 2023 to Mar 22 2024",
        "Fall 2023",
        "Madhouse",
        "Manga",
        ["Adventure", "Drama", "Fantasy"],
        [""],
        "24 minutes"
    ),
    new Anime(
        'Mushoku Tensei: Jobless Reincarnation 2nd Season - Episode 0 "Guardian Fitz"',
        "Mushoku Tensei II: Isekai Ittara Honki Dasu - Shugo Jutsushi Fitz",
        "https://cdn.myanimelist.net/images/anime/1627/136934.jpg",
        1,
        "R - 17+ (violence & profanity)",
        Synopsis.MushokuTensei2Special,
        [],
        "TV Special",
        "Jul 3 2023",
        "Summer 2023",
        "Studio Bind",
        "Light novel",
        ["Adventure", "Drama", "Fantasy", "Ecchi"],
        ["Isekai", "Reincarnation"],
        "24 minutes"
    ),
    new Anime(
        "Mushoku Tensei: Jobless Reincarnation Season 2",
        "Mushoku Tensei II: Isekai Ittara Honki Dasu",
        "https://cdn.myanimelist.net/images/anime/1898/138005.jpg",
        12,
        "R - 17+ (violence & profanity)",
        Synopsis.MushokuTensei2,
        [],
        "TV",
        "Jul 10 2023 to Sep 25 2023",
        "Summer 2023",
        "Studio Bind",
        "Light novel",
        ["Adventure", "Drama", "Fantasy", "Ecchi"],
        ["Isekai", "Reincarnation"],
        "23 minutes"
    ),
    new Anime(
        "Mushoku Tensei: Jobless Reincarnation Season 2 Part 2",
        "Mushoku Tensei II: Isekai Ittara Honki Dasu Part 2",
        "https://cdn.myanimelist.net/images/anime/1876/141251.jpg",
        12,
        "R - 17+ (violence & profanity)",
        Synopsis.MushokuTensei2Part2,
        [],
        "TV",
        "Apr 8 2024 to Jul 1 2024",
        "Spring 2024",
        "Studio Bind",
        "Light novel",
        ["Adventure", "Drama", "Fantasy", "Ecchi"],
        ["Isekai", "Reincarnation"],
        "23 minutes"
    ),
    new Anime(
        "My Deer Friend Nokotan",
        "Shikanoko Nokonoko Koshitantan",
        "https://cdn.myanimelist.net/images/anime/1094/143324.jpg",
        -1,
        "PG-13 - Teens 13 or older",
        Synopsis.Nokotan,
        [],
        "TV",
        "Jul 7 2024 to ?",
        "Summer 2024",
        "Wit Studio",
        "Manga",
        ["Comedy"],
        ["Gag Humor", "School"],
        "23 minutes"
    ),
    new Anime(
        "Rent-a-Girlfriend Season 3",
        "Kanojo, Okarishimasu 3rd Season",
        "https://cdn.myanimelist.net/images/anime/1696/136634.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.RentAGirlfriend3,
        [""],
        "TV",
        "Jul 8 2023 to Sep 30 2023",
        "Summer 2023",
        "TMS Entertainment",
        "Manga",
        ["Comedy", "Romance"],
        ["Shounen"],
        "23 minutes",
    ),
    new Anime(
        "The iDOLM@STER Cinderella Girls: U149",
        "",
        "https://cdn.myanimelist.net/images/anime/1875/133377.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.IdolMasterU149,
        [""],
        "TV",
        "Apr 6 2023 to Jun 29 2023",
        "Spring 2023",
        "CygamesPictures",
        "Web manga",
        ["lol"],
        ["Idols (Female)", "Music"],
        "24 minutes",
    ),
    new Anime(
        "My Clueless First Friend",
        "Jijou wo Shiranai Tenkousei ga Guigui Kuru.",
        "https://cdn.myanimelist.net/images/anime/1350/133642.jpg",
        13,
        "PG-13 - Teens 13 or older",
        Synopsis.CluelessFirstFriend,
        [""],
        "TV",
        "Apr 9 2023 to Jul 2 2023",
        "Spring 2023",
        "Studio Signpost",
        "Manga",
        ["Comedy"],
        ["Romantic Subtext", "School"],
        "23 minutes",
    ),
    new Anime(
        "Fight League: Gear Gadget Generators",
        "",
        "https://cdn.myanimelist.net/images/anime/1351/96571.jpg",
        26,
        "PG-13 - Teens 13 or older",
        Synopsis.FightLeague,
        [""],
        "ONA",
        "Feb 14 2019 to Aug 8 2019",
        "Winter 2019",
        "Bandai Namco Pictures, XFLAG",
        "Game",
        ["Action", "Sci-Fi"],
        ["Mecha"],
        "10 minutes",
    ),
];