import { Anime } from "@/lib/class/Anime";
import { Synopsis } from "./wSynopsis";

export const w_anime = [
    new Anime(
        "Wandering Witch: The Journey of Elaina",
        "Majo no Tabitabi",
        "https://cdn.myanimelist.net/images/anime/1802/108501.jpg",
        12,
        "R - 17+ (violence & profanity)",
        Synopsis.WanderingWitch,
        [""],
        "TV",
        "Oct 2 2020 to Dec 18 2020",
        "Fall 2020",
        "C2C",
        "Light novel",
        ["Adventure", "Fantasy"],
        [""],
        "24 minutes",
    ),
    new Anime(
        "Wagamama High Spec",
        "",
        "https://cdn.myanimelist.net/images/anime/3/79135.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Wagamama,
        [""],
        "TV",
        "Apr 12 2016 to Jun 28 2016",
        "Spring 2016",
        "AXsiZ",
        "Visual novel",
        ["Comedy"],
        ["School"],
        "3 minutes",
    ),
    new Anime(
        "WataTen! An Angel Flew Down to Me",
        "Watashi ni Tenshi ga Maiorita!",
        "https://cdn.myanimelist.net/images/anime/1778/100470.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.WataTen,
        [""],
        "TV",
        "Jan 8 2019 to Mar 26 2019",
        "Winter 2019",
        "Doga Kobo",
        "4-koma manga",
        ["Comedy"],
        ["CGDCT", "Otaku Culture"],
        "23 minutes",
    ),
    new Anime(
        "When SuperNatural Battles Become Commonplace",
        "Inou-Battle wa Nichijou-kei no Naka de",
        "https://cdn.myanimelist.net/images/anime/8/67047.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.SuperNaturalBattles,
        [""],
        "TV",
        "Oct 7 2014 to Dec 23 2014",
        "Fall 2014",
        "Trigger",
        "Light novel",
        ["Comedy", "Supernatural"],
        ["Harem", "School", "Super Power"],
        "24 minutes",
    ),
    new Anime(
        "WIXOSS Diva(A)Live",
        "",
        "https://cdn.myanimelist.net/images/anime/1779/110807.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Wixoss,
        [""],
        "TV",
        "Jan 9 2021 to Mar 27 2021",
        "Winter 2021",
        "J.C. Staff",
        "Card game",
        ["lol"],
        ["Strategy Game"],
        "23 minutes",
    ),
    new Anime(
        "Wagnaria!!",
        "Working!!",
        "https://cdn.myanimelist.net/images/anime/7/73886.jpg",
        13,
        "PG-13 - Teens 13 or older",
        Synopsis.Wagnaria,
        [""],
        "TV",
        "Apr 4 2010 to Jun 27 2010",
        "Spring 2010",
        "A-1 Pictures",
        "4-koma manga",
        ["Comedy"],
        ["Romantic Subtext", "Workplace"],
        "24 minutes",
    ),
    new Anime(
        "Wagnaria!!2",
        "Working'!!",
        "https://cdn.myanimelist.net/images/anime/3/75263.jpg",
        13,
        "PG-13 - Teens 13 or older",
        Synopsis.Wagnaria2,
        [""],
        "TV",
        "Oct 1 2011 to Dec 24 2011",
        "Fall 2021",
        "A-1 Pictures",
        "4-koma manga",
        ["Comedy"],
        ["Romantic Subtext", "Workplace"],
        "24 minutes",
    ),
    new Anime(
        "Wagnaria!!3",
        "Working!!!",
        "https://cdn.myanimelist.net/images/anime/7/73886.jpg",
        13,
        "PG-13 - Teens 13 or older",
        Synopsis.Wagnaria3,
        [""],
        "TV",
        "Jul 5 2015 to Sep 27 2015",
        "Summer 2015",
        "A-1 Pictures",
        "4-koma manga",
        ["Comedy", "Romance"],
        ["Workplace"],
        "23 minutes",
    ),
    new Anime(
        "WWW.WAGNARIA!!",
        "WWW.Working!!",
        "https://cdn.myanimelist.net/images/anime/11/82287.jpg",
        13,
        "PG-13 - Teens 13 or older",
        Synopsis.WWW_Wagnaria,
        [""],
        "TV",
        "Oct 1 2016 to Dec 24 2016",
        "Fall 2016",
        "A-1 Pictures",
        "Web manga",
        ["Comedy"],
        ["Workplace"],
        "23 minutes",
    ),
]