export const Synopsis = {
    WanderingWitch: `Since childhood, Elaina has always been fascinated by the stories written within her favorite book, especially those about Nike, a renowned witch who had numerous great travels across the world. Wanting to experience the awe of adventure herself, Elaina strives to become a witch, and despite the numerous trials that come her way, she eventually succeeds.
                     Now a full-fledged witch, Elaina finally embarks on her long-awaited journey, in which she meets many people along the way, learning their various stories. Through all of this, she explores the world at its fullest—experiencing both its bright and dark sides—starting her legendary tale.`,

    Wagamama: `The adorable girls of Ousui Academy's student council love to spend time with their crush, Kouki Narumi. But what happens when he isn't around?
               For the student council, consisting of otaku president Kaoruko Rokuonji; headstrong Ashe Rufflette Sakuragi; quiet computer programmer Toa Narumi; and Toa's best friend, the impish Mihiro Miyase, it means they will have to keep themselves entertained. Wagamama High Spec offers a glimpse into the girls' lives as they get into amusing—and sometimes risqué—hijinks at their school and around town.`,

    WataTen: `College student Miyako Hoshino is quite shy around other people. She mostly spends her time in her room making cosplay outfits. When her fifth-grade sister Hinata brings her classmate Hana Shirosaki home, Miyako instantly becomes captivated with Hana's cuteness.
              Miyako tries to do various things, ranging from making Hana wear cosplay dresses to giving her sweets. This gives Hana a bad impression of her at first, but Miyako will do anything to grow closer to the angel who has descended before her.`,

    SuperNaturalBattles: `During a Literature Club meeting, the four club members—along with their faculty adviser's niece—suddenly find themselves with supernatural powers. Now capable of fabricating black flames, resident chuunibyou Jurai Andou is the most ecstatic about their new abilities; unfortunately, his own is only for show and unable to accomplish anything of substance. Moreover, he is completely outclassed by those around him: fellow club member Tomoyo Kanzaki manipulates time, Jurai's childhood friend Hatoko Kushikawa wields control over the five elements, club president Sayumi Takanashi can repair both inanimate objects and living things, and their adviser's niece Chifuyu Himeki is able to create objects out of thin air.
                          However, while the mystery of why they received these powers looms overhead, very little has changed for the Literature Club. The everyday lives of these five superpowered students continue on, albeit now tinged with the supernatural.`,

    Wixoss: `The story moves the "Wixoss" card game to the online virtual space of "Wixossland" as it continues to grow more popular. The game allows players to become the LRIG avatars themselves. The most popular format in the game is "Diva Battle," which allows three players to team up to compete against other units for the most "Selector" fans. Some units are idol-themed, while others are DJ- and band-themed.`,

    Wagnaria: `Due to his love for small, cute things, Souta Takanashi cannot turn childlike Popura Taneshima down when she recruits him to work for Wagnaria, a family restaurant located in Hokkaido. Takanashi takes particular joy in doting on the older Popura, which only fuels her complex over how young she looks. He also quickly learns he must stay on his toes once he meets the rest of his colleagues, including the katana-wielding floor chief Yachiyo Todoroki, the intimidating head chef Jun Satou, the dangerously well-informed and subtly sadistic sous chef Hiroomi Souma, the adamantly lazy manager Kyouko Shirafuji, and the waitress Mahiru Inami who has a "painful" fear of men.
               Powered by an eccentric cast, Working!! is a unique workplace comedy that follows the never-dull happenings within the walls of Wagnaria as Takanashi and his co-workers' quirky personalities combine to create non-stop antics, shenanigans, and hilarity.`,

    Wagnaria2: `The exciting antics of Wagnaria return as more ridiculous incidents occur, friendships are deepened, and new feelings are discovered. In addition to Souta Takanashi and his wacky co-workers, more eccentric personalities join the family restaurant: Haruna, Hyougo Otoo's missing wife, who has a habit of getting hopelessly lost through the sewer system; Kirio Yamada, Aoi's older brother, who is able to withstand Mahiru Inami's deadly punches; and twins Youhei and Mitsuki Mashiba, Kyouko Shirafuji's juniors who do not get along.
                Absurdity, romance, and hilarity are all on the menu for the Wagnaria family restaurant!`,

    Wagnaria3: `As the stories of those connected to Wagnaria come to a close, only one thing is certain: the workplace is about to get crazier than ever before! Whether it be incredibly awkward romances, relentless searches for lost relatives, or even uncomfortable family reunions, lover of all things cute and tiny Souta Takanashi and his motley crew have plenty on their plates. With more Napoleon complexes, androphobia, and katana-wielding than you can shake a frying pan at, Working!!! delivers a final serving of the staff's hilarious misadventures working at everybody's favorite family restaurant.`,

    WWW_Wagnaria: `Daisuke Higashida is a serious first-year student at Higashizaka High School. He lives a peaceful everyday life even though he is not satisfied with the family who doesn't laugh at all and makes him tired. However, his father's company goes bankrupt one day, and he can no longer afford allowances, cellphone bills, and commuter tickets. When his father orders him to take up a part-time job, Daisuke decides to work at a nearby family restaurant in order to avoid traveling 15 kilometers to school by bicycle.`,


}