import { Anime } from "@/lib/class/Anime";
import { Synopsis } from "./hSynopsis";

export const h_anime = [
    new Anime(
        "Hakone-chan",
        "Onsen Yousei Hakone-chan",
        "https://cdn.myanimelist.net/images/anime/12/77820.jpg",
        13,
        "PG-13 - Teens 13 or older",
        Synopsis.Hakonechan,
        [""],
        "TV",
        "Oct 4 2015 to Dec 27 2015",
        "Fall 2015",
        "Production Reed, Asahi Production",
        "Web manga",
        ["Comedy", "Supernatural"],
        [""],
        "3 minutes",
    ),
    new Anime(
        "HaNaYaMaTa",
        "",
        "https://cdn.myanimelist.net/images/anime/1963/90831.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Hanayamata,
        [""],
        "TV",
        "Jul 8 2014 to Sep 23 2014",
        "Summer 2014",
        "Madhouse",
        "Manga",
        ["Slice of Life"],
        ["CGDCT", "Iyashikei", "Performing Arts", "School"],
        "24 minutes",
    ),
    new Anime(
        "Haven't You Heard? I'm Sakamoto",
        "Sakamoto desu ga?",
        "https://cdn.myanimelist.net/images/anime/4/79468.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Sakamoto,
        [""],
        "TV",
        "Apr 8 2016 to Jul 1 2016",
        "Spring 2016",
        "Studio Deen",
        "Manga",
        ["Comedy"],
        ["Gag Humor", "School"],
        "24 minutes",
    ),
    new Anime(
        "Higehiro: After being Rejected, I Shaved and Took in a High School Runaway",
        "Hige wo Soru. Soshite Joshikousei wo Hirou.",
        "https://cdn.myanimelist.net/images/anime/1146/113477.jpg",
        13,
        "PG-13 - Teens 13 or older",
        Synopsis.Higehiro,
        [""],
        "TV",
        "Apr 5 2021 to Jun 28 2021",
        "Spring 2021",
        "Project No.9",
        "Light novel",
        ["Drama", "Romance"],
        [""],
        "23 minutes",
    ),
    new Anime(
        "Himegoto",
        "",
        "https://cdn.myanimelist.net/images/anime/8/75226.jpg",
        13,
        "PG-13 - Teens 13 or older",
        Synopsis.Himegoto,
        [""],
        "TV",
        "Jul 7 2014 to Sep 29 2014",
        "Summer 2014",
        "Asahi Production",
        "4-koma manga",
        ["Comedy", "Ecchi"],
        ["Crossdressing", "School"],
        "4 minutes",
    ),
    new Anime(
        "Himouto! Umaru-chan",
        "",
        "https://cdn.myanimelist.net/images/anime/12/75086.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Himouto,
        [""],
        "TV",
        "Jul 9 2015 to Sep 24 2015",
        "Summer 2015",
        "Doga Kobo",
        "Manga",
        ["Comedy"],
        ["Otaku Culture", "School"],
        "24 minutes",
    ),
    new Anime(
        "Himouto! Umaru-chan R",
        "",
        "https://cdn.myanimelist.net/images/anime/10/89671.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Himouto2,
        [""],
        "TV",
        "Oct 8 2017 to Dec 24 2017",
        "Fall 2017",
        "Doga Kobo",
        "Manga",
        ["Comedy"],
        ["Otaku Culture", "School"],
        "23 minutes",
    ),
    new Anime(
        "Hinako Note",
        "",
        "https://cdn.myanimelist.net/images/anime/2/84858.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.HinakoNote,
        [""],
        "TV",
        "Apr 7 2017 to Jun 23 2017",
        "Spring 2017",
        "Passione",
        "4-koma manga",
        ["Slice of Life"],
        ["CGDCT", "Performing Arts"],
        "23 minutes",
    ),
    new Anime(
        "Hitoribocchi no Marumaru Seikatsu",
        "",
        "https://cdn.myanimelist.net/images/anime/1130/99458.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Hitoribocchi,
        [""],
        "TV",
        "Apr 6 2019 to Jun 22 2019",
        "Spring 2019",
        "C2C",
        "4-koma manga",
        ["Comedy"],
        ["CGDCT", "School"],
        "23 minutes",
    ),
    new Anime(
        "How clumsy you are, Miss Ueno",
        "Ueno-san wa Bukiyou",
        "https://cdn.myanimelist.net/images/anime/1874/111374.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Ueno,
        [""],
        "TV",
        "Jan 7 2019 to Mar 25 2019",
        "Winter 2019",
        "Lesprit",
        "Manga",
        ["Comedy"],
        ["Romantic Subtext", "School"],
        "12 minutes",
    )
]