export const Synopsis = {
    Hakonechan: `After many years of dormant rest, a hot springs fairy awakens in modern-day Japan. However, while she slept, she took on the appearance of a young girl. She decides to cooperate with the locals whilst trying to regain her powers.`,

    Hanayamata: `At the tender age of 14, high school student Naru Sekiya finds that she pales in comparison to the fairy tale princesses she adores so much, not to mention the ideal girl she wants to be in contrast to her peers. Her childhood friend Yaya Sasame is enjoying herself with her school rock band, while her other childhood friend Tami Nishimikado is a member of the student council. Desiring the strength to take the next step forward, Naru has wanted a magic key to open her timid heart since the start of high school.
                 During one moonlit night, Naru encounters what she believes is a cute fairy standing atop a torii gate who shortly invites her to dance with her. The next day, she discovers that the "fairy" was not only just an ordinary girl, but also a transfer high school student from America! Excited to meet Naru again, Hana N. Fountainstand encourages her to help her start a club for yosakoi, a festive type of Japanese dance that Hana has been entranced by since childhood.
                 Though initially terrified of Hana's enthusiasm and the thought of being seen dancing, Naru slowly finds herself immersed in the art of yosakoi and assisting her new friend achieve her dream—for the path for a maiden such as herself is at the mercy of the wind!`,

    Sakamoto: `Sophisticated, suave, sublime; all words which describe the exceedingly handsome and patently perfect Sakamoto. Though it is only his first day in high school, his attractiveness, intelligence, and charm already has the girls swooning and the guys fuming with jealousy. No one seems able to derail him, as all attempts at tripping him up are quickly foiled. His sangfroid is indomitable, his wits peerless. Will any of Sakamoto's classmates, or even teachers, be able to reach his level of excellence? Probably not, but they just might learn a thing or two trying...`,

    Higehiro: `When regular salaryman Yoshida wakes up one Sunday morning after a long night at the bar, the last thing he expects to see is that his tiny apartment has a new resident—an unfamiliar high school girl.
               The previous night, despite finally gathering the courage to confess to his boss and longtime crush, Airi Gotou, Yoshida was rejected. After drowning his sorrows at a bar with his good friend Hashimoto, Yoshida headed back to his home in a drunken stupor, only to run into Sayu Ogiwara, a runaway high schooler. She asked him to let her stay the night, and with his judgment clouded by alcohol, Yoshida complied.
               Now, with his head on straight but with no memory of last night's events, Yoshida has Sayu explain just how she ended up sleeping at his apartment. Having listened to her story, Yoshida finds himself unable to kick her out—especially after learning that she came all the way from Hokkaido! So, despite his reservations about sheltering an underage girl, Yoshida allows her to stay, and their life together begins.`,

    Himegoto: `Constantly on the run from loan sharks, Hime Arikawa has to deal with the debt left over from his parents' lousy spending habits, which they left under his name. Fleeing in a maid outfit forced upon him by the moneylenders, he is found and rescued by Shimoshina High School's student council, who pay the debt in full. However, now indebted to the student council for saving him, they not only make Hime transfer schools, but also make him a part of the student council as their servant!
               Forced to cross-dress for the rest of his high school years, Hime has no other option but to obey the demands of the girls in the student council. As he is harassed both mentally and physically, he must overcome his somewhat perverted classmates and join forces with other crossdressers throughout the school.`,

    Himouto: `People are not always who they appear to be, as is the case with Umaru Doma, the perfect high school girl—that is, until she gets home! Once the front door closes, the real fun begins. When she dons her hamster hoodie, she transforms from a refined, over-achieving student into a lazy, junk food-eating otaku, leaving all the housework to her responsible older brother Taihei. Whether she's hanging out with her friends Nana Ebina and Kirie Motoba, or competing with her self-proclaimed "rival" Sylphinford Tachibana, Umaru knows how to kick back and have some fun!
              Himouto! Umaru-chan is a cute story that follows the daily adventures of Umaru and Taihei, as they take care of—and put up with—each other the best they can, as well as the unbreakable bonds between friends and siblings.`,

    Himouto2: `Umaru Doma is a model student who has a hidden side: when she gets home each day, she puts on her hamster hoodie and turns into a sluggish otaku fond of junk food. As Umaru continues these daily antics, the friendship between her and her classmates—Nana Ebina, Kirie Motoba, and Sylphinford Tachibana—deepens, and more and more interesting events begin to unfold.
               Of course, these events give rise to numerous questions. What did Nana ask of Umaru's brother Taihei? Who is the mysterious girl with the diamond hairpin? And most important of all: why does this girl seem to know Umaru? These questions and more will be answered in Himouto! Umaru-chan R!`,

    HinakoNote: `Born and raised in the countryside of Japan, Hinako "Hina" Sakuragi gets anxious easily when she talks to new people—so much so that she resembles a stiff scarecrow. To overcome this, Hina hopes to get involved in theater, inspired by a play she saw during her school's field trip. So, Hina moves into the Hitotose Manor in the bustling city of Tokyo to study at Fujiyama High School, aspiring to join the school's renowned theater club.
                 But to Hina's dismay, she learns that Fujiyama High's theater club has been on a lengthy hiatus. Having already come to Tokyo and enrolled in the school, Hina is at a loss for what to do next. Sensing her disappointment and eagerness to learn theater, Chiaki Hagino, the landlady of Hitotose Manor, encourages Hina to create a troupe with the residents of Hitotose Manor as its members.
                 Hinako Note follows Hina as she begins a new life in Tokyo attending Fujiyama High while learning the ropes of theater with the support of her friends along the way.`,

    Hitoribocchi: `Many of us know what it is like to transition to a new school with few to no friends in a new environment, going through the arduous process of getting to know people again. Bocchi Hitori knows this struggle all too well, having just graduated from elementary school and thrown into middle school. Unfortunately, she suffers from extreme social anxiety: she faints when overwhelmed, vomits when nervous, and draws up ridiculously convoluted plans to avoid social contact. It does not help that her only friend from elementary school, Kai Yawara, will not be attending the same middle school as Bocchi. However, wanting to help her, Kai severs ties with Bocchi and promises to reconcile with her when she befriends all of her classmates in her new middle school class.
                   Even though Bocchi has no faith in herself, she is determined to be friends with Kai again. Summoning all of her courage, Bocchi takes on the daunting challenge of making friends with her entire class, starting with the delinquent-looking girl sitting in front of her...`,

    Horimiya: `On the surface, the thought of Kyouko Hori and Izumi Miyamura getting along would be the last thing in people's minds. After all, Hori has a perfect combination of beauty and brains, while Miyamura appears meek and distant to his fellow classmates. However, a fateful meeting between the two lays both of their hidden selves bare. Even though she is popular at school, Hori has little time to socialize with her friends due to housework. On the other hand, Miyamura lives under the noses of his peers, his body bearing secret tattoos and piercings that make him look like a gentle delinquent.
               Having opposite personalities yet sharing odd similarities, the two quickly become friends and often spend time together in Hori's home. As they both emerge from their shells, they share with each other a side of themselves concealed from the outside world.`,

    Ueno: `As the head of her middle school's science club, it's only fitting that Ueno is also a brilliant inventor. With devices that can convert any liquid into drinkable water, deodorize the most foul smells, or even generate dark matter to be used as a means of concealment, it seems like nothing is beyond Ueno's capabilities. However, she doesn't invent these devices for the advancement of mankind. Rather, the one force that motivates her is love, the only phenomenon she can't quite figure out.
           Ueno is head over heels for Tanaka, her nonchalant fellow club member. Yet, because she is too nervous to confess her love and he is too oblivious to notice her affection, her love life is completely stagnant. In Ueno's mind, if she could just expose him to perverted situations, then surely he'd get flustered and fall for her, right? Assisted by her stone-faced classmate and dedicated wingwoman Yamashita, Ueno employs her many inventions on Tanaka in a lewd manner in hopes that he may one day understand how she feels.`,


}