import { Anime } from "@/lib/Anime";
import { Synopsis } from "./nSynopsis";

export const n_anime = [
    new Anime(
        "Nekopara",
        "",
        "https://cdn.myanimelist.net/images/anime/1716/104880.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Nekopara,
        [""],
        "TV",
        "Jan 9 2020 to Mar 26 2020",
        "Winter 2020",
        "Felix Film",
        "Visual novel",
        ["Comedy", "Slice of Life"],
        ["Anthropomorphic"],
        "23 minutes",
    ),
    new Anime(
        "Netsuzou Trap -NTR-",
        "Netsuzou TRap",
        "https://cdn.myanimelist.net/images/anime/10/86667.jpg",
        12,
        "R+ - Mild Nudity",
        Synopsis.NetsuzouTrap,
        [""],
        "TV",
        "Jul 5 2017 to Sep 20 2017",
        "Summer 2017",
        "Creators in Pack",
        "Manga",
        ["Drama", "Girls Love"],
        [""],
        "9 minutes",
    ),
    new Anime(
        "New Game!",
        "",
        "https://cdn.myanimelist.net/images/anime/9/80417.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.NewGame,
        [""],
        "TV",
        "Jul 4 2016 to Sep 19 2016",
        "Summer 2016",
        "Doga Kobo",
        "4-koma manga",
        ["Comedy"],
        ["Adult Cast", "CGDCT", "Otaku Culture", "Workplace"],
        "24 minutes",
    ),
    new Anime(
        "New Game!!",
        "",
        "https://cdn.myanimelist.net/images/anime/4/86790.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.NewGame2,
        [""],
        "TV",
        "Jul 11 2017 to Sep 26 2017",
        "Summer 2017",
        "Doga Kobo",
        "4-koma manga",
        ["Comedy"],
        ["Adult Cast", "CGDCT", "Otaku Culture", "Workplace"],
        "24 minutes",
    ),
    new Anime(
        "Nichijou - My Ordinary Life",
        "Nichijou",
        "https://cdn.myanimelist.net/images/anime/3/75617.jpg",
        26,
        "PG-13 - Teens 13 or older",
        Synopsis.Nichijou,
        [""],
        "TV",
        "Apr 3 2011 to Sep 25 2011",
        "Spring 2011",
        "Kyoto Animation",
        "Manga",
        ["Comedy"],
        ["Gag Humor", "School"],
        "23 minutes",
    ),
    new Anime(
        "Nijiyon Animation",
        "",
        "https://cdn.myanimelist.net/images/anime/1977/135538.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Nijiyon,
        [""],
        "TV",
        "Jan 6 2023 to Mar 24 2023",
        "Winter 2023",
        "Sunrise",
        "4-koma manga",
        ["Comedy"],
        ["CGDCT", "Idols (Female)"],
        "3 minutes",
    ),
    new Anime(
        "Nisekoi: False Love",
        "Nisekoi",
        "https://cdn.myanimelist.net/images/anime/13/75587.jpg",
        20,
        "PG-13 - Teens 13 or older",
        Synopsis.Nisekoi,
        [""],
        "TV",
        "Jan 11 2014 to May 24 2014",
        "Winter 2014",
        "Shaft",
        "Manga",
        ["Comedy", "Romance"],
        ["Harem", "School"],
        "24 minutes",
    ),
    new Anime(
        "Nisekoi: False Love Season 2",
        "Nisekoi:",
        "https://cdn.myanimelist.net/images/anime/13/72626.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Nisekoi2,
        [""],
        "TV",
        "Apr 10 2015 to Jun 26 2015",
        "Spring 2015",
        "Shaft",
        "Manga",
        ["Comedy", "Romance"],
        ["Harem", "School"],
        "24 minutes",
    ),
    new Anime(
        "No Game, No Life",
        "No Game No Life",
        "https://cdn.myanimelist.net/images/anime/1074/111944.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.NoGameNoLife,
        [""],
        "TV",
        "Apr 9 2014 to Jun 25 2014",
        "Spring 2014",
        "Madhouse",
        "Light novel",
        ["Comedy", "Fantasy", "Ecchi"],
        ["Isekai", "Strategy Game"],
        "23 minutes",        
    ),
    new Anime(
        "Non Non Biyori",
        "",
        "https://cdn.myanimelist.net/images/anime/2/51581.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.NonNonBiyori,
        [""],
        "TV",
        "Oct 8 2013 to Dec 24 2013",
        "Fall 2013",
        "SILVER LINK",
        "Manga",
        ["Slice of Life"],
        ["CGDCT", "Iyashikei", "School"],
        "24 minutes",
    ),
    new Anime(
        "Non Non Biyori Repeat",
        "",
        "https://cdn.myanimelist.net/images/anime/9/75105.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.NonNonBiyori2,
        [""],
        "TV",
        "Jul 7 2015 to Sep 22 2015",
        "Summer 2015",
        "SILVER LINK",
        "Manga",
        ["Slice of Life"],
        ["CGDCT", "Iyashikei", "School"],
        "23 minutes",
    ),
    new Anime(
        "Non Non Biyori Nonstop",
        "",
        "https://cdn.myanimelist.net/images/anime/1033/111540.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.NonNonBiyori3,
        [""],
        "TV",
        "Jan 11 2021 to Mar 29 2021",
        "Winter 2021",
        "SILVER LINK",
        "Manga",
        ["Slice of Life"],
        ["CGDCT", "Iyashikei", "School"],
        "24 minutes",
    ),
    new Anime(
        "Nyaruko: Crawling With Love!",
        "Haiyore! Nyaruko-san",
        "https://cdn.myanimelist.net/images/anime/6/49081.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Nyaruko,
        [""],
        "TV",
        "Apr 10 2012 to Jun 26 2012",
        "Spring 2012",
        "Xebec",
        "Light novel",
        ["Comedy", "Sci-Fi"],
        ["Parody"],
        "24 minutes",
    ),
    new Anime(
        "Nyaruko: Crawling With Love! Second Season",
        "Haiyore! Nyaruko-san W",
        "https://cdn.myanimelist.net/images/anime/10/47533.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Nyaruko2,
        [""],
        "TV",
        "Apr 8 2013 to Jul 1 2013",
        "Spring 2013",
        "Xebec",
        "Light novel",
        ["Comedy", "Sci-Fi"],
        ["Parody"],
        "24 minutes",
    ),
]