export const Synopsis = {
    Nekopara: `The siblings Kashou and Shigure Minazuki enjoy the company of six catgirls. Chocola and Vanilla assist Kashou in his job as a baker at the patisserie La Soleil, while the others—Coconut, Azuki, Cinnamon, and Maple—accompany Shigure in her daily life back at their home.
               One afternoon, when Chocola goes out for an errand, she notices a green-haired kitten alone by herself at a park and decides to bring her back to the patisserie. Soon after, the Minazuki household adopts her and gives her a name: Cacao. With a new member in their family, the members of the Minazuki household continue their everyday lives—bound to become livelier than ever.`,

    NetsuzouTrap: `High school students Yuma Okazaki and Hotaru Mizushina are childhood friends. With their respective boyfriends, Takeda and Fujiwara, their lives couldn't be more perfect. From playing in school to going on group dates, it seems nothing can break their bond.
                   However, during one such group date, Hotaru makes an unexpected move. While Takeda and Fujiwara are distracted, she begins stroking Yuma's thighs. Taken aback by this peculiar action, Yuma awkwardly retreats to the toilets, followed shortly by her aggressor. Now in private, Hotaru forces the innocent Yuma into a locked cubicle and whispers into her ear: "You'll be more nervous with a boy; I'll help you practice."`,

    NewGame: `Since childhood, Aoba Suzukaze has loved the Fairies Story game series, particularly the character designs. So when she graduates from high school, it is no surprise that she applies to work at Eagle Jump, the company responsible for making her favorite video game. On her first day, she is excited to learn that she will be working on a new installment to the series: Fairies Story 3—and even more so under Kou Yagami, the lead character designer.
              In their department are people who share the same passion for games. There is Yun Iijima, whose specialty is designing monsters; the shy Hifumi Takimoto, who prefers to communicate through instant messaging; Hajime Shinoda, an animation team member with an impressive figurine collection; Rin Tooyama, the orderly art director; Shizuku Hazuki, the game director who brings her cat to work; and Umiko Ahagon, the short-tempered head programmer.
              New Game! follows Aoba and the others on their adventure through the ups and downs of game making, from making the perfect character design to fixing all the errors that will inevitably accumulate in the process.`,

    NewGame2: `It has been a year since Aoba Suzukaze started working at the Eagle Jump game company. In that time, she and her eccentric coworkers in the character design department have worked hard to release the company's newest game: Fairies Story 3. With their latest title now complete, a new project must begin—starting with a contest to decide the character designs for the upcoming game. Through hard work, dedication, and some guidance from the previous character designer, Kou Yagami, Aoba wins the contest and begins her new role as lead character designer.
               However, her new job is not an easy one. In addition to having extra work and longer hours, Aoba questions whether she is the right fit for the job. As she overcomes her inexperience with the help of her friends and coworkers, Aoba is willing to face any challenge to make Eagle Jump's newest creation, a cutesy game called Peco.`,

    Nichijou: `Nichijou primarily focuses on the daily antics of a trio of childhood friends—high school girls Mio Naganohara, Yuuko Aioi and Mai Minakami—whose stories soon intertwine with the young genius Hakase Shinonome, her robot caretaker Nano, and their talking cat Sakamoto. With every passing day, the lives of these six, as well as of the many people around them, experience both the calms of normal life and the insanity of the absurd. Walking to school, being bitten by a talking crow, spending time with friends, and watching the principal suplex a deer: they are all in a day's work in the extraordinary everyday lives of those in Nichijou.`,

    Nijiyon: `Short anime based on the 4-koma series illustrating the daily lives of the Nijigasaki High School Idol Club’s members.`,

    Nisekoi: `Raku Ichijou, a first-year student at Bonyari High School, is the sole heir to an intimidating yakuza family. Ten years ago, Raku made a promise to his childhood friend. Now, all he has to go on is a pendant with a lock, which can only be unlocked with the key which the girl took with her when they parted.
              Now, years later, Raku has grown into a typical teenager, and all he wants is to remain as uninvolved in his yakuza background as possible while spending his school days alongside his middle school crush Kosaki Onodera. However, when the American Bee Hive Gang invades his family's turf, Raku's idyllic romantic dreams are sent for a toss as he is dragged into a frustrating conflict: Raku is to pretend that he is in a romantic relationship with Chitoge Kirisaki, the beautiful daughter of the Bee Hive's chief, so as to reduce the friction between the two groups. Unfortunately, reality could not be farther from this whopping lie—Raku and Chitoge fall in hate at first sight, as the girl is convinced he is a pathetic pushover, and in Raku's eyes, Chitoge is about as attractive as a savage gorilla.
              Nisekoi follows the daily antics of this mismatched couple who have been forced to get along for the sake of maintaining the city's peace. With many more girls popping up his life, all involved with Raku's past somehow, his search for the girl who holds his heart and his promise leads him in more unexpected directions than he expects.`,

    Nisekoi2: `Despite having seemingly quelled the war between their respective gangs, Raku Ichijou and Chitoge Kirisaki still carry on with their fake relationship. Eventually, as Chitoge's perception of Raku slowly changes, she even begins to see him as a little charming.
               Chitoge struggles to come to terms with her newfound feelings for Raku, as a new girl joins the slew of Raku's admirers and the competition among those vying for the yakuza heir's attention grows even fiercer. And amidst all this, Raku's search for his first love and the contents of the mysterious sealed locket continues in Nisekoi:, which picks up where the first season left off.`,

    NoGameNoLife: `Sixteen sentient races inhabit Disboard, a world overseen by Tet, the One True God. The lowest of the sixteen—Imanity—consists of humans, a race with no affinity for magic. In a place where everything is decided through simple games, humankind seems to have no way out of their predicament—but the arrival of two outsiders poses a change.
                   On Earth, stepsiblings Sora and Shiro are two inseparable shut-ins who dominate various online games under the username "Blank." While notorious on the internet, the pair believe that life is merely another dull game. However, after responding to a message from an unknown user, they are suddenly transported to Disboard. The mysterious sender turns out to be Tet, who informs them about the world's absolute rules. After Tet leaves, Sora and Shiro begin their search for more information and a place to stay, taking them to Elkia—Imanity's only remaining kingdom.
                   There, the duo encounters Stephanie Dola, an emotional girl vying for the kingdom's sovereignty. In desperation, she attempts to regain her father's throne, but her foolhardiness makes her goal unachievable. Inspired by the girl's motivation and passion, Sora and Shiro decide to aid Stephanie in getting Elkia back on its feet, ultimately aiming to become the new rulers of the enigmatic realm.`,

    NonNonBiyori: `Hotaru Ichijou's lifestyle completely changes when she leaves Tokyo and moves with her family to the isolated Asahigaoka village. Her new school has only five students including herself, all sharing a single classroom regardless of grade level. There are no convenience stores in the area, and it can take up to two hours for a bus to arrive.
                   Nevertheless, Hotaru finds herself captivated by the countryside's charm thanks to her four unique schoolmates with whom she quickly forms a genuine bond. The most colorful of them is Renge Miyauchi, a first-grader who is often perceptive despite her age. However, no less intriguing are the three Koshigaya siblings: the quiet oldest brother Suguru, the petite older sister Komari, and the prankish youngest sister Natsumi.
                   Having someone from the city join their cheerful little group enlivens the ordinary days in Asahigaoka. Not only does Hotaru bring firsthand knowledge from the alluring outside world, but her fresh outlook on life welcomes a blossom of change to their usual routine.`,

    NonNonBiyori2: `Far from the hustle and bustle of urban life, and with only a single candy store and bus route to its name, the rural Asahigaoka is certainly not a place for everyone. Nevertheless, the village's children still manage to cheerfully spend their days exploring and having fun in the wilderness around them. One such child, Renge Miyauchi, the youngest of the group, looks forward to the entrance ceremony of the upcoming school year, signalling her entry into first grade and the beginning of her elementary school life. Attending the only school in town, Renge and her friends, seventh grader Natsumi Koshigaya and her eighth grade sister Komari, make the most out of their rural lifestyle, playing and studying everyday.
                    Meanwhile, fifth grader Hotaru Ichijou has just moved to Asahigaoka from Tokyo, unaware of the numerous adventures and memories that await her.`,

    NonNonBiyori3: `The carefree journeys of the four girls continue! As their fleeting yet eventful summer becomes a distant memory, the arrival of fall signals a new school year with limitless opportunities. Even as the four girls return to their peaceful routine, the appearance of new faces enlivens the anything but exciting rural life of Asahigaoka.
                    Non Non Biyori Nonstop leisurely walks back into the lives of Hotaru Ichijou, Komari Koshigaya, Natsumi Koshigaya, and Renge Miyauchi as they fully embrace their rural lifestyles and turn anything they find into nothing but fun!`,

    Nyaruko: `Mahiro Yasaka is just an ordinary high school student, until one day he is suddenly attacked by a dangerous monster. Just when everything seems to be lost, he is saved by a silver-haired girl named Nyaruko, who claims to be the shape-shifting deity Nyarlathotep from horror author H. P. Lovecraft's Cthulhu Mythos, sent by the Space Defense Agency to Earth. She explains to Mahiro that the creature chasing him was an alien called Nightgaunt, who had planned on abducting and selling him as a slave.
              After rescuing him from the alien, the Lovecraftian deity falls madly in love with Mahiro and forces herself into his household, much to his chagrin. Moreover, they are soon joined by two others from the fictional universe: Cthuko, a girl obsessed with Nyaruko, and Hasuta, a young boy easily mistaken for a beautiful female. Together, the three eccentric aliens protect Mahiro from the various extraterrestrial dangers that threaten both his and Earth's well-being, all the while making his life a living hell.`,

    Nyaruko2: `Nyaruko still wants Mahiro, as does Hasuta. Kūko wants Nyaruko, but believes both Nyaruko's and Mahiro's "first time" belongs to her. Yoriko puts up with all of it and cheerfully runs the house where they all live. Mahiro just wants some sanity. He doesn't want to be the love toy of a Nyarlathotepan, Cthughan, or a shots-like Hasturan. He may or may not hold out.`,

    
}