import { Anime } from "@/lib/Anime";
import { Synopsis } from "./uSynopsis";

export const u_anime = [
    new Anime(
        "Uma Musume: Pretty Derby",
        "",
        "https://cdn.myanimelist.net/images/anime/1683/91888.jpg",
        13,
        "PG-13 - Teens 13 or older",
        Synopsis.Umamusume,
        [""],
        "TV",
        "Apr 2 2018 to Jun 18 2018",
        "Spring 2018",
        "P.A. Works",
        "Game",
        ["Sports"],
        ["Anthropomorphic", "Racing"],
        "23 minutes",
    ),
    new Anime(
        "Uma Musume: Pretty Derby Season 2",
        "",
        "https://cdn.myanimelist.net/images/anime/1447/114282.jpg",
        13,
        "PG-13 - Teens 13 or older",
        Synopsis.Umamusume2,
        [""],
        "TV",
        "Jan 5 2021 to Mar 30 2021",
        "Winter 2021",
        "Studio Kai",
        "Game",
        ["Sports"],
        ["Anthropomorphic", "Racing"],
        "23 minutes",
    ),
    new Anime(
        "Umayon",
        "",
        "https://cdn.myanimelist.net/images/anime/1032/111641.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Umayon,
        [""],
        "TV",
        "Jul 7 2020 to Sep 22 2020",
        "Summer 2020",
        "W-Toon Studio, DMM.futureworks",
        "4-koma manga",
        ["Comedy"],
        ["Anthropomorphic"],
        "3 minutes",
    ),
    new Anime(
        "Uncle from Another World",
        "Isekai Ojisan",
        "https://cdn.myanimelist.net/images/anime/1743/125204.jpg",
        13,
        "PG-13 - Teens 13 or older",
        Synopsis.IsekaiOjisan,
        [""],
        "TV",
        "Jul 6 2022 to Mar 8 2023",
        "Summer 2022",
        "AtelierPontdarc",
        "Web manga",
        ["Comedy", "Fantasy"],
        ["Adult Cast", "Isekai", "Otaku Culture", "Parody"],
        "24 minutes",
    ),
    new Anime(
        "Urawa no Usagi-chan",
        "",
        "https://cdn.myanimelist.net/images/anime/13/86398.jpg",
        12,
        "PG - Children",
        Synopsis.Urawa,
        [""],
        "TV",
        "Apr 10 2015 to Jun 26 2015",
        "Spring 2015",
        "A-Real",
        "Original",
        ["Comedy"],
        ["School"],
        "3 minutes",
    ),
]