import { Anime } from "@/lib/Anime";
import { Synopsis } from "./sSynopsis";

export const s_anime = [
    new Anime(
        "Sakura Trick",
        "",
        "https://cdn.myanimelist.net/images/anime/2/56189.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.SakuraTrick,
        [""],
        "TV",
        "Jan 10 2014 to Mar 28 2014",
        "Winter 2014",
        "Studio Deen",
        "4-koma manga",
        ["Comedy", "Girls Love"],
        ["School"],
        "24 minutes",
    ),
    new Anime(
        "School-Live!",
        "Gakkougurashi!",
        "https://cdn.myanimelist.net/images/anime/1798/91548.jpg",
        12,
        "R - 17+ (violence & profanity)",
        Synopsis.SchoolLive,
        [""],
        "TV",
        "Jul 9 2015 to Sep 24 2015",
        "Summer 2015",
        "Lerche",
        "Manga",
        ["Horror", "Mystery", "Slice of Life", "Supernatural", "Suspense"],
        ["Psychological", "School", "Survival"],
        "24 minutes",
    ),
    new Anime(
        "Seirei Gensouki: Spirit Chronicles",
        "Seirei Gensouki",
        "https://cdn.myanimelist.net/images/anime/1836/116060.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.SeireiGensouki,
        [""],
        "TV",
        "Jul 6 2021 to Sep 21 2021",
        "Summer 2021",
        "TMS Entertainment",
        "Light novel",
        ["Action", "Adventure", "Fantasy", "Romance"],
        ["Harem", "Isekai", "Reincarnation"],
        "23 minutes",
    ),
    new Anime(
        "Shomin Sample",
        'Ore ga Ojousama Gakkou ni "Shomin Sample" Toshite Gets♥Sareta Ken',
        "https://cdn.myanimelist.net/images/anime/9/76542.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.ShominSample,
        [""],
        "TV",
        "Oct 7 2015 to Dec 23 2015",
        "Fall 2015",
        "SILVER LINK",
        "Light novel",
        ["Comedy", "Romance", "Ecchi"],
        ["Harem", "School"],
        "23 minutes",
    ),
    new Anime(
        "Slow Loop",
        "",
        "https://cdn.myanimelist.net/images/anime/1360/119608.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.SlowLoop,
        [""],
        "TV",
        "Jan 7 2022 to Mar 25 2022",
        "Winter 2022",
        "Connect",
        "Manga",
        ["Gourmet", "Slice of Life"],
        ["CGDCT", "Iyashikei"],
        "24 minutes",
    ),
    new Anime(
        "Slow Start",
        "",
        "https://cdn.myanimelist.net/images/anime/4/89982.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.SlowStart,
        [""],
        "TV",
        "Jan 7 2018 to Mar 25 2018",
        "Winter 2018",
        "CloverWorks",
        "4-koma manga",
        ["Comedy"],
        ["CGDCT", "School"],
        "23 minutes",
    ),
    new Anime(
        "Sorairo Utility",
        "",
        "https://cdn.myanimelist.net/images/anime/1291/118973.jpg",
        1,
        "PG-13 - Teens 13 or older",
        Synopsis.SorairoUtility,
        [""],
        "TV Special",
        "Dec 31 2021",
        "Winter 2021",
        "Yostar Pictures",
        "Original",
        ["Sports"],
        ["CGDCT"],
        "14 minutes",
    ),
    new Anime(
        "Space Patrol Luluco",
        "Uchuu Patrol Luluco",
        "https://cdn.myanimelist.net/images/anime/4/79073.jpg",
        13,
        "PG-13 - Teens 13 or older",
        Synopsis.SpacePatrolLuluco,
        [""],
        "TV",
        "Apr 1 2016 to Jun 24 2016",
        "Spring 2016",
        "Trigger",
        "Original",
        ["Action", "Adventure", "Comedy", "Sci-Fi"],
        ["Parody", "Space"],
        "7 minutes",
    ),
    new Anime(
        "Spy x Family",
        "",
        "https://cdn.myanimelist.net/images/anime/1441/122795.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.SpyFamily,
        [""],
        "TV",
        "Apr 9 2022 to Jun 25 2022",
        "Spring 2022",
        "Wit Studio, CloverWorks",
        "Manga",
        ["Action", "Award Winning", "Comedy"],
        ["Childcare"],
        "24 minutes",
    ),
    new Anime(
        "Spy x Family Part 2",
        "",
        "https://cdn.myanimelist.net/images/anime/1111/127508.jpg",
        13,
        "PG-13 - Teens 13 or older",
        Synopsis.SpyFamily2,
        [""],
        "TV",
        "Oct 1 2022 to Dec 24 2022",
        "Fall 2022",
        "Wit Studio, CloverWorks",
        "Manga",
        ["Action", "Comedy"],
        ["Childcare"],
        "24 minutes",
    ),
    new Anime(
        "Spy x Family Code: White",
        "Spy x Family Movie: Code: White",
        "https://cdn.myanimelist.net/images/anime/1426/139388.jpg",
        1,
        "PG-13 - Teens 13 or older",
        Synopsis.SpyFamilyCodeWhite,
        [""],
        "Movie",
        "Dec 22 2023",
        "Winter 2023",
        "Wit Studio, CloverWorks",
        "Manga",
        ["Action", "Comedy"],
        ["Childcare"],
        "1 hour 50 minutes",
    ),
    new Anime(
        "SSSS.Dynazenon",
        "",
        "https://cdn.myanimelist.net/images/anime/1880/113766.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.SSSSDynazenon,
        [""],
        "TV",
        "Apr 2 2021 to Jun 18 2021",
        "Spring 2021",
        "Trigger",
        "Original",
        ["Action", "Sci-Fi"],
        ["Mecha"],
        "23 minutes",
    ),
    new Anime(
        "SSSS.Gridman",
        "",
        "https://cdn.myanimelist.net/images/anime/1973/95616.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.SSSSGridman,
        [""],
        "TV",
        "Oct 7 2018 to Dec 23 2018",
        "Fall 2018",
        "Trigger",
        "Original",
        ["Action", "Award Winning", "Sci-Fi"],
        ["Mecha"],
        "23 minutes",
    ),
    new Anime(
        "Strike Witches",
        "",
        "https://cdn.myanimelist.net/images/anime/13/75524.jpg",
        12,
        "R+ - Mild Nudity",
        Synopsis.StrikeWitches,
        [""],
        "TV",
        "Jul 4 2008 to Sep 19 2008",
        "Summer 2008",
        "Gonzo",
        "Original",
        ["Action", "Sci-Fi", "Ecchi"],
        ["Military"],
        "24 minutes",
    ),
    new Anime(
        "Strike Witches 2",
        "",
        "https://cdn.myanimelist.net/images/anime/13/25477.jpg",
        12,
        "R+ - Mild Nudity",
        Synopsis.StrikeWitches2,
        [""],
        "TV",
        "Jul 8 2010 to Sep 23 2010",
        "Summer 2010",
        "AIC Spirits",
        "Original",
        ["Action", "Sci-Fi", "Ecchi"],
        ["Military"],
        "24 minutes",
    ),
    new Anime(
        "Strike Witches: 501st JOINT FIGHTER WING Take off!",
        "Strike Witches: 501 Butai Hasshin Shimasu!",
        "https://cdn.myanimelist.net/images/anime/1515/100453.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.StrikeWitchesSpecial,
        [""],
        "TV",
        "Apr 10 2019 to Jun 26 2019",
        "Spring 2019",
        "Acca effe, Giga Production",
        "Manga",
        ["Comedy", "Sci-Fi"],
        ["CGDCT", "Military"],
        "13 minutes",
    ),
    new Anime(
        "Sword Art Online",
        "",
        "https://cdn.myanimelist.net/images/anime/11/39717.jpg",
        25,
        "PG-13 - Teens 13 or older",
        Synopsis.SwordArtOnline,
        [""],
        "TV",
        "Jul 8 2012 to Dec 23 2012",
        "Summer 2012",
        "A-1 Pictures",
        "Light novel",
        ["Action", "Adventure", "Fantasy", "Romance"],
        ["Love Polygon", "Video Game"],
        "23 minutes",
    ),
    new Anime(
        "Sword Art Online II",
        "",
        "https://cdn.myanimelist.net/images/anime/1223/121999.jpg",
        24,
        "PG-13 - Teens 13 or older",
        Synopsis.SwordArtOnline2,
        [""],
        "TV",
        "Jul 5 2014 to Dec 20 2014",
        "Summer 2014",
        "A-1 Pictures",
        "Light novel",
        ["Action", "Adventure", "Fantasy", "Romance"],
        ["Love Polygon", "Video Game"],
        "23 minutes",
    ),
    new Anime(
        "Sword Art Online: Alicization",
        "",
        "https://cdn.myanimelist.net/images/anime/1424/142754.jpg",
        24,
        "R - 17+ (violence & profanity)",
        Synopsis.SwordArtOnline3,
        [""],
        "TV",
        "Oct 7 2018 to Mar 31 2019",
        "Fall 2018",
        "A-1 Pictures",
        "Light novel",
        ["Action", "Adventure", "Fantasy"],
        ["Video Game"],
        "24 minutes",
    ),
    new Anime(
        "Sword Art Online: Alicization - War of Underworld",
        "",
        "https://cdn.myanimelist.net/images/anime/1630/103417.jpg",
        12,
        "R - 17+ (violence & profanity)",
        Synopsis.SwordArtOnline3_1,
        [""],
        "TV",
        "Oct 13 2019 to Dec 29 2019",
        "Fall 2019",
        "A-1 Pictures",
        "Light novel",
        ["Action", "Adventure", "Fantasy"],
        ["Video Game"],
        "23 minutes",
    ),
    new Anime(
        "Sword Art Online: Alicization - War of Underworld Part 2",
        "Sword Art Online: Alicization - War of Underworld 2nd Season",
        "https://cdn.myanimelist.net/images/anime/1438/105106.jpg",
        11,
        "R - 17+ (violence & profanity)",
        Synopsis.SwordArtOnline3_2,
        [""],
        "TV",
        "Jul 12 2020 to Sep 20 2020",
        "Summer 2020",
        "A-1 Pictures",
        "Light novel",
        ["Action", "Adventure", "Fantasy"],
        ["Video Game"],
        "24 minutes",
    ),
    new Anime(
        "Sword Art Online Alternative: Gun Gale Online",
        "",
        "https://cdn.myanimelist.net/images/anime/1141/93288.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.SwordArtOnlineAlternative,
        [""],
        "TV",
        "Apr 8 2018 to Jul 1 2018",
        "Spring 2018",
        "Studio 3Hz",
        "Light novel",
        ["Action"],
        ["Military", "Video Game"],
        "23 minutes",
    ),
]