export const Synopsis = {
    SakuraTrick: `Having been best friends since middle school, Haruka Takayama and Yuu Sonoda plan to attend Misato West High School together. However, despite being assigned to the same class, a cruel twist of fate has them seated on the opposite ends of their classroom! To make matters worse, their school will shut down in three years, making them the final intake of first-year students. Undeterred by this chain of unfortunate events, Haruka is set on sticking with Yuu, striving to create many wonderful memories with her.
                  Much to Haruka's jealousy however, Yuu's easygoing demeanor quickly attracts the attention of their female classmates. Sympathizing with her friend's growing insecurity, Yuu ends up sharing a deep, affectionate kiss with her in an empty classroom. The act intensifies their bond as "special friends," gradually revealing a different aspect to their unique friendship while also inviting new conflicts.`,

    SchoolLive: `Carefree high school senior Yuki Takeya every day looks forward to the School Living Club. Consisting of the president Yuuri Wakasa, the athletic Kurumi Ebisuzawa, the mature Miki Naoki, the supervising teacher Megumi Sakura, and club dog Taroumaru, the club prides itself on making the most of life at school. There is only one rule the club members have to follow: all members must live their entire lives within school grounds.
                 Gakkougurashi! follows the adventures of the School Living Club as they promote independence and self-determination through their lively time residing at Megurigaoka Private High School.`,

    ScottPilgrim: `The series, set in Toronto, Canada, serves as an alternate retelling of the original Scott Pilgrim graphic novel series and movie. Like in the original series, Scott Pilgrim, a bassist in an indie band, falls in love with Ramona Flowers, a mysterious delivery girl, attracting the attention of Ramona's seven evil exes. Things take an unexpected turn when Scott loses his battle against Ramona's first evil ex Matthew Patel and is seemingly killed. As the trajectory of everyone's lives, including those of Ramona's evil exes, changes drastically as a result, Ramona learns that Scott may still be alive and investigates his disappearance.`,

    SeireiGensouki: `When 20-year-old college student Haruto Amakawa dies in a traffic accident, he does not expect to wake up in an unfamiliar world in the body of a young boy named Rio. As their memories and personas fuse, Rio realizes that he now also possesses magical powers. He is relieved to find that his burning passion for revenge against his mother's murderers has not subsided, despite his newly changed identity.
                     Not soon after, Rio comes across the kidnapped princess of the Bertram Kingdom and saves her without hesitation. To express his gratitude, the king grants him the opportunity to enroll in the Bertram Royal Academy. Believing this to be a new chapter in his life, he is excited to study at this prestigious academy, but life here proves to be difficult for him, a slum-dweller surrounded by the majestic children of nobles.`,

    ShominSample: `Kimito Kagurazaka is a commoner with a fetish for men's muscles—or at least that's the lie he must keep telling if he wants to keep himself out of trouble at the elite all-girls school, Seikain Academy. Kidnapped by the school under the assumption that he prefers men, Kimito is made to be their "commoner sample," exposing the girls to both commoner and man so that the transition to the world after school is not jarring. Threatened with castration should his sexual preferences not match the school's assumptions, Kimito keeps up the facade to protect his manhood.
                   But there are eccentric individuals around every corner who begin to make Kimito's life even more difficult. Among them are Aika Tenkuubashi, a social outcast who blurts out whatever comes to mind; Hakua Shiodome, a young genius; Karen Jinryou, the daughter of samurai who is obsessed with defeating Kimito; and Reiko Arisugawa, the perfect student who has delusions of marrying Kimito. Along with the commoner himself, these four girls make up the Commoner Club, which attempts to teach the girls more about life outside the school, while Kimito gradually learns about the odd girls surrounding him.`,

    SlowLoop: `Since childhood, Hiyori Yamakawa has witnessed her father's various eccentricities, but one activity she has always loved doing with him is fly fishing—a complicated yet rewarding method of catching fish. Even after his sudden death, Hiyori still visits the seaside in her spare time, savoring the joy that her father's memento brings her.
               Three years later, Hiyori's mother decides to remarry and arranges a dinner with her fiancé, his daughter, and Hiyori to celebrate. Anxious and wanting to pass the time, Hiyori goes to her usual fishing spot when a rather energetic girl named Koharu Minagi suddenly appears before her. The two soon become acquainted, with Koharu taking an interest in fly fishing herself. However, their meeting is more than just a coincidence: Koharu turns out to be Hiyori's future stepsibling, which is only the beginning of treasured memories the both of them will reel in as they foster their sisterhood.`,

    SlowStart: `Hana Ichinose, a 17-year-old high school student who is not only introverted, but also insecure and timid, has just moved and will be attending a new school. To make her situation more difficult, Hana is a "slow start," which means that she missed a year and worries about attending a class where everyone is younger than her.
                During her introduction, the teacher reveals it is Hana's birthday, which gives her the jumping-off point to meet three of her classmates: Tamate Momochi, a charismatic and extroverted girl; Kanmuri Sengoku, who is shy and small; and the popular and pretty Eiko Tokura. Not wanting to lose the chance to make new friends, Hana's interactions with these three mark the beginning of some beautiful relationships that will change her life.`,

    SorairoUtility: `The special follows high school girl Minami, who is a beginner at golf, and her friends Haruka and Ayaka.`,

    SpacePatrolLuluco: `Living an abnormal existence in Ogikubo, an intergalactic melting pot of humans and aliens as well as the only Space Immigration Zone on Earth, Luluco is a bubbly middle school girl who just wants to be normal. One morning, however, her father, who works at the Space Patrol, eats a volatile sleep capsule by mistake and is frozen solid! To make matters worse, Luluco accidentally breaks him, so she hurries off to his office for help. There, the chief of the Space Patrol, Over Justice, hires Luluco as a space temp worker for undercover investigations, so that the institution may crack down on crime within her school.
                        Made to don the Space Patrol suit and sent on her way to mete out justice, Luluco attempts to maintain the image of a normal girl who does not stand out in any way. But she soon discovers that with the automatic systems and inherently zealous judiciousness of the Space Patrol suit, continuing to be normal will be more difficult than she thought.`,

    SpyFamily: `Corrupt politicians, frenzied nationalists, and other warmongering forces constantly jeopardize the thin veneer of peace between neighboring countries Ostania and Westalis. In spite of their plots, renowned spy and master of disguise "Twilight" fulfills dangerous missions one after another in the hope that no child will have to experience the horrors of war.
                In the bustling Ostanian city of Berlint, Twilight dons the alias of "Loid Forger," an esteemed psychiatrist. However, his true intention is to gather intelligence on prominent politician Donovan Desmond, who only appears rarely in public at his sons' school: the prestigious Eden Academy. Enlisting the help of unmarried city hall clerk Yor Briar to act as his wife and adopting the curious six-year-old orphan Anya as his daughter, Loid enacts his master plan. He will enroll Anya in Eden Academy, where Loid hopes she will excel and give him the opportunity to meet Donovan without arousing suspicion.
                Unfortunately for Loid, even a man of his talents has trouble playing the figure of a loving father and husband. And just like Loid is hiding his true identity, Yor—who is an underground assassin known as "Thorn Princess"—and Anya—an esper who can read people's minds—have no plans to disclose their own secrets either. Although this picture-perfect family is founded on deception, the Forgers gradually come to understand that the love they share for one another trumps all else.`,

    SpyFamilyPart2: `With Anya Forger successfully enrolled at the renowned Eden Academy, Operation Strix advances to its second phase. To investigate Ostanian politician Donovan Desmond, Anya must either befriend his son Damian or collect eight Stella Stars to become an Imperial Scholar. Fortunately, Anya has already acquired her first star. In celebration, her adoptive father, Loid, decides to fulfill her wish to adopt a dog.
                     During their canine search, Loid receives new orders from his superiors, who have found that a band of Berlint University students is plotting to assassinate Westalis' Minister Brantz using bombs worn by trained dogs. While Loid tries to stop their plans, Anya stumbles upon the terrorists' base of operations. There, she befriends a kindhearted, clairvoyant dog who the family later names Bond.
                     Although the Forgers continue to lead their individual lives in secrecy, the family—with a new fluffy addition—remains united through all of the unusual obstacles thrown their way.`,

    SpyFamily2: `With her ability to read minds, Anya Forger is the only one who knows the true identities of her unconventional family. Her pretend father Loid operates as an elite spy code-named Twilight; her mother Yor kills on demand as the assassin Thorn Princess; and their dog, Bond, possesses the gift of precognition. Although they hide the truth from each other, this pretense of a perfectly ordinary family provides Anya with the genuine love and warmth that she longed for as an orphan.
                 Operation Strix—Loid's special mission to avoid potential war by gathering vital information and getting close to the powerful political figure, Donovan Desmond—is only possible if Anya plays her part right. She can either excel academically and become an Imperial Scholar at her prestigious school or make friends with Donovan's son, Damian. Neither is exactly easy, but with her adventurous attitude, Anya throws herself wholeheartedly into her mission as a Forger—all for the sake of international peace.`,
 

    SpyFamilyCodeWhite: `Loid Forger, an elite spy, is warned by his handler that he may potentially be reassigned from his ongoing mission, Operation Strix. To maintain his position, he must make significant progress toward the operation's objectives, which involves having his adoptive daughter Anya earn sufficient Stella Stars to become an Imperial Scholar at Eden Academy.
                         After learning of a cooking contest that awards the winning student with a Stella Star, Loid researches the judge's preferred dessert to help increase Anya's odds. However, perfectly recreating the judge's favorite meremere requires more than just following a recipe. Thus, the Forgers embark on a vacation to the Frigis region to try an authentic meremere. Not all goes smoothly on the trip, as the Forger family ends up entwined in a sinister plot to reignite war between the countries of Ostania and Westalis.`,

    SSSSDynazenon: `One day after school, first-year high school student Yomogi Asanaka comes across a starving man under a bridge. Introducing himself as Gauma, the strange drifter informs Yomogi that he is a "kaiju user," a person who deals with the "kaiju"—monsters who bring harm to the city and its citizens.
                    The following evening, Yomogi runs into Gauma and his classmate Yume Minami. Simultaneously, a kaiju appears in a populated area of the city. Due to Gauma's lack of experience controlling the kaiju, he brings out a mysterious object from a glowing pouch, summoning a giant robot known as Dynazenon. Requiring the cooperation of four people, the mecha drags Gauma, Yomogi, Minami, and Koyomi Yamanaka—an unemployed man who was wandering on the street—into its cockpit.
                    Their encounter with the kaiju marks the beginning of their entanglement with kaiju eugenicists—kaiju users who manipulate kaiju with ill intent—and their efforts toward bringing out the full potential of Dynazenon.`,

    SSSSGridman: `Yuuta Hibiki wakes up in the room of Rikka Takarada and notices two things: he has no memories, and he can hear a mysterious voice calling his name from a nearby room. On further inspection, he finds a robot—which introduces itself as Hyper Agent Gridman—behind the screen of an old computer. Much to Yuuta's surprise, Rikka cannot hear Gridman, nor can she see the ominous monsters looming over a thick fog as it envelopes the town outside.
                  Another giant monster materializes in the city and proceeds to wreak havoc. Amidst the confusion, Yuuta is once again drawn to the old computer and merges with Gridman. Suddenly, he appears in the middle of the battle and is forced to fight the monster. Together with Rikka and fellow classmate Shou Utsumi, Yuuta forms the "Gridman Alliance" to defeat the monsters plaguing the city and find whoever is responsible for their emergence.`,

    StrikeWitches: `In the year 1939, humanity was on the verge of destruction. Equipped with weapons of devastating power, a mysterious alien race, known as the Neuroi, began an invasion of the Earth, ravaging the planet, obliterating countries, and vanquishing human armies. To counter this seemingly unstoppable force, the world's powers united. A new device was produced, called the Striker Unit, capable of facing Neuroi technology. Girls equipped with the Striker Unit became known as the Witches, forming humanity's last line of defense. They began their fight against the Neuroi, utilizing their now-enhanced magical abilities, flaunting destructive weapons no human could manage.
                    Fast forward to 1944—Yoshika Miyafuji is a young teenage girl who eventually decides to join the 501st Joint Fighter Wing, known as the "Strike Witches." With no formal training however, can Miyafuji learn to cooperate with her fellow Strike Witches? And if so, can she save humanity from the Neuroi onslaught?`,

    StrikeWitches2: `Six months have passed since the victorious Battle of Britannia and the reclamation of Gallia from Neuroi invaders. Yoshika Miyafuji, member of the famed 501st Joint Fighter Wing, has come back home to Fuso and graduated from middle school.
                     However, her fight is far from over. She receives a letter supposedly sent by her long-deceased father, containing blueprints of a state-of-the-art Striker Unit he had been working on before his death. The Unit, designed specifically for Yoshika, might be capable of harnessing her extraordinary magical powers.
                     Meanwhile, a new threat in Europe is rising. A Neuroi nest of an unprecedented size and might has appeared over Venezia, wiping out local Witch forces and instantly swallowing the northern part of the country. To make matters worse, a newly spotted humanoid type of Neuroi is attempting to come into contact with humans.
                     Yoshika, incapable of abandoning her friends on the front lines, must once again venture to the war-torn continent.`,

    StrikeWitchesSpecial: `Yoshika Miyafuji joins the 501st Joint Fighter Wing, a defense unit specializing in taking down alien beings known as the Neuroi. However, in days of no invasion, she and the members of the unit are taking down day to day tasks like cooking and laundry.`,

    SwordArtOnline: `Ever since the release of the innovative NerveGear, gamers from all around the globe have been given the opportunity to experience a completely immersive virtual reality. Sword Art Online (SAO), one of the most recent games on the console, offers a gateway into the wondrous world of Aincrad, a vivid, medieval landscape where users can do anything within the limits of imagination. With the release of this worldwide sensation, gaming has never felt more lifelike.
                     However, the idyllic fantasy rapidly becomes a brutal nightmare when SAO's creator traps thousands of players inside the game. The "log-out" function has been removed, with the only method of escape involving beating all of Aincrad's one hundred increasingly difficult levels. Adding to the struggle, any in-game death becomes permanent, ending the player's life in the real world.
                     While Kazuto "Kirito" Kirigaya was fortunate enough to be a beta-tester for the game, he quickly finds that despite his advantages, he cannot overcome SAO's challenges alone. Teaming up with Asuna Yuuki and other talented players, Kirito makes an effort to face the seemingly insurmountable trials head-on. But with difficult bosses and threatening dark cults impeding his progress, Kirito finds that such tasks are much easier said than done.`,

    SwordArtOnline2: `A year after escaping Sword Art Online, Kazuto Kirigaya has been settling back into the real world. However, his peace is short-lived as a new incident occurs in a game called Gun Gale Online, where a player by the name of Death Gun appears to be killing people in the real world by shooting them in-game. Approached by officials to assist in investigating the murders, Kazuto assumes his persona of Kirito once again and logs into Gun Gale Online, intent on stopping the killer.
                      Once inside, Kirito meets Sinon, a highly skilled sniper afflicted by a traumatic past. She is soon dragged in his chase after Death Gun, and together they enter the Bullet of Bullets, a tournament where their target is sure to appear. Uncertain of Death Gun's real powers, Kirito and Sinon race to stop him before he has the chance to claim another life. Not everything goes smoothly, however, as scars from the past impede their progress. In a high-stakes game where the next victim could easily be one of them, Kirito puts his life on the line in the virtual world once more.`,

    SwordArtOnline3: `The Soul Translator is a state-of-the-art full-dive interface which interacts with the user's Fluctlight—the technological equivalent of a human soul—and fundamentally differs from the orthodox method of sending signals to the brain. The private institute Rath aims to perfect their creation by enlisting the aid of Sword Art Online survivor Kazuto Kirigaya. He works there as a part-time employee to test the system's capabilities in the Underworld: the fantastical realm generated by the Soul Translator. As per the confidentiality contract, any memories created by the machine in the virtual world are wiped upon returning to the real world. Kazuto can only vaguely recall a single name, Alice, which provokes a sense of unease when mentioned in reality.
                      When Kazuto escorts Asuna Yuuki home one evening, they chance upon a familiar foe. Kazuto is mortally wounded in the ensuing fight and loses consciousness. When he comes to, he discovers that he has made a full-dive into the Underworld with seemingly no way to escape. He sets off on a quest, seeking a way back to the physical world once again.`,

    SwordArtOnline3_1: `Despite the defeat of Quinella—the pontifex of the Axiom Church—things have not seemed to calm down yet. Upon contacting the real world, Kazuto "Kirito" Kirigaya finds out that the Ocean Turtle—a mega-float controlled by Rath—was raided. Due to a sudden short-circuit caused by the raiders, Kirito's fluctlight is damaged, leaving him comatose. Feeling insecure about the people at the Axiom Church, Alice brings the unconscious Kirito back to their hometown—Rulid Village, disregarding her banishment due to an unabsolved crime. Now, Alice is living an ordinary and peaceful life close by the village, wishing for Kirito to wake up.
                        However, tragedy strikes when Alice notices that the Dark Territory has already started to invade the Human Empire. Reassuming her previous alias, Alice Synthesis Thirty, she promises to defeat the Dark Territory in order to defend the world that Kirito and Eugeo worked so hard to protect.`,

    SwordArtOnline3_2: `The final battle against the Dark Territory drags on, as players from all over the world flood the Underworld's servers and plunge the Human Empire into utter chaos. Asuna Yuuki and her friends defend their new allies with everything they have, but their numbers are falling. Meanwhile, Alice Zuberg heads toward the World's End Altar while Gabriel "Vecta" Miller relentlessly pursues her.
                        Meanwhile, members of Rath strategize a plan in an attempt to restore Kirito's damaged fluctlight. However, the intruders occupying the main control room have other plans. Surrounded by death and despair, when all hope seems to be lost, one voice reaches out to Kirito—a familiar one saying, "I will always be by your side."
                        Sword Art Online: Alicization - War of Underworld 2nd Season is the epic conclusion to Akihiko Kayaba's dream of creating artificial human intelligence. Now it is up to Kirito and his friends to protect this collapsing world from the people that still think it is just a game.`,

    SwordArtOnlineAlternative: `Clad in desert pink and the size of a mere child, the infamous "Pink Devil" mercilessly hunts down other players in the firearm-centered world of the virtual reality game Gun Gale Online. But in real life, this feared player killer is not quite who anyone would expect.
                                A shy university student in Tokyo, Karen Kohiruimaki stands in stark contrast to her in-game avatar—in fact, she happens to stand above everyone else too, much to her dismay. Towering above all the people around her, Karen's insecurities over her height reach the point where she turns to the virtual world for an escape. Starting game after game in hopes of manifesting as a cute, short character, she finally obtains her ideal self in the world of Gun Gale Online. Overjoyed by her new persona, she pours her time into the game as LLENN, garnering her reputation as the legendary player killer.
                                However, when one of LLENN's targets gets the best of her, she ends up meeting Pitohui, a skilled yet eccentric woman. Quickly becoming friends with Karen, Pitohui insists that LLENN participates in Squad Jam, a battle royale that pits teams against one another, fighting until only one remains. Thrust into the heated competition, LLENN must fight with all her wit and will if she hopes to shoot her way to the top.`,


}