import { Anime } from "@/lib/class/Anime";
import { Synopsis } from "./gSynopsis";

export const g_anime = [
    new Anime(
        "Gabriel Dropout",
        "",
        "https://cdn.myanimelist.net/images/anime/9/82590.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.GabrielDropout,
        [""],
        "TV",
        "Jan 9 2017 to Mar 27 2017",
        "Winter 2017",
        "Doga Kobo",
        "Manga",
        ["Comedy", "Supernatural"],
        ["CGDCT", "Mythology", "School"],
        "23 minutes",        
    ),
    new Anime(
        "Gakuen Handsome",
        "",
        "https://cdn.myanimelist.net/images/anime/5/81425.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.GakuenHandsome,
        [""],
        "TV",
        "Oct 4 2016 to Dec 20 2016",
        "Fall 2016",
        "Team YokkyuFuman",
        "Game",
        ["Boys Love", "Comedy"],
        ["Parody", "School"],
        "3 minutes",
    ),
    new Anime(
        "Ganbare Douki-chan",
        "",
        "https://cdn.myanimelist.net/images/anime/1185/117548.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.GanbareDouki,
        [""],
        "ONA",
        "Sep 20 2021 to Dec 6 2021",
        "Fall 2021",
        "AtelierPontdarc",
        "Web manga",
        ["Comedy", "Ecchi"],
        ["Adult Cast", "Romantic Subtext", "Workplace"],
        "5 minutes",
    ),
    new Anime(
        "Ghost Stories",
        "Gakkou no Kaidan",
        "https://cdn.myanimelist.net/images/anime/1414/112029.jpg",
        19,
        "PG-13 - Teens 13 or older",
        Synopsis.GhostStories,
        [""],
        "TV",
        "Oct 22 2000 to Mar 25 2001",
        "Fall 2000",
        "Pierrot",
        "Novel",
        ["Horror", "Mystery", "Supernatural"],
        [""],
        "24 minutes",
    ),
    new Anime(
        "Girlfriend, Girlfriend",
        "Kanojo mo Kanojo",
        "https://cdn.myanimelist.net/images/anime/1713/117119.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Girlfriend,
        [""],
        "TV",
        "Jul 3 2021 to Sep 18 2021",
        "Summer 2021",
        "Tezuka Productions",
        "Manga",
        ["Comedy", "Romance"],
        ["Harem", "School"],
        "24 minutes",
    ),
    new Anime(
        "Grand Blues!",
        "Guraburu!",
        "https://cdn.myanimelist.net/images/anime/1870/119993.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.GrandBlues,
        [""],
        "TV",
        "Oct 8 2020 to Dec 24 2020",
        "Fall 2020",
        "W-Toon Studio, DMM.futureworks",
        "4-koma manga",
        ["Adventure", "Fantasy"],
        [""],
        "3 minutes",
    ),
    new Anime(
        "GJ Club",
        "GJ-bu",
        "https://cdn.myanimelist.net/images/anime/10/45995.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.GJClub,
        [""],
        "TV",
        "Jan 10 2013 to Mar 28 2013",
        "Winter 2013",
        "Doga Kobo",
        "Light novel",
        ["Comedy"],
        ["School"],
        "23 minutes",
    ),
    new Anime(
        "Goblin Slayer",
        "",
        "https://cdn.myanimelist.net/images/anime/1719/95621.jpg",
        12,
        "R - 17+ (violence & profanity)",
        Synopsis.GoblinSlayer,
        [""],
        "TV",
        "Oct 7 2018 to Dec 30 2018",
        "Fall 2018",
        "White Fox",
        "Light novel",
        ["Action", "Adventure", "Fantasy"],
        ["Gore"],
        "23 minutes",
    ),
    new Anime(
        "Gurren Lagann",
        "Tengen Toppa Gurren Lagann",
        "https://cdn.myanimelist.net/images/anime/4/5123.jpg",
        27,
        "PG-13 - Teens 13 or older",
        Synopsis.GurrenLagann,
        [""],
        "TV",
        "Apr 1 2007 to Sep 30 2007",
        "Spring 2007",
        "Gainax",
        "Original",
        ["Action", "Adventure", "Award Winning", "Sci-Fi"],
        ["Mecha"],
        "24 minutes",
    ),
]