export const Synopsis = {

    GabrielDropout: `For centuries, Heaven has required its young angels to live and study among humans in order to become full-fledged angels. This is no different for top-of-her-class Gabriel White Tenma, who believes it is her mission to be a great angel who will bring happiness to mankind. However, Gabriel grows addicted to video games on Earth and eventually becomes a hikikomori. Proclaiming herself a "Fallen Angel," she is apathetic to everything else—much to the annoyance of Vignette April Tsukinose, a demon whom Gabriel befriended in her angelic early days on Earth.
                     Vignette's attempts to revert Gabriel back to her previous self are in vain, as Gabriel shoots down any attempt to change her precious lifestyle. As they spend their time on Earth, they meet two eccentric personalities: the angel Raphiel Ainsworth Shiraha, Gabriel's classmate with a penchant for sadism, and the demon Satanichia McDowell Kurumizawa, a clumsy self-proclaimed future ruler of the Underworld.
                     Gabriel DropOut follows these four friends' comedic lives as they utterly fail to understand what it truly means to be a demon or an angel.`,

    GakuenHandsome: `High school student Yoshiki Maeda is starting a new year in the all-boys Baraman High School. On the first day, Yoshiki reconnects with his childhood friend, Takuya Saotome, and meets his odd and dramatic homeroom teacher, Teruhiko Saionji. Yoshiki's younger sister, Yuu, is aware of many of these handsome boys and seems to take pleasure in teasing her big brother about them.
                     Yoshiki soon discovers a number of stereotypical romance characters and has no choice but to deal with their outright ludicrous and nonsensical boys' love antics.`,

    GanbareDouki: `Douki-chan is a respectable office worker with one goal: to seduce her coworker Douki-kun. Unfortunately, this proves to be easier said than done, as her plans are constantly thwarted by Kouhai-chan and Senpai-san—her two love rivals who will stop at nothing to gain the affection of their beloved colleague first. Douki-chan will need all the luck she can get to surpass her competition and win Douki-kun's heart.`,

    GhostStories: `Years ago, all of the ghosts in a haunted schoolhouse were banished by a certain student. Now, they're back—and they want revenge...
                   Satsuki and Keiichirou Miyanoshita are two siblings recovering from the tragic loss of their mother. After moving to their mother's hometown, they learn that the local school they have transferred to is an old building—one said to be haunted. Despite initially brushing it off as a silly rumor, the two soon discover that ghosts are indeed real and that they're after them! Gakkou no Kaidan is the creepy tale of the lives of these siblings and their newfound friends as they try to survive the school's ghosts—with a little help from their pet cat along the way.`,

    Girlfriend: `Naoya Mukai is having the time of his life after his childhood friend Saki Saki finally accepts one of his countless confessions. Ensuring that their relationship will stay strong, he spares no effort in showering affection to his now beloved girlfriend.
                 However, one afternoon, another girl named Nagisa Minase suddenly confesses to Naoya following months of preparation. Even though he politely rejects her, Nagisa's irresistible charm and determination continue to attract Naoya. Wanting to fulfill both Saki and Nagisa's desires, Naoya ends up proposing a crazy idea—to date the two of them simultaneously, with both girls fully aware. This unprecedented state of affairs ultimately causes wacky and hilarious situations in whatever they do to keep their unusual relationship going.`,

    GrandBlues: `Anime adaptation of Guraburu!, which is 4-koma manga of Granblue Fantasy.`,

    GJClub: `School clubs usually advertise their activities, but the goings-on of the GJ Club are a mystery. Kyouya "Kyoro" Shinomiya recently joined and became the sole male member of the five-person club.
             Besides Kyoro, there is Mao Amatsuka, the club president who has a tendency to bite Kyoro when she gets mad or bashful; Megumi Amatsuka, Mao's composed younger sister who always makes tea and desserts for the club's members; Shion Sumeragi, a demure chess prodigy; and Kirara Bernstein, a meat lover with a strong feline personality. All four girls have some form of interest in Kyoro.
             With the girls' idiosyncratic and cute personalities, Kyoro's time in GJ-bu will never be a dull one, for better or for worse.`,

    GoblinSlayer: `Goblins are known for their ferocity, cunning, and rapid reproduction, but their reputation as the lowliest of monsters causes their threat to be overlooked. Raiding rural civilizations to kidnap females of other species for breeding, these vile creatures are free to continue their onslaught as adventurers turn a blind eye in favor of more rewarding assignments with larger bounties.
                   To commemorate her first day as a Porcelain-ranked adventurer, the 15-year-old Priestess joins a band of young, enthusiastic rookies to investigate a tribe of goblins responsible for the disappearance of several village women. Unprepared and inexperienced, the group soon faces its inevitable demise from an ambush while exploring a cave. With no one else left standing, the terrified Priestess accepts her fate—until the Goblin Slayer unexpectedly appears to not only rescue her with little effort, but destroy the entire goblin nest.
                   As a holder of the prestigious Silver rank, the Goblin Slayer allows her to accompany him as he assists the Adventurer's Guild in all goblin-related matters. Together with the Priestess, High Elf, Dwarf, and Lizardman, the armored warrior will not rest until every single goblin in the frontier lands has been eradicated for good.`,

    GurrenLagann: `Simon and Kamina were born and raised in a deep, underground village, hidden from the fabled surface. Kamina is a free-spirited loose cannon bent on making a name for himself, while Simon is a timid young boy with no real aspirations. One day while excavating the earth, Simon stumbles upon a mysterious object that turns out to be the ignition key to an ancient artifact of war, which the duo dubs Lagann. Using their new weapon, Simon and Kamina fend off a surprise attack from the surface with the help of Yoko Littner, a hot-blooded redhead wielding a massive gun who wanders the world above.
                   In the aftermath of the battle, the sky is now in plain view, prompting Simon and Kamina to set off on a journey alongside Yoko to explore the wastelands of the surface. Soon, they join the fight against the "Beastmen," humanoid creatures that terrorize the remnants of humanity in powerful robots called "Gunmen." Although they face some challenges and setbacks, the trio bravely fights these new enemies alongside other survivors to reclaim the surface, while slowly unraveling a galaxy-sized mystery.`,


}