import { Anime } from "@/lib/Anime";
import { Synopsis } from "./oSynopsis";

export const o_anime = [
    new Anime(
        "Ojisan and Marshmallow",
        "Ojisan to Marshmallow",
        "https://cdn.myanimelist.net/images/anime/7/78113.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.OjisanMarshmallow,
        [""],
        "TV",
        "Jan 8 2016 to Mar 25 2016",
        "Winter 2016",
        "Creators in Pack",
        "Web manga",
        ["Comedy"],
        ["Adult Cast", "Romantic Subtext", "Workplace"],
        "3 minutes",
    ),
    new Anime(
        "One Punch Man",
        "",
        "https://cdn.myanimelist.net/images/anime/12/76049.jpg",
        12,
        "R - 17+ (violence & profanity)",
        Synopsis.OnePunchMan,
        [""],
        "TV",
        "Oct 5 2015 to Dec 21 2015",
        "Fall 2015",
        "Madhouse",
        "Web manga",
        ["Action", "Comedy"],
        ["Adult Cast", "Parody", "Super Power"],
        "24 minutes",
    ),
    new Anime(
        "One Punch Man Season 2",
        "One Punch Man 2nd Season",
        "https://cdn.myanimelist.net/images/anime/1247/122044.jpg",
        12,
        "R - 17+ (violence & profanity)",
        Synopsis.OnePunchMan2,
        [""],
        "TV",
        "Apr 10 2019 to Jul 3 2019",
        "Spring 2019",
        "J.C. Staff",
        "Web manga",
        ["Action", "Comedy"],
        ["Adult Cast", "Parody", "Super Power"],
        "23 minutes",
    ),
    new Anime(
        "One Room",
        "",
        "https://cdn.myanimelist.net/images/anime/9/83777.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.OneRoom,
        [""],
        "TV",
        "Jan 11 2017 to Mar 29 2017",
        "Winter 2017",
        "Typhoon Graphics",
        "Original",
        ["Slice of Life"],
        [""],
        "4 minutes",
    ),
    new Anime(
        "One Room: Second Season",
        "",
        "https://cdn.myanimelist.net/images/anime/1098/93257.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.OneRoom2,
        [""],
        "TV",
        "Jul 10 2018 to Sep 24 2018",
        "Summer 2018",
        "Zero-G",
        "Original",
        ["Slice of Life"],
        [""],
        "4 minutes",
    ),
    new Anime(
        "One Room: Third Season",
        "",
        "https://cdn.myanimelist.net/images/anime/1553/109101.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.OneRoom3,
        [""],
        "TV",
        "Oct 6 2020 to Dec 22 2020",
        "Fall 2020",
        "Zero-G",
        "Original",
        ["Slice of Life"],
        [""],
        "4 minutes",
    ),
    new Anime(
        "Onimai: I'm Now Your Sister!",
        "Oniichan wa Oshimai!",
        "https://cdn.myanimelist.net/images/anime/1058/131632.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Onimai,
        [""],
        "TV",
        "Jan 5 2023 to Mar 23 2023",
        "Winter 2023",
        "Studio Bind",
        "Manga",
        ["Comedy"],
        ["CGDCT", "Magical Sex Shift", "School"],
        "23 minutes",
    ),
    new Anime(
        "Landlord is in Puberty!",
        "Ooya-san wa Shishunki!",
        "https://cdn.myanimelist.net/images/anime/13/77832.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Landlord,
        [""],
        "TV",
        "Jan 10 2016 to Mar 27 2016",
        "Winter 2016",
        "Seven Arcs Pictures",
        "4-koma manga",
        ["Comedy", "Slice of Life"],
        [""],
        "2 minutes",
    ),
    new Anime(
        "Osamake: Romcom Where The Childhood Friend Won't Lose",
        "Osananajimi ga Zettai ni Makenai Love Comedy",
        "https://cdn.myanimelist.net/images/anime/1111/113327.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Osamake,
        [""],
        "TV",
        "Apr 14 2021 to Jun 30 2021",
        "Spring 2021",
        "Doga Kobo",
        "Light novel",
        ["Comedy", "Romance"],
        ["Harem", "School"],
        "23 minutes",
    ),
    new Anime(
        "Overlord",
        "",
        "https://cdn.myanimelist.net/images/anime/7/88019.jpg",
        13,
        "R - 17+ (violence & profanity)",
        Synopsis.Overlord,
        [""],
        "TV",
        "Jul 7 2015 to Sep 29 2015",
        "Summer 2015",
        "Madhouse",
        "Light novel",
        ["Action", "Adventure", "Fantasy"],
        ["Isekai"],
        "24 minutes",
    ),
    new Anime(
        "Overlord II",
        "",
        "https://cdn.myanimelist.net/images/anime/1212/113415.jpg",
        13,
        "R - 17+ (violence & profanity)",
        Synopsis.Overlord2,
        [""],
        "TV",
        "Jan 9 2018 to Apr 3 2018",
        "Winter 2018",
        "Madhouse",
        "Light novel",
        ["Action", "Adventure", "Fantasy"],
        ["Isekai"],
        "23 minutes",
    ),
    new Anime(
        "Overlord III",
        "",
        "https://cdn.myanimelist.net/images/anime/1511/93473.jpg",
        13,
        "R - 17+ (violence & profanity)",
        Synopsis.Overlord3,
        [""],
        "TV",
        "Jul 10 2018 to Oct 2 2018",
        "Summer 2018",
        "Madhouse",
        "Light novel",
        ["Action", "Adventure", "Fantasy"],
        ["Isekai"],
        "23 minutes",
    ),
    new Anime(
        "Overlord IV",
        "",
        "https://cdn.myanimelist.net/images/anime/1530/120110.jpg",
        13,
        "R - 17+ (violence & profanity)",
        Synopsis.Overlord4,
        [""],
        "TV",
        "Jul 5 2022 to Sep 27 2022",
        "Summer 2022",
        "Madhouse",
        "Light novel",
        ["Action", "Adventure", "Fantasy"],
        ["Isekai"],
        "23 minutes",
    ),
]