export const Synopsis = {
    OjisanMarshmallow: `Habahiro Hige is a simple-minded older man who works an office job and is an enthusiast of Tabekko Marshmallows. His days often consist of being teased by his 24-year-old colleague Iori Wakabayashi, who uses his obsession to her advantage: from eating them in front of his face, to buying out his favorite brand from the convenience store, and even embarrassing him in front of their boss. Although her friends cannot fathom what she sees in him, she just cannot get over his marshmallow-like, fluffy frame. No matter the lengths it takes, Iori will find a way to get his attention.
                        Little does Habahiro know that she is trying to seduce him into a romantic relationship with her. The way to a man's heart is through his stomach, right? At least this is what Iori would honestly like to believe. With a bag in hand, Iori continues to make him chase after her day after day, hoping that he will finally see through her attempts. Will he ever realize that their relationship can become s'more?`,

    OnePunchMan: `The seemingly unimpressive Saitama has a rather unique hobby: being a hero. In order to pursue his childhood dream, Saitama relentlessly trained for three years, losing all of his hair in the process. Now, Saitama is so powerful, he can defeat any enemy with just one punch. However, having no one capable of matching his strength has led Saitama to an unexpected problem—he is no longer able to enjoy the thrill of battling and has become quite bored.
                  One day, Saitama catches the attention of 19-year-old cyborg Genos, who witnesses his power and wishes to become Saitama's disciple. Genos proposes that the two join the Hero Association in order to become certified heroes that will be recognized for their positive contributions to society. Saitama, who is shocked that no one knows who he is, quickly agrees. Meeting new allies and taking on new foes, Saitama embarks on a new journey as a member of the Hero Association to experience the excitement of battle he once felt.`,

    OnePunchMan2: `In the wake of defeating Boros and his mighty army, Saitama has returned to his unremarkable everyday life in Z-City. However, unbeknownst to him, the number of monsters appearing is still continuously on the rise, putting a strain on the Hero Association's resources. Their top executives decide on the bold move of recruiting hoodlums in order to help in their battle. But during the first meeting with these potential newcomers, a mysterious man calling himself Garou makes his appearance. Claiming to be a monster, he starts mercilessly attacking the crowd.
                   The mysterious Garou continues his rampage against the Hero Association, crushing every hero he encounters. He turns out to be the legendary martial artist Silverfang's best former disciple and seems driven by unknown motives. Regardless, this beast of a man seems unstoppable. Intrigued by this puzzling new foe and with an insatiable thirst for money, Saitama decides to seize the opportunity and joins the interesting martial arts competition.
                   As the tournament commences and Garou continues his rampage, a new great menace reveals itself, threatening the entire human world. Could this finally be the earth-shattering catastrophe predicted by the great seer Madame Shibabawa?`,

    OneRoom: `Having just moved into a new apartment building, Yui Hanasaka makes a customary visit to greet her neighbor. When she learns that he is an upperclassman at the university she aspires to attend, she asks for his help to pass her entrance exams. Meanwhile, Natsuki Momohara decides to visit her older brother, who lives alone in an apartment in Tokyo. Elsewhere, aspiring singer Moka Aoshima reunites with her childhood friend, who is a hopeful novelist.
              Three stories, although seemingly unrelated, contain the same essence: strings of fate will bind together those who share the same destiny, and one needs to look no further than a single apartment room.`,

    OneRoom2: `Second season of One Room.`,

    OneRoom3: `Third season of One Room.`,

    Onimai: `Self-professed "home security guard" Mahiro Oyama has not left his home in years, secluding himself in his room playing erotic visual novels. This depraved lifestyle causes his prodigious sister, Mihari, to worry about his well-being. In hopes of solving this problem, she devises a plan to rehabilitate him back to normalcy.
             The first part of Mihari's plan is to concoct a medicine that changes her brother's biological constitution into a bona fide female, much to Mahiro's vehement dismay. Stuck in this predicament, Mahiro has no choice but to live out his life as a cute girl until the effect wears off—if it ever does.`,

    Landlord: `Maeda has just moved into his new apartment to live by himself. While unpacking, a cute middle school student named Chie Satonaka suddenly appears in his room. She introduces herself as his new landlord, which pleasantly surprises him as he has never seen a landlord so young. His excitement is boosted further when the gorgeous Reiko Shirai, who lives directly next to him, also introduces herself as his new neighbor.
               Ooyasan wa Shishunki! follows the everyday lives of Maeda and his newfound acquaintances, where each day presents itself as an opportunity for new events to unfold and new bonds to be forged.`,

    Osamake: `Suehara Maru is childhood best friends with one of Hozumino High School's most popular girls, Kuroha Shida. Cute, outgoing, and affectionate, Kuroha is the perfect older sister type. She has boys constantly begging at her feet to be with her. Yet, when she confesses to Suehara one day, he immediately rejects her; he just can't think of her in that way! Besides, he already has his sights set on his first love—school idol and renowned author Shirokusa Kachi.
              Suehara believes that he has a chance with Kachi after one fateful meeting, but soon, he finds out that Kachi has a boyfriend! With his dreams now shattered, Suehara agonizes over what could have been. That is, until Kuroha approaches him with a proposal: "let's get revenge."`,

    Oshinoko: `In the entertainment world, celebrities often show exaggerated versions of themselves to the public, concealing their true thoughts and struggles beneath elaborate lies. Fans buy into these fabrications, showering their idols with undying love and support, until something breaks the illusion. Sixteen-year-old rising star Ai Hoshino of pop idol group B Komachi has the world captivated; however, when she announces a hiatus due to health concerns, the news causes many to become worried.
               As a huge fan of Ai, gynecologist Gorou Amemiya cheers her on from his countryside medical practice, wishing he could meet her in person one day. His wish comes true when Ai shows up at his hospital—not sick, but pregnant with twins! While the doctor promises Ai to safely deliver her children, he wonders if this encounter with the idol will forever change the nature of his relationship with her.`,

    Overlord: `The final hour of the popular virtual reality game Yggdrasil has come. However, Momonga, a powerful wizard and master of the dark guild Ainz Ooal Gown, decides to spend his last few moments in the game as the servers begin to shut down. To his surprise, despite the clock having struck midnight, Momonga is still fully conscious as his character and, moreover, the non-player characters appear to have developed personalities of their own!
               Confronted with this abnormal situation, Momonga commands his loyal servants to help him investigate and take control of this new world, with the hopes of figuring out what has caused this development and if there may be others in the same predicament.`,

    Overlord2: `Ainz Ooal Gown, the undead sorcerer formerly known as Momonga, has accepted his place in this new world. Though it bears similarities to his beloved virtual reality game Yggdrasil, it still holds many mysteries which he intends to uncover, by utilizing his power as ruler of the Great Tomb of Nazarick. However, ever since the disastrous brainwashing of one of his subordinates, Ainz has become wary of the impending dangers of the Slane Theocracy, as well as the possible existence of other former Yggdrasil players. Meanwhile, Albedo, Demiurge and the rest of Ainz's loyal guardians set out to prepare for the next step in their campaign: Nazarick's first war…
                Overlord II picks up immediately after its prequel, continuing the story of Ainz Ooal Gown, his eclectic army of human-hating guardians, and the many hapless humans affected by the Overlord's arrival.`,

    Overlord3: `Following the horrific assault on the Re-Estize capital city, the Guardians of the Great Tomb of Nazarick return home to their master Ainz Ooal Gown. After months of laying the groundwork, they are finally ready to set their plans of world domination into action.
                As Ainz's war machine gathers strength, the rest of the world keeps moving. The remote Carne Village, which Ainz once saved from certain doom, continues to prosper despite the many threats on its doorstep. And in the northeastern Baharuth Empire, a certain Bloody Emperor sets his sights on the rising power of Nazarick.
                Blood is shed, heroes fall, and nations rise. Can anyone, or anything, challenge the supreme power of Ainz Ooal Gown?`,

    Overlord4: `E-Rantel, the capital city of the newly established Sorcerer Kingdom, suffers from a dire shortage of goods. Once a prosperous city known for its trade, it now faces a crisis due to its caution—or even fear—of its king, Ainz Ooal Gown. To make amends, Ainz sends Albedo to the city as a diplomatic envoy.
                Meanwhile, the cardinals of the Slane Theocracy discuss how to retaliate against Ainz after his attack crippled the Re-Estize Kingdom's army, plotting for the Baharuth Empire to take over the Sorcerer Kingdom. However, when Emperor Jircniv Rune Farlord El Nix arranges a meeting with the Theocracy's messengers at a colosseum, he is confronted by none other than Ainz himself.
                With their secret gathering now out in the open, the emperor and his guests learn that Ainz has challenged the Warrior King, the empire's greatest fighter, to a duel. With Ainz's motivations beyond his comprehension, Jircniv can do nothing but watch as humanity's future changes before his very eyes.`,


}