import { Anime } from "@/lib/Anime";
import { Synopsis } from "./rSynopsis";

export const r_anime = [
    new Anime(
        "Rail Romanesque",
        "",
        "https://cdn.myanimelist.net/images/anime/1858/113920.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.RailRomanesque,
        [""],
        "TV",
        "Oct 3 2020 to Dec 19 2020",
        "Fall 2020",
        "Saetta",
        "Visual novel",
        ["Slice of Life"],
        [""],
        "3 minutes",
    ),
    new Anime(
        "Rascal Does Not Dream of Bunny Girl Senpai",
        "Seishun Buta Yarou wa Bunny Girl Senpai no Yume wo Minai",
        "https://cdn.myanimelist.net/images/anime/1301/93586.jpg",
        13,
        "PG-13 - Teens 13 or older",
        Synopsis.BunnyGirlSenpai,
        [""],
        "TV",
        "Oct 4 2018 to Dec 27 2018",
        "Fall 2018",
        "CloverWorks",
        "Light novel",
        ["Drama", "Romance", "Supernatural"],
        ["School"],
        "24 minutes",
    ),
    new Anime(
        "Recorder and Randsell",
        "Recorder to Randoseru Do♪",
        "https://cdn.myanimelist.net/images/anime/13/33003.jpg",
        13,
        "PG-13 - Teens 13 or older",
        Synopsis.RecorderAndRandsell,
        [""],
        "TV",
        "Jan 6 2012 to Mar 28 2012",
        "Winter 2022",
        "Seven",
        "4-koma manga",
        ["Comedy", "Slice of Life"],
        ["School"],
        "3 minutes",
    ),
    new Anime(
        "Recorder and Randsell Re",
        "Recorder to Randoseru Re♪",
        "https://cdn.myanimelist.net/images/anime/11/38901.jpg",
        13,
        "PG-13 - Teens 13 or older",
        Synopsis.RecorderAndRandsell2,
        [""],
        "TV",
        "Apr 4 2012 to Jun 27 2012",
        "Spring 2012",
        "Seven",
        "4-koma manga",
        ["Comedy", "Slice of Life"],
        ["School"],
        "3 minutes",
    ),
    new Anime(
        "Recorder and Randsell Mi",
        "Recorder to Randoseru Mi☆",
        "https://cdn.myanimelist.net/images/anime/6/50651.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.RecorderAndRandsell3,
        [""],
        "TV",
        "Jul 8 2013 to Sep 23 2013",
        "Summer 2013",
        "Seven",
        "4-koma manga",
        ["Comedy", "Slice of Life"],
        ["School"],
        "3 minutes",
    ),
    new Anime(
        "Re:ZERO -Starting Life in Another World-",
        "Re:Zero kara Hajimeru Isekai Seikatsu",
        "https://cdn.myanimelist.net/images/anime/1522/128039.jpg",
        25,
        "R - 17+ (violence & profanity)",
        Synopsis.ReZero,
        [""],
        "TV",
        "Apr 4 2016 to Sep 19 2016",
        "Spring 2016",
        "White Fox",
        "Light novel",
        ["Drama", "Fantasy", "Suspense"],
        ["Isekai", "Psychological", "Time Travel"],
        "26 minutes",
    ),
    new Anime(
        "Remake Our Life!",
        "Bokutachi no Remake",
        "https://cdn.myanimelist.net/images/anime/1871/118309.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.RemakeOurLife,
        [""],
        "TV",
        "Jul 3 2021 to Sep 25 2021",
        "Summer 2021",
        "feel",
        "Light novel",
        ["Drama", "Romance"],
        ["Adult Cast", "Time Travel"],
        "25 minutes",
    ),
    new Anime(
        "Rent-a-Girlfriend",
        "Kanojo, Okarishimasu",
        "https://cdn.myanimelist.net/images/anime/1902/128382.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.RentAGirlfriend,
        [""],
        "TV",
        "Jul 11 2020 to Sep 26 2020",
        "Summer 2020",
        "TMS Entertainment",
        "Manga",
        ["Comedy", "Romance"],
        ["Adult Cast", "Harem"],
        "24 minutes",
    ),
    new Anime(
        "Rent-a-Girlfriend Season 2",
        "Kanojo, Okarishimasu 2nd Season",
        "https://cdn.myanimelist.net/images/anime/1070/124592.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.RentAGirlfriend2,
        [""],
        "TV",
        "Jul 2 2022 to Sep 17 2022",
        "Summer 2022",
        "TMS Entertainment",
        "Manga",
        ["Comedy", "Romance"],
        ["Adult Cast", "Harem"],
        "24 minutes",
    ),
    new Anime(
        "Room Camp",
        "Heya Camp△",
        "https://cdn.myanimelist.net/images/anime/1228/104364.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.RoomCamp,
        [""],
        "TV",
        "Jan 6 2020 to Mar 23 2020",
        "Winter 2020",
        "C-Station",
        "Manga",
        ["Slice of Life"],
        ["CGDCT", "Iyashikei"],
        "3 minutes",
    ),
]