export const Synopsis = {
    RailRomanesque: `The year is 1989. After the nation of Hinomoto was destabilized during the past World War, the rise of new technologies has enabled its revitalization. Modern engineering has given birth to aircraft, gasoline engines, and geomagnetic technology—revolutionizing transportation. Railroads have been rendered nearly obsolete and replaced by more efficient modes of transit.
                     However, a group of lively "Raillords" aims to renew the railroads' former glory. The Raillords, personified as energetic and spirited girls, act as humanoid control modules for their assigned railways. They meet in Ohitoyo City for the Raillord Summit, headed by Suzushiro, a Raillord from Manoka Railways. Together, the group capitalizes on its teamwork to get the railroads back on track, ushering in a "new railroad age."`,

    BunnyGirlSenpai: `The rare and inexplicable Puberty Syndrome is thought of as a myth. It is a rare disease which only affects teenagers, and its symptoms are so supernatural that hardly anyone recognizes it as a legitimate occurrence. However, high school student Sakuta Azusagawa knows from personal experience that it is very much real, and happens to be quite prevalent in his school.
                      Mai Sakurajima is a third-year high school student who gained fame in her youth as a child actress, but recently halted her promising career for reasons unknown to the public. With an air of unapproachability, she is well known throughout the school, but none dare interact with her—that is until Sakuta sees her wandering the library in a bunny girl costume. Despite the getup, no one seems to notice her, and after confronting her, he realizes that she is another victim of Puberty Syndrome. As Sakuta tries to help Mai through her predicament, his actions bring him into contact with more girls afflicted with the elusive disease.`,

    RecorderAndRandsell: `Atsushi Miyagawa is an 11-year-old boy with the appearance of a fully-grown man. His 17-year-old sister, Atsumi, has the stature of a child! From Atsushi being arrested numerous times as a suspected predator to Atsumi constantly grabbed like a small child more times than she can count, many things go wrong for this curious sibling duo. Atsumi's classmate is even in love with Atsushi, oblivious to his true age! Despite all this, indeed, there is not a single dull moment in the Miyagawa household.`,

    RecorderAndRandsell2: `Second season of Recorder to Randoseru.`,

    RecorderAndRandsell3: `Third season of Recorder to Randoseru.`,

    ReZero: `When Subaru Natsuki leaves the convenience store, the last thing he expects is to be wrenched from his everyday life and dropped into a fantasy world. Things are not looking good for the bewildered teenager; however, not long after his arrival, he is attacked by some thugs. Armed with only a bag of groceries and a now useless cell phone, he is quickly beaten to a pulp. Fortunately, a mysterious beauty named Satella, in hot pursuit after the one who stole her insignia, happens upon Subaru and saves him. In order to thank the honest and kindhearted girl, Subaru offers to help in her search, and later that night, he even finds the whereabouts of that which she seeks. But unbeknownst to them, a much darker force stalks the pair from the shadows, and just minutes after locating the insignia, Subaru and Satella are brutally murdered.
             However, Subaru immediately reawakens to a familiar scene—confronted by the same group of thugs, meeting Satella all over again—the enigma deepens as history inexplicably repeats itself.`,

    ReincarnatedSword: `A nameless sword wakes up to discover he has been reincarnated from his former life as a human. With his power of telekinesis, he moves around this new world, acquiring several skills and abilities. When the sword comes upon a forest filled with monsters, he meets a young girl fleeing from a beast. Grabbing the sword, the girl easily defeats the monster. After introducing herself as Fran, she names the sword "Shishou" and officially becomes his wielder.
                        The two set out to become adventurers, but unfortunately for Fran, she is a member of the Black Cat Tribe—a Beastkin group with a bad reputation. No member of this tribe has ever evolved into a mightier beast, but Fran plans to be the first and achieve her parents' dream. As Shishou promises to remain her sword until she attains her goal, they form an unstoppable partnership of impressive strength.`,

    RemakeOurLife: `Life is not going well for 28-year-old Kyouya Hashiba. Having left his office job to pursue a career in the video game industry, his internship at a popular game studio abruptly ends, leaving him unemployed and forcing him to move back in with his parents. Additionally, his jealousy toward the success of the "Platinum Generation"—a group of similarly-aged creators—has caused him to regret his decision to attend a traditional university instead of an arts college. Even though he believes there are no second chances in life, Kyouya is suddenly given one when he wakes up one day and finds himself 10 years in the past.
                    Instead of choosing business school like he originally had, Kyouya decides to pursue his passions and attends the Oonaka University of Art. There, he meets classmate Eiko Kawasegawa, the woman who had hired him as an intern in the present, alongside his new housemates and future Platinum Generation members: underachieving artist Aki Shino, aspiring singer and actress Nanako Kogure, and naturally-gifted writer Tsurayuki Rokuonji.
                    With each project they complete together, Kyouya and his friends venture closer to discovering their true potential as creators and remaking their lives into the ideal versions they desire.`,

    RentAGirlfriend: `Kazuya Kinoshita is a 20-year-old college student who has a wonderful girlfriend: the bright and sunny Mami Nanami. But suddenly, he doesn't. Without warning, Mami breaks up with him, leaving him utterly heartbroken and lonely. Seeking to soothe the pain, he hires a rental girlfriend through an online app. His partner is Chizuru Mizuhara, who through her unparalleled beauty and cute demeanor, manages to gain Kazuya's affection.
                      But after reading similar experiences other customers had had with Chizuru, Kazuya believes her warm smile and caring personality were all just an act to toy with his heart, and he rates her poorly. Aggravated, Chizuru lambastes him for his shameless hypocrisy, revealing her true pert and hot-tempered self. This one-sided exchange is cut short, however, when Kazuya finds out that his grandmother has collapsed.
                      They dash toward the hospital and find Kazuya's grandmother already in good condition. Baffled by Chizuru's presence, she asks who this girl might be. On impulse, Kazuya promptly declares that they are lovers, forcing Chizuru to play the part. But with Kazuya still hung up on his previous relationship with Mami, how long can this difficult client and reluctant rental girlfriend keep up their act?`,

    RentAGirlfriend2: `A year after they met, Kazuya Kinoshita and Chizuru Mizuhara still regularly see each other through the rental girlfriend app. However, Chizuru confesses that she is ready to quit her job to pursue her true passion—acting. Despite wishing to maintain the relationship they have, Kazuya decides to support her dream.
                       When Kazuya goes to watch Chizuru's anticipated first play, he is amazed by her talent and ability to captivate the audience. At the same time, he is saddened at the thought that she will undoubtedly be scouted by the famous director in attendance.
                       However, after the show, Chizuru explains that the director recruited another actress, lamenting her lack of talent. Frustrated on her behalf, Kazuya resolves to rent her every week to help her financially. But as Kazuya's ex-girlfriend Mami Nanami lingers around for unknown reasons, hesitance muddles his true feelings, and fulfilling his promise to Chizuru becomes uncertain.`,

    RoomCamp: `During an Outdoor Activities Club meeting, Nadeshiko Kagamihara, Aoi Inuyama, and Chiaki Oogaki debate what it means to be a real Yamanashi native. Somewhere along the line, Chiaki brings up the Yamanashi Kids' Stamp Rally, which Nadeshiko has never heard of. The rally encourages one to visit famous places in the prefecture and collect stamps; those who complete the rally will win a year's worth of Minobu steamed buns. Enticed by the humongous food prize, Nadeshiko is set on participating.
               Follow the Outdoor Activities Club as they travel around the Yamanashi prefecture to collect stamps and explore what the region has to offer!`,


}