import { Anime } from "@/lib/Anime";
import { Synopsis } from "./cSynopsis";

export const c_anime = [
    new Anime(
        "Cautious Hero: The Hero is Overpowered but Overly Cautious",
        "Shinchou Yuusha: Kono Yuusha ga Ore Tueee Kuse ni Shinchou Sugiru",
        "https://cdn.myanimelist.net/images/anime/1715/103419.jpg",
        12,
        "R - 17+ (violence & profanity)",
        Synopsis.CautiousHero,
        [""],
        "TV",
        "Oct 2 2019 to Dec 27 2019",
        "Fall 2019",
        "White Fox",
        "Light novel",
        ["Action", "Adventure", "Comedy", "Fantasy"],
        ["Isekai", "Parody"],
        "23 minutes",
    ),
    new Anime(
        "Case Closed: The Culprit Hanzawa", 
        "Meitantei Konan Hannin no Hanzawa-san", 
        "",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.CaseClosedHanzawa,
        [""],
        "TV",
        "October 4 2022 to December 20 2022",
        "Fall 2022",
        "TMS Entertainment",
        "Manga",
        ["Comedy"],
        ["Gag Humor", "Parody"],
        "11 minutes",
    ),
    new Anime(
        "Cells at Work!",
        "Hataraku Saibou",
        "https://cdn.myanimelist.net/images/anime/1141/117446.jpg",
        13,
        "PG-13 - Teens 13 or older",
        Synopsis.CellsAtWork,
        [""],
        "TV",
        "Jul 8 2018 to Sep 30 2018",
        "Summer 2018",
        "David Production",
        "Manga",
        ["Comedy"],
        ["Anthropomorphic", "Educational", "Medical"],
        "23 minutes",
    ),
    new Anime(
        "Cells at Work!!",
        "Hataraku Saibou!!",
        "https://cdn.myanimelist.net/images/anime/1726/114552.jpg",
        8,
        "PG-13 - Teens 13 or older",
        Synopsis.CellsAtWork2,
        [""],
        "TV",
        "Jan 9 2021 to Feb 27 2021",
        "Winter 2021",
        "David Production",
        "Manga",
        ["Comedy"],
        ["Anthropomorphic", "Educational", "Medical"],
        "23 minutes",
    ),
    new Anime(
        "Cells at Work! CODE BLACK",
        "Hataraku Saibou Black",
        "https://cdn.myanimelist.net/images/anime/1837/110799.jpg",
        13,
        "PG-13 - Teens 13 or older",
        Synopsis.CellsAtWorkBlack,
        [""],
        "TV",
        "Jan 10 2021 to Mar 19 2021",
        "Winter 2021",
        "LIDENFILMS",
        "Manga",
        ["Action", "Drama"],
        ["Anthropomorphic", "Educational", "Medical"],
        "23 minutes",
    ),
    new Anime(
        "Charlotte",
        "",
        "https://cdn.myanimelist.net/images/anime/12/74683.jpg",
        13,
        "PG-13 - Teens 13 or older",
        Synopsis.Charlotte,
        [""],
        "TV",
        "Jul 5 2015 to Sep 27 2015",
        "Summer 2015",
        "P.A. Works",
        "Original",
        ["Drama"],
        ["School", "Super Power"],
        "24 minutes",
    ),
    new Anime(
        "Chitose Get You!!",
        "",
        "https://cdn.myanimelist.net/images/anime/10/50537.jpg",
        26,
        "PG-13 - Teens 13 or older",
        Synopsis.Chitose,
        [""],
        "TV",
        "Jul 2 2016 to Dec 24 2012",
        "Summer 2012",
        "SILVER LINK",
        "4-koma manga",
        ["Comedy", "Romance"],
        ["School"],
        "3 minutes",
    ),
    new Anime(
        "Chronicles of the Going Home Club",
        "Kitaku-bu Katsudou Kiroku",
        "https://cdn.myanimelist.net/images/anime/9/59639.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Chronicles,
        [""],
        "TV",
        "Jul 5 2013 to Oct 11 2013",
        "Summer 2013",
        "Nomad",
        "Web manga",
        ["Comedy"],
        ["CGDCT", "School"],
        "23 minutes",
    ),
    new Anime(
        "Classroom of the Elite",
        "Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e",
        "https://cdn.myanimelist.net/images/anime/5/86830.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Classroom,
        [""],
        "TV",
        "Jul 12 2017 to Sep 27 2017",
        "Summer 2017",
        "Lerche",
        "Light novel",
        ["Drama", "Suspense"],
        ["Psychological", "School"],
        "24 minutes",
    ),
    new Anime(
        "Classroom of the Elite II",
        "Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e 2nd Season",
        "https://cdn.myanimelist.net/images/anime/1010/124180.jpg",
        13,
        "PG-13 - Teens 13 or older",
        Synopsis.Classroom2,
        [""],
        "TV",
        "Jul 4 2022 to Sep 26 2022",
        "Summer 2022",
        "Lerche",
        "Light novel",
        ["Drama", "Suspense"],
        ["Psychological", "School"],
        "23 minutes",
    ),
    new Anime(
        "Comic Girls",
        "",
        "https://cdn.myanimelist.net/images/anime/1444/140760.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Comic,
        [""],
        "TV",
        "Apr 5 2018 to Jun 21 2018",
        "Spring 2018",
        "Nexus",
        "4-koma manga",
        ["Slice of Life"],
        ["CGDCT", "Otaku Culture"],
        "23 minutes",
    ),
    new Anime(
        "Corpse Party: Tortured Souls",
                  "Corpse Party: Tortured Souls - Bougyakusareta Tamashii no Jukyou",
        "https://cdn.myanimelist.net/images/anime/10/78811.jpg",
        4,
        "R - 17+ (violence & profanity)",
        Synopsis.Corpse,
        [""],
        "OVA",
        "Jul 24 2013",
        "1 day",
        "asread",
        "Visual novel",
        ["Horror", "Mystery", "Supernatural"],
        ["Gore"],
        "29 minutes",
    ),
    new Anime(
        "Crossing Time",
        "Fumikiri Jikan",
        "https://cdn.myanimelist.net/images/anime/1598/91857.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Crossing,
        [""],
        "TV",
        "Apr 10 2018 to Jun 26 2018",
        "Spring 2018",
        "EKACHI EPILKA",
        "Manga",
        ["Comedy", "Slice of Life"],
        [""],
        "3 minutes",
    ),
]