export const Synopsis = {
    CautiousHero: `There is a popular saying: "you can never be too careful." It is very important to prepare for every situation you may face, even if it seems like an unnecessary waste of time. Also, in games like RPGs, it is good to exceed the level of your enemies to achieve total victory.
                   These words describe Seiya Ryuuguuin a little too perfectly. After being summoned by the goddess Ristarte to save the world of Gaeabrande from destruction, the hero prepares himself for his noble journey. While this might be normal, he spends a very long time training himself, despite having overpowered stats. He fights weak enemies using his strongest skills and buys excessive amounts of supplies and potions—all to stay safe.
                   While his attitude may be a bit annoying, it might just be the saving grace of Gaeabrande, especially considering that it is a world where the forces of evil dominate each and every expectation.`,

    CaseClosedHanzawa: `A silhouetted suspect moves to the crime-infested town of Beika with murder in mind, in this spinoff spoof of "Detective Conan."`,

    CellsAtWork: `Inside the human body, roughly 37.2 trillion cells work energetically 24 hours a day and 365 days a year. Fresh out of training, the cheerful and somewhat airheaded Sekkekkyuu AE3803 is ready to take on the ever-so-important task of transporting oxygen. As usual, Hakkekkyuu U-1146 is hard at work patrolling and eliminating foreign bacteria seeking to make the body their new lair. Elsewhere, little platelets are lining up for a new construction project.
                  Dealing with wounds and allergies, getting lost on the way to the lungs, and bickering with similar cell types, the daily lives of cells are always hectic as they work together to keep the body healthy!`,

    CellsAtWork2: `The cells of the human body never rest for too long; there's always something new to do and learn every day. At least, that's what Hakkekkyuu U-1146 feels as he rushes to and fro, searching for any pathogens that could cause harm to the body. Despite his dangerous line of work, it's all worth it to protect the happy smiles of Sekkekkyuu AE3803, the platelet crew, his fellow neutrophils, and the other cells he meets along the way.
                   In his latest pathogen-hunting adventures, Hakkekkyuu U-1146 discovers how important cells can sometimes make mistakes, and that not all bacteria are actually bad. Everybody has their bad days, but everything eventually works out when their comrades have their backs. In the end, it's just another normal day for these hardworking cells!`,

    CellsAtWorkBlack: `Due to poor lifestyle choices, a certain human's body is in constant turmoil. With germs, bacteria, and foreign substances abound, the jobs of various cells become increasingly difficult and dangerous. As some of the unfortunate ones who matured in this chaotic environment, Sekkekkyuu AA2153 and Hakkekkyuu U-1196 strive to fulfill their duties—even if it means seeing many of their fellow cells lose their lives in duty.
                       Set in an environment vastly different from its parent story, Hataraku Saibou Black portrays the cells' struggles as they try to maintain the body's health. However, the human's condition continues to deteriorate, and whether or not these efforts will amount to something concrete depends on the cells!`,

    Charlotte: `If not for his ability to take over people's mind and body, Yuu Otosaka would be an ordinary high school student. Though it only lasts for five seconds at a time, Yuu's mysterious power allowed him to cheat his way to the top of his class and enter a prestigious high school, where he continues his dishonest acts.
                His shenanigans are eventually stopped by Nao Tomori—the headstrong student council president from Hoshinoumi Academy—who sees through his deceit. Through coercion, Nao convinces Yuu to transfer to Hoshinoumi and join the student council. Hoshinoumi Academy is secretly an institution created for adolescents who possess supernatural abilities—with the student council serving as a means of locating those who abuse their powers.
                With Yuu begrudgingly assisting in council affairs, the group sets out to find and protect new ability users from harm. However, as they further investigate the abilities, their findings entangle them in far more complicated matters than they could ever imagine.`,

    Chitose: `Chitose is an 11-year-old girl who is madly in love with an older guy named Hiroshi. He works at the town hall right next to the school and Chitose spends every day relentlessly pursuing him. Can Chitose ever convince Hiroshi to go out with her?`,

    Chronicles: `When a friend asks Natsuki what high school club she's going to join, she cheerfully responds "the go-home club" (meaning, she's not going to join any of them). However, she soon realizes that this club actually exists at her high school, and she's just expressed interest in joining it! Before she knows it, she ends up as one of the two new members of "the go-home club," which is a small group of eccentric school girls. One of the girls likes fighting bears, while another is ridiculously rich. But what exactly constitutes the activities of "the go-home club"?`,

    Classroom: `On the surface, Koudo Ikusei Senior High School is a utopia. The students enjoy an unparalleled amount of freedom, and it is ranked highly in Japan. However, the reality is less than ideal. Four classes, A through D, are ranked in order of merit, and only the top classes receive favorable treatment.
                Kiyotaka Ayanokouji is a student of Class D, where the school dumps its worst. There he meets the unsociable Suzune Horikita, who believes she was placed in Class D by mistake and desires to climb all the way to Class A, and the seemingly amicable class idol Kikyou Kushida, whose aim is to make as many friends as possible.
                While class membership is permanent, class rankings are not; students in lower ranked classes can rise in rankings if they score better than those in the top ones. Additionally, in Class D, there are no bars on what methods can be used to get ahead. In this cutthroat school, can they prevail against the odds and reach the top?`,

    Classroom2: `Life back on the cruise following the Island Special Examination is anything but smooth sailing. Almost immediately after their return, the first-year students of Tokyo Metropolitan Advanced Nurturing High School face yet another special exam, with both class and individual points on the line.
                 In addition to the complicated ruleset, more issues arise in the form of Kakeru Ryuuen and Kei Karuizawa. Angered by the previous test's outcome, Ryuuen is dead set on outdoing every class in the new challenge using any means necessary. Meanwhile, Karuizawa, a crucial pillar of Class D, is close to crumbling under the pressure of her past.
                 The stage is now set for Kiyotaka Ayanokouji to once again—using the full extent of his planning, foresight, and ruthless manipulation—steer Class D to victory as dangerously close enemy forces try to bring it down.`,

    Comic: `Kaoruko "Chaos" Moeta is a young manga artist who is down on her luck. She wants to draw manga about high school girls, but her storyboards are bland, her art uninspired, and her premises weak. Her concerned, exasperated editor comes up with an idea: push Chaos to be more social. So, by her recommendation, Chaos moves into a dormitory for female manga artists. She soon meets the other residents: Tsubasa Katsuki, a shounen manga artist; Ruki Irokawa, who draws erotic manga popular with women; and Koyume Koizuka, a shoujo artist who, like Chaos, has yet to be serialized. Quickly striking up a friendship with these girls, Chaos finds new inspiration for her manga and continues to grow her creativity.
            Comic Girls is a showcase of the daily lives of these manga artists. Will Chaos finally be able to make her debut and become serialized? None of the girls know, but they will all do their best to help each other become the best artists they can be.`,

    Corpse: `Nine students gather in their high school at night to bid farewell to a friend. As is customary among many high school students, they perform a sort of ritual for them to remain friends forever, using small paper charms shaped like dolls.
             However, the students do not realize that these charms are connected to Heavenly Host Academy—an elementary school that was destroyed years ago after a series of gruesome murders took place, a school that rests under the foundation of their very own Kisaragi Academy. Now, trapped in an alternate dimension with vengeful ghosts of the past, the students must work together to escape—or join the spirits of the damned forever.
             A feast for mystery fanatics, gore-hounds, and horror fans alike, Corpse Party: Tortured Souls - Bougyakusareta Tamashii no Jukyou shows a sobering look at redemption, sacrifice, and how the past is always right behind, sometimes a little too close for comfort.`,

    Crossing: `Every day, all kinds of different people stop at railroad crossings on their way to work or school, resulting in all sorts of different conversations. Friends, enemies, acquaintances, and complete strangers—there's always a new encounter to be had.
               Fumikiri Jikan documents the discussions that take place at these locations. Whether these are funny or depressing, expected or completely unexpected, they certainly have the potential to be quite interesting.`,
}