import { Anime } from "@/lib/class/Anime";
import { Synopsis } from "./mSynopsis";

export const m_anime = [
    new Anime(
        "Maerchen Maedchen",
        "Märchen Mädchen",
        "https://cdn.myanimelist.net/images/anime/8/90088.jpg",
        10,
        "PG-13 - Teens 13 or older",
        Synopsis.MaerchenMaedchen,
        [""],
        "TV",
        "Jan 11 2018 to Mar 29 2018",
        "Winter 2018",
        "Hoods Entertainment",
        "Light novel",
        ["Fantasy"],
        ["Isekai", "School"],
        "23 minutes",
    ),
    new Anime(
        "Magical Somera-chan",
        "Fushigi na Somera-chan",
        "https://cdn.myanimelist.net/images/anime/7/76737.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.MagicalSomera,
        [""],
        "TV",
        "Oct 7 2015 to Dec 23 2015",
        "Fall 2015",
        "Seven",
        "4-koma manga",
        ["Comedy", "Slice of Life"],
        ["Gag Humor"],
        "3 minutes",
    ),
    new Anime(
        "Magimoji Rurumo",
        "",
        "https://cdn.myanimelist.net/images/anime/8/64443.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Magimoji,
        [""],
        "TV",
        "Jul 9 2014 to Sep 24 2014",
        "Summer 2014",
        "J.C. Staff",
        "Manga",
        ["Comedy", "Fantasy", "Ecchi"],
        ["School"],
        "23 minutes",
    ),
    new Anime(
        "Mahou Shoujo Nante Mouiidesukara",
        "Mahou Shoujo Nante Mou Ii desu kara.",
        "https://cdn.myanimelist.net/images/anime/9/77841.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.MahouShoujoNante,
        [""],
        "TV",
        "Jan 12 2016 to Mar 29 2016",
        "Winter 2016",
        "PINE JAM",
        "Web manga",
        ["Comedy"],
        ["Mahou Shoujo"],
        "4 minutes",
    ),
    new Anime(
        "Mahou Shoujo Nante Mouiidesukara Second Season",
        "Mahou Shoujo Nante Mou Ii desu kara. Second Season",
        "https://cdn.myanimelist.net/images/anime/5/82253.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.MahouShoujoNante2,
        [""],
        "TV",
        "Oct 5 2016 to Dec 21 2016",
        "Fall 2016",
        "PINE JAM",
        "Web manga",
        ["Comedy"],
        ["Mahou Shoujo"],
        "4 minutes",
    ),
    new Anime(
        "Masamune-kun's Revenge",
        "Masamune-kun no Revenge",
        "https://cdn.myanimelist.net/images/anime/12/83709.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Masamune,
        [""],
        "TV",
        "Jan 5 2017 to Mar 23 2017",
        "Winter 2017",
        "SILVER LINK",
        "Manga",
        ["Comedy", "Romance"],
        ["Harem", "School"],
        "24 minutes",
    ),
    new Anime(
        "Military!",
        "",
        "https://cdn.myanimelist.net/images/anime/4/68837.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Military,
        [""],
        "TV",
        "Jan 7 2015 to Mar 25 2015",
        "Winter 2015",
        "Creators in Pack",
        "4-koma manga",
        ["Comedy", "Slice of Life", "Ecchi"],
        ["Military"],
        "3 minutes",
    ),
    new Anime(
        "Miss Bernard said.",
        "Bernard-jou Iwaku.",
        "https://cdn.myanimelist.net/images/anime/11/81589.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.MissBernard,
        [""],
        "TV",
        "Oct 7 2016 to Dec 23 2016",
        "Fall 2016",
        "Creators in Pack",
        "Manga",
        ["Comedy"],
        ["School"],
        "3 minutes",
    ),
    new Anime(
        "Miss Kobayashi's Dragon Maid",
        "Kobayashi-san Chi no Maid Dragon",
        "https://cdn.myanimelist.net/images/anime/5/85434.jpg",
        13,
        "PG-13 - Teens 13 or older",
        Synopsis.Kobayashi,
        [""],
        "TV",
        "Jan 12 2017 to Apr 6 2017",
        "Winter 2017",
        "Kyoto Animation",
        "Manga",
        ["Fantasy", "Slice of Life"],
        [""],
        "24 minutes",
    ),
    new Anime(
        "Miss Kobayashi's Dragon Maid: Valentine's, and Then Hot Springs! (Please Don't Get Your Hopes Up)",
        "Kobayashi-san Chi no Maid Dragon: Valentine, Soshite Onsen! - Amari Kitai Shinaide Kudasai",
        "https://cdn.myanimelist.net/images/anime/5/88486.jpg",
        1,
        "PG-13 - Teens 13 or older",
        Synopsis.KobayashiSpecial,
        [""],
        "Special",
        "Sep 20 2017",
        "Fall 2017",
        "Kyoto Animation",
        "Manga",
        ["Fantasy", "Slice of Life"],
        [""],
        "23 minutes",
    ),
    new Anime(
        "Miss Kobayashi's Dragon Maid S",
        "Kobayashi-san Chi no Maid Dragon S",
        "https://cdn.myanimelist.net/images/anime/1252/115539.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Kobayashi2,
        [""],
        "TV",
        "Jul 8 2021 to Sep 23 2021",
        "Summer 2021",
        "Kyoto Animation",
        "Manga",
        ["Fantasy", "Slice of Life"],
        [""],
        "23 minutes",
    ),
    new Anime(
        "Miss Kuroitsu from the Monster Development Department",
        "Kaijin Kaihatsu-bu no Kuroitsu-san",
        "https://cdn.myanimelist.net/images/anime/1975/121513.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.MissKuroitsu,
        [""],
        "TV",
        "Jan 9 2022 to Apr 3 2022",
        "Winter 2022",
        "Quad",
        "Web manga",
        ["Comedy", "Fantasy"],
        ["Workplace"],
        "23 minutes",
    ),
    new Anime(
        "Mob Psycho 100",
        "",
        "https://cdn.myanimelist.net/images/anime/8/80356.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.MobPsycho,
        [""],
        "TV",
        "Jul 11 2016 to Sep 27 2016",
        "Summer 2016",
        "Bones",
        "Web manga",
        ["Action", "Comedy", "Supernatural"],
        ["Super Power"],
        "24 minutes",
    ),
    new Anime(
        "Morita-san wa Mukuchi",
        "",
        "https://cdn.myanimelist.net/images/anime/13/30166.jpg",
        13,
        "PG-13 - Teens 13 or older",
        Synopsis.Morita,
        [""],
        "TV",
        "Jul 6 2011 to Sep 28 2011",
        "Summer 2011",
        "Seven",
        "4-koma manga",
        ["Comedy", "Slice of Life"],
        ["School"],
        "3 minutes",
    ),
    new Anime(
        "Morita-san wa Mukuchi. 2",
        "",
        "https://cdn.myanimelist.net/images/anime/7/32933.jpg",
        13,
        "PG-13 - Teens 13 or older",
        Synopsis.Morita2,
        [""],
        "TV",
        "Oct 5 2011 to Dec 28 2011",
        "Fall 2011",
        "Seven",
        "4-koma manga",
        ["Comedy", "Slice of Life"],
        ["School"],
        "3 minutes",
    ),
    new Anime(
        "Musasi-no",
        "Musashino!",
        "https://cdn.myanimelist.net/images/anime/1541/126462.jpg",
        12,
        "PG - Children",
        Synopsis.Musasino,
        [""],
        "TV",
        "Jul 2 2022 to Sep 17 2022",
        "Summer 2022",
        "A-Real",
        "Original",
        ["Comedy"],
        ["School"],
        "3 minutes",
    ),
    new Anime(
        "Mushoku Tensei: Jobless Reincarnation",
        "Mushoku Tensei: Isekai Ittara Honki Dasu",
        "https://cdn.myanimelist.net/images/anime/1530/117776.jpg",
        11,
        "R - 17+ (violence & profanity)",
        Synopsis.MushokuTensei,
        [""],
        "TV",
        "Jan 11 2021 to Mar 22 2021",
        "Winter 2021",
        "Studio Bind",
        "Light novel",
        ["Adventure", "Drama", "Fantasy", "Ecchi"],
        ["Isekai", "Reincarnation"],
        "23 minutes",
    ),
    new Anime(
        "Mushoku Tensei: Jobless Reincarnation Part 2",
        "Mushoku Tensei: Isekai Ittara Honki Dasu Part 2",
        "https://cdn.myanimelist.net/images/anime/1028/117777.jpg",
        12,
        "R - 17+ (violence & profanity)",
        Synopsis.MushokuTenseiPart2,
        [""],
        "TV",
        "Oct 4 2021 to Dec 20 2021",
        "Fall 2021",
        "Studio Bind",
        "Light novel",
        ["Adventure", "Drama", "Fantasy", "Ecchi"],
        ["Isekai", "Reincarnation"],
        "23 minutes",
    ),
    new Anime(
        'Mushoku Tensei: Jobless Reincarnation 2nd Season - Episode 0 "Guardian Fitz"',
        "Mushoku Tensei II: Isekai Ittara Honki Dasu - Shugo Jutsushi Fitz",
        "https://cdn.myanimelist.net/images/anime/1627/136934.jpg",
        1,
        "R - 17+ (violence & profanity)",
        Synopsis.MushokuTensei2Special,
        [],
        "TV Special",
        "Jul 3 2023",
        "Summer 2023",
        "Studio Bind",
        "Light novel",
        ["Adventure", "Drama", "Fantasy", "Ecchi"],
        ["Isekai", "Reincarnation"],
        "24 minutes"
    ),
    new Anime(
        "Mushoku Tensei: Jobless Reincarnation Season 2",
        "Mushoku Tensei II: Isekai Ittara Honki Dasu",
        "https://cdn.myanimelist.net/images/anime/1898/138005.jpg",
        12,
        "R - 17+ (violence & profanity)",
        Synopsis.MushokuTensei2,
        [],
        "TV",
        "Jul 10 2023 to Sep 25 2023",
        "Summer 2023",
        "Studio Bind",
        "Light novel",
        ["Adventure", "Drama", "Fantasy", "Ecchi"],
        ["Isekai", "Reincarnation"],
        "23 minutes"
    ),
    new Anime(
        "Mushoku Tensei: Jobless Reincarnation Season 2 Part 2",
        "Mushoku Tensei II: Isekai Ittara Honki Dasu Part 2",
        "https://cdn.myanimelist.net/images/anime/1876/141251.jpg",
        12,
        "R - 17+ (violence & profanity)",
        Synopsis.MushokuTensei2Part2,
        [],
        "TV",
        "Apr 8 2024 to Jul 1 2024",
        "Spring 2024",
        "Studio Bind",
        "Light novel",
        ["Adventure", "Drama", "Fantasy", "Ecchi"],
        ["Isekai", "Reincarnation"],
        "23 minutes"
    ),
    new Anime(
        "My Deer Friend Nokotan",
        "Shikanoko Nokonoko Koshitantan",
        "https://cdn.myanimelist.net/images/anime/1094/143324.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Nokotan,
        [],
        "TV",
        "Jul 7 2024 to Sep 18 2024",
        "Summer 2024",
        "Wit Studio",
        "Manga",
        ["Comedy"],
        ["Gag Humor", "School"],
        "23 minutes"
    ),
    new Anime(
        "My Dress-Up Darling",
        "Sono Bisque Doll wa Koi wo Suru",
        "https://cdn.myanimelist.net/images/anime/1179/119897.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.MyDressUpDarling,
        [""],
        "TV",
        "Jan 9 2022 to Mar 27 2022",
        "Winter 2022",
        "CloverWorks",
        "Manga",
        ["Romance"],
        ["Otaku Culture", "School"],
        "23 minutes",
    ),
    new Anime(
        "My Hero Academia",
        "Boku no Hero Academia",
        "https://cdn.myanimelist.net/images/anime/10/78745.jpg",
        13,
        "PG-13 - Teens 13 or older",
        Synopsis.MHA,
        [""],
        "TV",
        "Apr 3 2016 to Jun 26 2016",
        "Spring 2016",
        "Bones",
        "Manga",
        ["Action"],
        ["School", "Super Power"],
        "24 minutes"
    ),
    new Anime(
        "My Hero Academia Season 2",
        "Boku no Hero Academia 2nd Season",
        "https://cdn.myanimelist.net/images/anime/12/85221.jpg",
        25,
        "PG-13 - Teens 13 or older",
        Synopsis.MHA2,
        [""],
        "TV",
        "Apr 1 2017 to Sep 30 2017",
        "Spring 2017",
        "Bones",
        "Manga",
        ["Action"],
        ["School", "Super Power"],
        "23 minutes"
    ),
    new Anime(
        "My Hero Academia Season 3",
        "Boku no Hero Academia 3rd Season",
        "https://cdn.myanimelist.net/images/anime/1319/92084.jpg",
        25,
        "PG-13 - Teens 13 or older",
        Synopsis.MHA3,
        [""],
        "TV",
        "Apr 7 2018 to Sep 29 2018",
        "Spring 2018",
        "Bones",
        "Manga",
        ["Action"],
        ["School", "Super Power"],
        "23 minutes"
    ),
    new Anime(
        "My Hero Academia Season 4",
        "Boku no Hero Academia 4th Season",
        "https://cdn.myanimelist.net/images/anime/1412/107914.jpg",
        25,
        "PG-13 - Teens 13 or older",
        Synopsis.MHA4,
        [""],
        "TV",
        "Oct 12 2019 to Apr 4 2020",
        "Fall 2019",
        "Bones",
        "Manga",
        ["Action"],
        ["School", "Super Power"],
        "24 minutes"
    ),
    new Anime(
        "My Mental Choices are Completely Interfering With my School Romantic Comedy",
        "Ore no Nounai Sentakushi ga, Gakuen Love Comedy wo Zenryoku de Jama Shiteiru",
        "https://cdn.myanimelist.net/images/anime/10/53235.jpg",
        10,
        "PG-13 - Teens 13 or older",
        Synopsis.MentalChoices,
        [""],
        "TV",
        "Oct 10 2013 to Dec 12 2013",
        "Fall 2013",
        "Diomedea",
        "Light novel",
        ["Comedy", "Romance"],
        ["Harem", "School"],
        "24 minutes",
    ),
    new Anime(
        "My Next Life as a Villainess: All Routes Lead to Doom!",
        "Otome Game no Hametsu Flag shika Nai Akuyaku Reijou ni Tensei shiteshimatta...",
        "https://cdn.myanimelist.net/images/anime/1483/107061.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.OtomeGameDoomFlag,
        [""],
        "TV",
        "Apr 5 2020 to Jun 21 2020",
        "Spring 2020",
        "SILVER LINK",
        "Light novel",
        ["Comedy", "Fantasy", "Romance"],
        ["Isekai", "Reincarnation", "Reverse Harem", "School"],
        "24 minutes",
    ),
    new Anime(
        "My Next Life as a Villainess: All Routes Lead to Doom! X",
        "Otome Game no Hametsu Flag shika Nai Akuyaku Reijou ni Tensei shiteshimatta... X",
        "https://cdn.myanimelist.net/images/anime/1088/116439.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.OtomeGameDoomFlag2,
        [""],
        "TV",
        "Jul 3 2021 to Sep 18 2021",
        "Summer 2021",
        "SILVER LINK",
        "Light novel",
        ["Comedy", "Fantasy", "Romance"],
        ["Isekai", "Reincarnation", "Reverse Harem", "School"],
        "23 minutes",
    ),
    new Anime(
        "My Stepmom's Daughter Is My Ex",
        "Mamahaha no Tsurego ga Motokano datta",
        "https://cdn.myanimelist.net/images/anime/1708/123281.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.StepmomDaughterEx,
        [""],
        "TV",
        "Jul 6 2022 to Sep 21 2022",
        "Summer 2022",
        "Project No.9",
        "Light novel",
        ["Comedy", "Romance"],
        [""],
        "23 minutes",
    ),
]