export const Synopsis = {

    MaerchenMaedchen: `Hazuki Kagimura is a socially awkward girl with no friends; and having been recently adopted, she struggles to connect with her new family as well. Her only refuge from this painful reality is between the pages of stories where her vivid imagination allows her to live out her dreams of friendship and adventure. However, one day, an old and mysterious text appears in her book bag. On her way back to the library to return it, Hazuki sees a familiar girl who is seemingly invisible to everyone but her. Deciding to follow her, Hazuki is led a hidden library where a world she thought only existed in her dreams awaits her.
                       Märchen Mädchen tells the story of Hazuki's meeting with Shizuka Tsuchimikado, her very first friend, and discovering she has been chosen by the original print of Cinderella to become a powerful mage known as an Origin Master. Hazuki enrolls at Kuzunoha Girl's Magic Academy where she learns to conquer her fears and believe in her ability to create her own amazing story.`,

    MagicalSomera: `The story follows the everyday life of Somera Nonomoto who can use the strongest kenpo, Nonomoto Mahou-ken, which is inherited from her mother with her younger sister Kukuru.`,

    Magimoji: `After an unfortunate accident, completely normal heterosexual high school student Kouta Shibaki is branded as the school pervert. With girls avoiding Kouta like the plague, truly the young man's worst nightmare has come to fruition! One day in the school library, he stumbles upon a peculiar book said to possess the power to summon witches. Partly out of desperation, partly out of boredom, Kouta decides to play along with the joke of a book, until an apprentice witch going by the name of Rurumo Maji Mojiruka appears before him. In an unusual turn of events, Kouta ends up helping Rurumo with some general witchery tasks in exchange for his soul being spared.
               Majimoji Rurumo follows the misadventures of Rurumo as she attempts to persuade Kouta to use 666 magical wish-granting tickets in her efforts to become a fully-fledged witch, unaware that every time she grants a wish, Kouta's life is shortened. Aided by Rurumo's familiar Chiro, Kouta must decide between helping Rurumo or saving his own life.`,

    MahouShoujoNante: `Yuzuka Hanami is a young, carefree girl who lives the most ordinary life imaginable. Although her father works around the clock and her mother is rarely home, she still enjoys herself and strives to be an excellent student.
                       Miton, on the other hand, is an alien life-form with the ability to transform his master into a magical girl, a warrior who fights evil wherever it may appear. However, there are not as many enemies as there used to be, so Miton has been out of work for a while. Starving and homeless, he has taken up residence in a pile of garbage.
                       As Yuzuka walks past him one day, Miton seizes the opportunity to offer his services to the young girl. Yuzuka reluctantly agrees, but when she transforms into a magical girl and discovers that her outfit is a swimsuit, she begins to have second thoughts about what she has gotten herself into!`,

    MahouShoujoNante2: `Second season of Mahou Shoujo Nante Mou Ii Desu kara.`,

    Masamune: `When Masamune Makabe was a child, he was rejected by a rich, beautiful girl named Aki Adagaki, who gave him the nickname ''Piggy'' for being overweight. Devastated, Masamune put great effort into working out to improve his appearance. Now a handsome yet narcissistic high school student, Masamune is determined to exact revenge—he will have Aki fall madly in love with him and ultimately reject her the next time they meet.
               To his surprise, Masamune discovers he has transferred into Aki's school. Setting his plan into motion, Masamune first begins to form a relationship with the ''Brutal Princess'' but, despite his efforts, fails miserably at his initial attempts. Shockingly, when Masamune finally progresses towards his vengeance, he receives a mysterious letter addressing him by his old nickname. Unless Masamune discovers the sender's identity, his plan is doomed before it even starts!`,

    Military: `The story takes place during a conflict between the Krakozhia Dukedom and the Grania Republic. In the midst of the fighting, a savior appears to the Krakozhia Dukedom, and it is a high school student named Yano Souhei. Two female soldiers, First Lieutenant Ruto and Second Lieutenant Haruka, appear in tanks to intrude on Souhei's everyday life, followed by the enemy soldier Shachirofu, all of whom use firearms without hesitation at his house.`,

    MissBernard: `Sawako Machida—or "Miss Bernard," as she prefers to be called—can frequently be found in the school library with a book in hand. Whether or not she has read it, however, is another matter entirely. In her own words, Sawako finds it too much work to actually read, and would rather just make others believe she spends a lot of time reading. But in the same library where she constantly hangs out, there are other students who love books and are quite upset with her disdainful approach to reading their favorite titles.
                  As she pretends to read and discuss great literary works amid eccentric book lovers, Sawako finds herself learning something after all, as well as making new friends along the way.`,

    Kobayashi: `As Kobayashi sets off for another day at work, she opens her apartment door only to be met by an unusually frightening sight—the head of a dragon, staring at her from across the balcony. The dragon immediately transforms into a cute, busty, and energetic young girl dressed in a maid outfit, introducing herself as Tooru.
                It turns out that the stoic programmer had come across the dragon the previous night on a drunken excursion to the mountains, and since the mythical beast had nowhere else to go, she had offered the creature a place to stay in her home. Thus, Tooru had arrived to cash in on the offer, ready to repay her savior's kindness by working as her personal maidservant. Though deeply regretful of her words and hesitant to follow through on her promise, a mix of guilt and Tooru's incredible dragon abilities convinces Kobayashi to take the girl in.
                Despite being extremely efficient at her job, the maid's unorthodox methods of housekeeping often end up horrifying Kobayashi and at times bring more trouble than help. Furthermore, the circumstances behind the dragon's arrival on Earth seem to be much more complicated than at first glance, as Tooru bears some heavy emotions and painful memories. To top it all off, Tooru's presence ends up attracting several other mythical beings to her new home, bringing in a host of eccentric personalities. Although Kobayashi makes her best effort to handle the crazy situation that she has found herself in, nothing has prepared her for this new life with a dragon maid.`,

    KobayashiSpecial: `Wanting to take her affection for Kobayashi a step further, dragon maid Tooru is confident in her latest creation: a love potion! With Valentine's Day just around the corner, Tooru decides there is no better way to use the potion than in homemade chocolates. However, on the special holiday, Tooru's plan is quickly foiled after Kobayashi sees through her heartfelt yet deceptive gift.
                       Despite the unsuccessful attempt, many opportunities still await. Between the lively atmosphere and a trip to the hot springs, Kobayashi and the dragons indulge themselves in the sweet festivities.`,

    Kobayashi2: `As Tooru continues on her quest to become the greatest maid and Kanna Kamui fully immerses in her life as an elementary school student, there is not a dull day in the Kobayashi household with mischief being a daily staple. On one such day, however, a massive landslide is spotted on the hill where Kobayashi and Tooru first met—a clear display of a dragon's might. When none of the dragons they know claim responsibility, the perpetrator herself descends from the skies: Ilulu, the radical Chaos Dragon with monstrous power rivaling that of Tooru.
                 Sickened by Tooru's involvement with humans, Ilulu resorts to the typical dragon method of resolving conflict—a battle to the death. Despite such behavior, she becomes intrigued by Kobayashi's ability to befriend dragons and decides instead to observe just what makes Kobayashi so special. With a new troublesome dragon in town, Kobayashi's eccentric life with a dragon maid is only getting merrier.`,

    MissKuroitsu: `On the outside, Agastia is a firm specializing in entertainment, well-known for the theme park it operates. However, beneath such an exterior lies a monumental secret: Agastia is one of various highly advanced evil organizations that aim for world domination. Despite its true nature, the company boasts enticements that make it worthwhile to put up with the work environment. Led by its great leader Akashic, Agastia has recently become a frontrunner in reaching its fellow groups' common goal.
                   Working for Agastia's Monster Development Division, Touka Kuroitsu is a researcher who primarily does fieldwork due to the eccentricities of her seniors. Kuroitsu's everyday jobs also include giving abrupt presentations and proposals, meeting ridiculous expectations for monster designs, and accompanying said monsters to face inevitable defeat by Agastia's enemies. Nevertheless, nothing will stop Kuroitsu from doing her best if it means getting the promotion she desires!`,

    MobPsycho: `Eighth-grader Shigeo "Mob" Kageyama has tapped into his inner wellspring of psychic prowess at a young age. But the power quickly proves to be a liability when he realizes the potential danger in his skills. Choosing to suppress his power, Mob's only present use for his ability is to impress his longtime crush, Tsubomi, who soon grows bored of the same tricks.
                In order to effectuate control on his skills, Mob enlists himself under the wing of Arataka Reigen, a con artist claiming to be a psychic, who exploits Mob's powers for pocket change. Now, exorcising evil spirits on command has become a part of Mob's daily, monotonous life. However, the psychic energy he exerts is barely the tip of the iceberg; if his vast potential and unrestrained emotions run berserk, a cataclysmic event that would render him completely unrecognizable will be triggered. The progression toward Mob's explosion is rising and attempting to stop it is futile.`,

    Morita: `Morita Mayu, a high school girl. She is extremely reticent and her silence and habit of looking at people's eyes straightly sometimes cause misunderstanding. The reason behind it is not because she doesn’t like to talk nor because she has nothing to say. The reason she rarely speaks is due to the fact she thinks too much before speaking, thus losing the timing to speak altogether. But she lives a happy school life with her classmates.`,

    Morita2: `The second season of Morita-san wa Mukuchi that directly follows the first.`,

    Musasino: `Sequel series to Urawa no Usagi-chan.`,

    MushokuTensei: `Despite being bullied, scorned, and oppressed all of his life, a 34-year-old shut-in still found the resolve to attempt something heroic—only for it to end in a tragic accident. But in a twist of fate, he awakens in another world as Rudeus Greyrat, starting life again as a baby born to two loving parents.
                    Preserving his memories and knowledge from his previous life, Rudeus quickly adapts to his new environment. With the mind of a grown adult, he starts to display magical talent that exceeds all expectations, honing his skill with the help of a mage named Roxy Migurdia. Rudeus learns swordplay from his father, Paul, and meets Sylphiette, a girl his age who quickly becomes his closest friend.
                    As Rudeus' second chance at life begins, he tries to make the most of his new opportunity while conquering his traumatic past. And perhaps, one day, he may find the one thing he could not find in his old world—love.`,

    MushokuTenseiPart2: `After the mysterious mana calamity, Rudeus Greyrat and his fierce student Eris Boreas Greyrat are teleported to the Demon Continent. There, they team up with their newfound companion Ruijerd Supardia—the former leader of the Superd's Warrior group—to form "Dead End," a successful adventurer party. Making a name for themselves, the trio journeys across the continent to make their way back home to Fittoa.
                         Following the advice he received from the faceless god Hitogami, Rudeus saves Kishirika Kishirisu, the Great Emperor of the Demon World, who rewards him by granting him a strange power. Now, as Rudeus masters the powerful ability that offers a number of new opportunities, it might prove to be more than what he bargained for when unexpected dangers threaten to hinder their travels.`,

    MushokuTensei2Special: `In the immediate aftermath of the mana calamity, Sylphiette finds herself teleported to the heart of the Asura Kingdom: the royal palace. Her sudden appearance accidentally saves the life of second princess Ariel Anemoi Asura, who has her sights set on becoming the ruler of the realm. Witnessing Sylphiette's talent with combat magic firsthand, Ariel recruits her as her bodyguard and right-hand woman, commencing their journey to power—which proves far more treacherous than first imagined.`,

    MyDressUpDarling: `High school student Wakana Gojou spends his days perfecting the art of making hina dolls, hoping to eventually reach his grandfather's level of expertise. While his fellow teenagers busy themselves with pop culture, Gojou finds bliss in sewing clothes for his dolls. Nonetheless, he goes to great lengths to keep his unique hobby a secret, as he believes that he would be ridiculed were it revealed.
                       Enter Marin Kitagawa, an extraordinarily pretty girl whose confidence and poise are in stark contrast to Gojou's meekness. It would defy common sense for the friendless Gojou to mix with the likes of Kitagawa, who is always surrounded by her peers. However, the unimaginable happens when Kitagawa discovers Gojou's prowess with a sewing machine and brightly confesses to him about her own hobby: cosplay. Because her sewing skills are pitiable, she decides to enlist his help.
                       As Gojou and Kitagawa work together on one cosplay outfit after another, they cannot help but grow close—even though their lives are worlds apart.`,

    MHA: `The appearance of "quirks," newly discovered super powers, has been steadily increasing over the years, with 80 percent of humanity possessing various abilities from manipulation of elements to shapeshifting. This leaves the remainder of the world completely powerless, and Izuku Midoriya is one such individual.
          Since he was a child, the ambitious middle schooler has wanted nothing more than to be a hero. Izuku's unfair fate leaves him admiring heroes and taking notes on them whenever he can. But it seems that his persistence has borne some fruit: Izuku meets the number one hero and his personal idol, All Might. All Might's quirk is a unique ability that can be inherited, and he has chosen Izuku to be his successor!
          Enduring many months of grueling training, Izuku enrolls in UA High, a prestigious high school famous for its excellent hero training program, and this year's freshmen look especially promising. With his bizarre but talented classmates and the looming threat of a villainous organization, Izuku will soon learn what it really means to be a hero.`,

    MHA2: `At UA Academy, not even a violent attack can disrupt their most prestigious event: the school sports festival. Renowned across Japan, this festival is an opportunity for aspiring heroes to showcase their abilities, both to the public and potential recruiters.
           However, the path to glory is never easy, especially for Izuku Midoriya—whose quirk possesses great raw power but is also cripplingly inefficient. Pitted against his talented classmates, such as the fire and ice wielding Shouto Todoroki, Izuku must utilize his sharp wits and master his surroundings to achieve victory and prove to the world his worth.`,

    MHA3: `As summer arrives for the students at UA Academy, each of these superheroes-in-training puts in their best efforts to become renowned heroes. They head off to a forest training camp run by UA's pro heroes, where the students face one another in battle and go through dangerous tests, improving their abilities and pushing past their limits. However, their school trip is suddenly turned upside down when the League of Villains arrives, invading the camp with a mission to capture one of the students.
           Boku no Hero Academia 3rd Season follows Izuku "Deku" Midoriya, an ambitious student training to achieve his dream of becoming a hero similar to his role model—All Might. Being one of the students caught up amidst the chaos of the villain attack, Deku must take a stand with his classmates and fight for their survival.`,

    MHA4: `After successfully passing his Provisional Hero License exam, Izuku "Deku" Midoriya seeks out an extracurricular internship with a professional hero agency. At the recommendation of his mentor All Might, Midoriya lands a position under All Might's former sidekick, Sir Nighteye, now a famous hero in his own right.
           As Midoriya's classmates further their own abilities through various internships, up-and-coming villain Kai Chisaki utilizes his terrifying powers to gather favor in the criminal underworld. Known by the moniker Overhaul, Chisaki's ambitions collide with the League of Villains and its leader, Tomura Shigaraki.
           Through his work with Sir Nighteye, Midoriya discovers Chisaki's crime syndicate and the villain's hostile relationship with a mysterious young girl named Eri. Fearing for the child's safety, Midoriya and his upperclassman Mirio Toogata must work together to put an end to Chisaki's reign of terror.`,

    MentalChoices: `For Kanade Amakusa, life as a high schooler should have been normal, and it would have been—if he wasn't living with the most ridiculous curse imaginable. "Absolute Choice," a system forced upon him by a self-proclaimed god, randomly presents a mental selection of actions that he must act out based on his choice. To add to his dilemma, it tends to occur in the most public of places, and his options never seem to deviate from the rude and crude in nature.
                    As a result, the helpless boy stresses through each day, fumbling to repair his already tarnished reputation while desperately praying to avoid the next spontaneous episode of Absolute Choice. To his dismay, the one in charge is always one step ahead of him and proceeds to not-so-subtly "choice" him into the lives of several girls at his school. Just when Kanade's school life can't seem to be doomed any further, a decision that he reluctantly selects on the way home sends a beautiful girl crashing down from the sky, along with the promise of more hysterically hellish choices.`,

    OtomeGameDoomFlag: `Most people would prefer being the protagonist of a world full of adventure, be it in a game or in another world. But, unfortunately, a certain girl is not so lucky. Regaining the memories of her past life, she realizes that she was reborn in the world of Fortune Lover—one of the games she used to play.
                        Unfortunately, the character she was reincarnated into—Catarina Claes—is the game's main antagonist, who faces utter doom in every ending. Using her extensive knowledge of the game, she takes it upon herself to escape from the chains of this accursed destiny.
                        However, this will not be an easy feat, especially since she needs to be cautious as to not set off death flags that may speed up the impending doom she is trying to avoid. Even so, to make a change that will affect the lives of everyone around her, she strives—not as the heroine—but as the villainess.`,

    OtomeGameDoomFlag2: `With no more death flags in sight, personable but dense Catarina Claes is finally able to lead a peaceful life surrounded by all of her friends and family. For that reason, she is determined to enjoy the school festival to the fullest without any concern on her mind.
                         Unbeknownst to her, however, the story of Fortune Lover—the game she used to play—has yet to end. Even more characters make an appearance, each with their own agenda to fulfill, and new mysteries await Katarina and those she loves. Will there be any way to avoid a bad ending when Catarina cannot remember what happens next?`,

    StepmomDaughterEx: `Listless geek Mizuto Irido and introverted nerd Yume Ayai seemed like a match made in heaven, connected by their mutual love for literature. Unfortunately, their differences gradually grew, and they separated just after their middle school graduation. But, as if by divine comedy, the two find themselves reunited as step-siblings.
                        A rivalry begins to brew between the former couple, both unwilling to acknowledge the other as the older sibling. In an attempt to "solve" this issue, Mizuto and Yume agree upon a rule: whoever crosses the boundaries of siblinghood norms loses, and the winner will not only be called the older sibling, but also get to make a request. However, now that they live under the same roof, the lingering memories they share start to influence their actions—possibly rekindling the feelings that may not have been fully extinguished in the first place.`,


}