import { Anime } from "@/lib/class/Anime";
import { Synopsis } from "./tSynopsis";

export const t_anime = [
    new Anime(
        "Takamiya Nasuno desu! Teekyuu Spin-off",
        "",
        "https://cdn.myanimelist.net/images/anime/12/73473.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.TeekyuuSpinOff,
        [""],
        "TV",
        "Apr 7 2015 to Jun 23 2015",
        "Spring 2015",
        "Millepensee",
        "Manga",
        ["Comedy", "Slice of Life"],
        [""],
        "2 minutes",
    ),
    new Anime(
        "Tawawa on Monday",
        "Getsuyoubi no Tawawa",
        "https://cdn.myanimelist.net/images/anime/13/83576.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Tawawa,
        [""],
        "ONA",
        "Oct 10 2016 to Dec 26 2016",
        "Fall 2016",
        "PINE JAM",
        "Web manga",
        ["Slice of Life", "Ecchi"],
        [""],
        "4 minutes",
    ),
    new Anime(
        "Tawawa on Monday 2",
        "Getsuyoubi no Tawawa 2",
        "https://cdn.myanimelist.net/images/anime/1370/117813.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Tawawa2,
        [""],
        "ONA",
        "Sep 20 2021 to Dec 6 2021",
        "Fall 2021",
        "Yokohama Animation Lab",
        "Other",
        ["Slice of Life", "Ecchi"],
        [""],
        "5 minutes",
    ),
    new Anime(
        "Takt Op. Destiny",
        "",
        "https://cdn.myanimelist.net/images/anime/1449/117797.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Takt,
        [""],
        "TV",
        "Oct 6 2021 to Dec 22 2021",
        "Fall 2021",
        "Madhouse, MAPPA",
        "Mixed media",
        ["Action", "Fantasy", "Sci-Fi"],
        ["Music"],
        "23 minutes",
    ),
    new Anime(
        "Teekyu",
        "Teekyuu",
        "https://cdn.myanimelist.net/images/anime/1703/98658.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Teekyu,
        [""],
        "TV",
        "Oct 7 2012 to Dec 23 2012",
        "Fall 2012",
        "MAPPA",
        "Manga",
        ["Comedy", "Sports"],
        ["School"],
        "2 minutes",
    ),
    new Anime(
        "Teekyu 2",
        "Teekyuu 2",
        "https://cdn.myanimelist.net/images/anime/1432/98659.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Teekyu2,
        [""],
        "TV",
        "Jul 7 2013 to Sep 22 2013",
        "Summer 2013",
        "MAPPA",
        "Manga",
        ["Comedy"],
        ["School"],
        "2 minutes",
    ),
    new Anime(
        "Teekyu 3",
        "Teekyuu 3",
        "https://cdn.myanimelist.net/images/anime/11/73503.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Teekyu3,
        [""],
        "TV",
        "Oct 6 2013 to Dec 22 2013",
        "Fall 2013",
        "MAPPA",
        "Manga",
        ["Comedy"],
        ["School"],
        "2 minutes",
    ),
    new Anime(
        "Teekyu 4",
        "Teekyuu 4",
        "https://cdn.myanimelist.net/images/anime/10/73472.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Teekyu4,
        [""],
        "TV",
        "Apr 7 2015 to Jun 23 2015",
        "Spring 2015",
        "Millepensee",
        "Manga",
        ["Comedy"],
        [""],
        "2 minutes",
    ),
    new Anime(
        "Teekyu 5",
        "Teekyuu 5",
        "https://cdn.myanimelist.net/images/anime/9/75010.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Teekyu5,
        [""],
        "TV",
        "Jul 7 2015 to Sep 22 2015",
        "Summer 2015",
        "Millepensee",
        "Manga",
        ["Comedy"],
        [""],
        "2 minutes",
    ),
    new Anime(
        "Teekyu 6",
        "Teekyuu 6",
        "https://cdn.myanimelist.net/images/anime/13/76645.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Teekyu6,
        [""],
        "TV",
        "Oct 6 2015 to Dec 22 2015",
        "Fall 2015",
        "Millepensee",
        "Manga",
        ["Comedy"],
        [""],
        "2 minutes",
    ),
    new Anime(
        "Teekyu 7",
        "Teekyuu 7",
        "https://cdn.myanimelist.net/images/anime/6/77830.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Teekyu7,
        [""],
        "TV",
        "Jan 12 2016 to Mar 29 2016",
        "Winter 2016",
        "Millepensee",
        "Manga",
        ["Comedy"],
        [""],
        "2 minutes",
    ),
    new Anime(
        "Teekyu 8",
        "Teekyuu 8",
        "https://cdn.myanimelist.net/images/anime/8/81424.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Teekyu8,
        [""],
        "TV",
        "Oct 5 2016 to Dec 21 2016",
        "Fall 2016",
        "Millepensee",
        "Manga",
        ["Comedy"],
        [""],
        "2 minutes",
    ),
    new Anime(
        "Teekyu 9",
        "Teekyuu 9",
        "https://cdn.myanimelist.net/images/anime/5/86833.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Teekyu9,
        [""],
        "TV",
        "Jul 12 2017 to Sep 27 2017",
        "Summer 2017",
        "Millepensee",
        "Manga",
        ["Comedy"],
        [""],
        "2 minutes",
    ),
    new Anime(
        "The Demon Girl Next Door",
        "Machikado Mazoku",
        "https://cdn.myanimelist.net/images/anime/1633/111518.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.MachikadoMazoku,
        [""],
        "TV",
        "Jul 12 2019 to Sep 27 2019",
        "Summer 2019",
        "J.C. Staff",
        "4-koma manga",
        ["Comedy", "Fantasy"],
        ["CGDCT", "Mahou Shoujo", "School"],
        "24 minutes",
    ),
    new Anime(
        "The Demon Sword Master of Excalibur Academy",
        "Seiken Gakuin no Makentsukai",
        "https://cdn.myanimelist.net/images/anime/1506/138529.jpg",
        12,
        "R - 17+ (violence & profanity)",
        Synopsis.DemonSword,
        [],
        "TV",
        "Oct 3 2023 to Dec 19 2023",
        "Fall 2023",
        "Passione",
        "Light novel",
        ["Action", "Fantasy"],
        ["Harem", "Reincarnation", "School"],
        "23 minutes"
    ),
    new Anime(
        "The Familiar of Zero",
        "Zero no Tsukaima",
        "https://cdn.myanimelist.net/images/anime/8/20680.jpg",
        13,
        "PG-13 - Teens 13 or older",
        Synopsis.FamiliarZero,
        [""],
        "TV",
        "Jul 3 2006 to Sep 25 2006",
        "Summer 2006",
        "J.C. Staff",
        "Light novel",
        ["Action", "Adventure", "Comedy", "Fantasy", "Romance", "Ecchi"],
        ["Harem", "Isekai", "School"],
        "23 minutes",
    ),
    new Anime(
        "The Familiar of Zero: Knight of the Twin Moons",
        "Zero no Tsukaima: Futatsuki no Kishi",
        "https://cdn.myanimelist.net/images/anime/2/22740.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.FamiliarZero2,
        [""],
        "TV",
        "Jul 9 2007 to Sep 24 2007",
        "Summer 2007",
        "J.C. Staff",
        "Light novel",
        ["Action", "Adventure", "Comedy", "Fantasy", "Romance", "Ecchi"],
        ["Harem", "Isekai", "School"],
        "23 minutes",
    ),
    new Anime(
        "The Familiar of Zero: Rondo of Princesses",
        "Zero no Tsukaima: Princesses no Rondo",
        "https://cdn.myanimelist.net/images/anime/6/10256.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.FamiliarZero3,
        [""],
        "TV",
        "Jul 7 2008 to Sep 22 2008",
        "Summer 2008",
        "J.C. Staff",
        "Light novel",
        ["Action", "Adventure", "Comedy", "Fantasy", "Romance", "Ecchi"],
        ["Harem", "Isekai", "School"],
        "24 minutes",
    ),
    new Anime(
        "The Familiar of Zero F",
        "Zero no Tsukaima F",
        "https://cdn.myanimelist.net/images/anime/2/75559.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.FamiliarZero4,
        [""],
        "TV",
        "Jan 7 2012 to Mar 24 2012",
        "Winter 2012",
        "J.C. Staff",
        "Light novel",
        ["Action", "Adventure", "Comedy", "Fantasy", "Romance", "Ecchi"],
        ["Harem", "Isekai", "School"],
        "24 minutes",
    ),
    new Anime(
        "The Great Jahy Will Not Be Defeated!",
        "Jahy-sama wa Kujikenai!",
        "https://cdn.myanimelist.net/images/anime/1154/115599.jpg",
        20,
        "PG-13 - Teens 13 or older",
        Synopsis.JahySama,
        [""],
        "TV",
        "Aug 1 2021 to Dec 19 2021",
        "Summer 2021",
        "SILVER LINK",
        "Manga",
        ["Comedy", "Supernatural"],
        [""],
        "23 minutes",
    ),
    new Anime(
        "The Greatest Demon Lord Is Reborn as a Typical Nobody",
        "Shijou Saikyou no Daimaou, Murabito A ni Tensei suru",
        "https://cdn.myanimelist.net/images/anime/1904/120095.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.GreatestDemonLord,
        [""],
        "TV",
        "Apr 6 2022 to Jun 22 2022",
        "Spring 2022",
        "SILVER LINK, Blade",
        "Light novel",
        ["Action", "Fantasy"],
        ["Harem", "Reincarnation", "School"],
        "24 minutes",
    ),
    new Anime(
        "The Helpful Fox Senko-san",
        "Sewayaki Kitsune no Senko-san",
        "https://cdn.myanimelist.net/images/anime/1814/99677.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.SenkoSan,
        [""],
        "TV",
        "Apr 10 2019 to Jun 26 2019",
        "Spring 2019",
        "Doga Kobo",
        "Web manga",
        ["Slice of Life", "Supernatural"],
        ["Iyashikei"],
        "23 minutes",
    ),
    new Anime(
        "The Hidden Dungeon Only I Can Enter",
        "Ore dake Haireru Kakushi Dungeon",
        "https://cdn.myanimelist.net/images/anime/1988/115708.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.HiddenDungeon,
        [""],
        "TV",
        "Jan 9 2021 to Mar 27 2021",
        "Winter 2021",
        "Okuruto Noboru",
        "Light novel",
        ["Action", "Adventure", "Fantasy", "Ecchi"],
        ["Harem"],
        "24 minutes",
    ),
    new Anime(
        "The Irregular at Magic High School",
        "Mahouka Koukou no Rettousei",
        "https://cdn.myanimelist.net/images/anime/11/61039.jpg",
        26,
        "PG-13 - Teens 13 or older",
        Synopsis.IrregularMagicHighSchool,
        [""],
        "TV",
        "Apr 6 2014 to Sep 28 2014",
        "Spring 2014",
        "Madhouse",
        "Light novel",
        ["Action", "Fantasy", "Romance", "Sci-Fi"],
        ["School"],
        "23 minutes",
    ),
    new Anime(
        "The Misfit of Demon King Academy",
        "Maou Gakuin no Futekigousha: Shijou Saikyou no Maou no Shiso, Tensei shite Shison-tachi no Gakkou e Kayou",
        "https://cdn.myanimelist.net/images/anime/1126/108573.jpg",
        13,
        "R - 17+ (violence & profanity)",
        Synopsis.MisfitOfDemonKingAcademy,
        [""],
        "TV",
        "Jul 4 2020 to Sep 26 2020",
        "Summer 2020",
        "SILVER LINK",
        "Light novel",
        ["Action", "Fantasy"],
        ["Reincarnation", "School"],
        "23 minutes",
    ),
    new Anime(
        "The Misfit of Demon King Academy Ⅱ",
        "Maou Gakuin no Futekigousha II: Shijou Saikyou no Maou no Shiso, Tensei shite Shison-tachi no Gakkou e Kayou",
        "https://cdn.myanimelist.net/images/anime/1369/139553.jpg",
        12,
        "R - 17+ (violence & profanity)",
        Synopsis.MisfitOfDemonKingAcademy2,
        [""],
        "TV",
        "Jan 8 2023 to Sep 24 2023",
        "Winter 2023",
        "SILVER LINK",
        "Light novel",
        ["Action", "Fantasy"],
        ["Reincarnation", "School"],
        "23 minutes"
    ),
    new Anime(
        "The Misfit of Demon King Academy II Part 2",
        "Maou Gakuin no Futekigousha II: Shijou Saikyou no Maou no Shiso, Tensei shite Shison-tachi no Gakkou e Kayou Part 2",
        "https://cdn.myanimelist.net/images/anime/1399/141651.jpg",
        12,
        "R - 17+ (violence & profanity)",
        Synopsis.MisfitOfDemonKingAcademy2Part2,
        [""],
        "TV",
        "Apr 12 2024 to Jul 25 2024",
        "Spring 2024",
        "SILVER LINK",
        "Light novel",
        ["Action", "Fantasy"],
        ["Reincarnation", "School"],
        "23 minutes"
    ),
    new Anime(
        "The Quintessential Quintuplets",
        "5-toubun no Hanayome",
        "https://cdn.myanimelist.net/images/anime/1819/97947.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Quintuplets1,
        [""],
        "TV",
        "Jan 11 2019 to Mar 29 2019",
        "Winter 2019",
        "Tezuka Productions",
        "Manga",
        ["Comedy", "Romance"],
        ["Harem", "School"],
        "24 minutes"
    ),
    new Anime(
        "The Quintessential Quintuplets 2",
        "5-toubun no Hanayome ∬",
        "https://cdn.myanimelist.net/images/anime/1775/109514.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Quintuplets2,
        [""],
        "TV",
        "Jan 8 2021 to Mar 26 2021",
        "Winter 2021",
        "Bibury Animation Studios",
        "Manga",
        ["Comedy", "Romance"],
        ["Harem", "School"],
        "24 minutes"
    ),
    new Anime(
        "The Quintessential Quintuplets Movie",
        "5-toubun no Hanayome Movie",
        "https://cdn.myanimelist.net/images/anime/1037/122516.jpg",
        1,
        "PG-13 - Teens 13 or older",
        Synopsis.QuintupletsMovie,
        [""],
        "Movie",
        "May 20 2022",
        "Spring 2022",
        "Bibury Animation Studios",
        "Manga",
        ["Comedy", "Romance"],
        ["Harem", "School"],
        "2 hours 16 minutes"
    ),
    new Anime(
        "The Rising of the Shield Hero",
        "Tate no Yuusha no Nariagari",
        "https://cdn.myanimelist.net/images/anime/1490/101365.jpg",
        25,
        "PG-13 - Teens 13 or older",
        Synopsis.ShieldHero,
        [""],
        "TV",
        "Jan 9 2019 to Jun 26 2019",
        "Winter 2019",
        "Kinema Citrus",
        "Light novel",
        ["Action", "Adventure", "Drama", "Fantasy"],
        ["Isekai"],
        "24 minutes",
    ),
    new Anime(
        "The Rising of the Shield Hero Season 2",
        "Tate no Yuusha no Nariagari Season 2",
        "https://cdn.myanimelist.net/images/anime/1143/121873.jpg",
        13,
        "PG-13 - Teens 13 or older",
        Synopsis.ShieldHero2,
        [""],
        "TV",
        "Apr 6 2022 to Jun 29 2022",
        "Spring 2022",
        "Kinema Citrus, DR Movie",
        "Light novel",
        ["Action", "Adventure", "Drama", "Fantasy"],
        ["Isekai"],
        "23 minutes",
    ),
    new Anime(
        "The Strongest Sage With the Weakest Crest",
        "Shikkakumon no Saikyou Kenja",
        "https://cdn.myanimelist.net/images/anime/1132/120388.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.StrongestSage,
        [""],
        "TV",
        "Jan 8 2022 to Mar 26 2022",
        "Winter 2022",
        "J.C. Staff",
        "Light novel",
        ["Action", "Adventure", "Fantasy"],
        ["Reincarnation"],
        "23 minutes",
    ),
    new Anime(
        "The World's Finest Assassin Gets Reincarnated in Another World as an Aristocrat",
        "Sekai Saikou no Ansatsusha, Isekai Kizoku ni Tensei suru",
        "https://cdn.myanimelist.net/images/anime/1928/117620.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.WorldFinestAssassin,
        [""],
        "TV",
        "Oct 6 2021 to Dec 22 2021",
        "Fall 2021",
        "SILVER LINK, Studio Palette",
        "Light novel",
        ["Action", "Drama", "Fantasy", "Mystery", "Romance"],
        ["Isekai", "Reincarnation"],
        "23 minutes",
    ),
    new Anime(
        "This Art Club Has a Problem!",
        "Kono Bijutsu-bu ni wa Mondai ga Aru!",
        "https://cdn.myanimelist.net/images/anime/3/80688.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.ArtClubHasAProblem,
        [""],
        "TV",
        "Jul 8 2016 to Sep 23 2016",
        "Summer 2016",
        "feel",
        "Manga",
        ["Comedy", "Romance"],
        ["School", "Visual Arts"],
        "24 minutes",
    ),
    new Anime(
        "Three Leaves, Three Colors",
        "Sansha Sanyou",
        "https://cdn.myanimelist.net/images/anime/13/79415.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.ThreeLeavesThreeColors,
        [""],
        "TV",
        "Apr 11 2016 to Jun 27 2016",
        "Spring 2016",
        "Doga Kobo",
        "4-koma manga",
        ["Comedy", "Slice of Life"],
        ["CGDCT", "School"],
        "24 minutes",
    ),
    new Anime(
        "Today's Menu for the Emiya Family",
        "Emiya-san Chi no Kyou no Gohan",
        "https://cdn.myanimelist.net/images/anime/8/89981.jpg",
        13,
        "PG-13 - Teens 13 or older",
        Synopsis.TodaysMenuForEmiyaFamily,
        [""],
        "ONA",
        "Jan 25 2018 to Jan 1 2019",
        "Winter 2018",
        "ufotable",
        "Web manga",
        ["Gourmet", "Slice of Life"],
        ["Iyashikei"],
        "13 minutes",
    ),
    new Anime(
        "Tomo-chan Is a Girl!",
        "Tomo-chan wa Onnanoko!",
        "https://cdn.myanimelist.net/images/anime/1444/131828.jpg",
        13,
        "PG-13 - Teens 13 or older",
        Synopsis.TomoChan,
        [""],
        "TV",
        "Jan 5 2023 to Mar 30 2023",
        "Winter 2023",
        "Lay-duce",
        "Web manga",
        ["Comedy", "Romance"],
        ["School"],
        "23 minutes",
    ),
    new Anime(
        "TONIKAWA: Over the Moon For You",
        "Tonikaku Kawaii",
        "https://cdn.myanimelist.net/images/anime/1613/108722.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Tonikawa,
        [""],
        "TV",
        "Oct 3 2020 to Dec 19 2020",
        "Fall 2020",
        "Seven Arcs",
        "Manga",
        ["Comedy", "Romance"],
        [""],
        "23 minutes",
    ),
    new Anime(
        "TONIKAWA: Over The Moon For You Season 2",
        "Tonikaku Kawaii 2nd Season",
        "https://cdn.myanimelist.net/images/anime/1996/133361.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Tonikawa2,
        [""],
        "TV",
        "Apr 8 2023 to Jun 24 2023",
        "Spring 2023",
        "Seven Arcs",
        "Manga",
        ["Comedy", "Romance"],
        [""],
        "23 minutes",
    ),
    new Anime(
        "Toradora!",
        "",
        "https://cdn.myanimelist.net/images/anime/13/22128.jpg",
        25,
        "PG-13 - Teens 13 or older",
        Synopsis.Toradora,
        [""],
        "TV",
        "Oct 2 2008 to Mar 26 2009",
        "Fall 2008",
        "J.C. Staff",
        "Light novel",
        ["Drama", "Romance"],
        ["Love Polygon", "School"],
        "23 minutes",
    ),
    new Anime(
        "Tsuredure Children",
        "Tsurezure Children",
        "https://cdn.myanimelist.net/images/anime/12/86676.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.TsuredureChildren,
        [""],
        "TV",
        "Jul 4 2017 to Sep 19 2017",
        "Summer 2017",
        "Studio Gokumi",
        "4-koma manga",
        ["Comedy", "Romance"],
        ["School"],
        "12 minutes",
    ),
    new Anime(
        "Twin Star Exorcists",
        "Sousei no Onmyouji",
        "https://cdn.myanimelist.net/images/anime/12/79556.jpg",
        50,
        "PG-13 - Teens 13 or older",
        Synopsis.TwinStarExorcists,
        [""],
        "TV",
        "Apr 6 2016 to Mar 29 2017",
        "Spring 2016",
        "Pierrot",
        "Manga",
        ["Action", "Fantasy", "Romance"],
        ["Mythology"],
        "24 minutes",
    ),
]