export const Synopsis = {
    TeekyuuSpinOff: `A spin-off from Teekyuu which centers on the daily life of Nasuno Takamiya, the "exceedingly airheaded" school tennis club member in Teekyuu, and her friends.`,

    Tawawa: `Oniisan, a typical salaryman, has the weekly duty of protecting high school student Ai-chan from gropers by escorting her during their Monday morning train commutes. Despite the short time Oniisan and Ai-chan spend together, they manage to bond and learn more about each other's lives. To help Oniisan get through his Monday blues, Ai-chan gives him small presents as motivation.
             Ai-chan and many other girls—who all share a certain attractive trait—lighten up the Mondays of their male friends and colleagues for the long week ahead.`,

    Tawawa2: `The anime follows a salaryman who has a chance meeting with a girl named Ai on the train. They begin to meet every Monday on the train, with the man serving as her bodyguard on the crowded commute while they chat.`,

    Takt: `The United States of America has been in chaos ever since the emergence of D2s, an invasive species originating from a black meteorite that fell to Earth. A public decree banned citizens from playing any melodies, to prevent further casualties caused by the D2s' hatred for music—even now, in 2047, this prohibition is still in effect. Humanity's only form of defense against the D2s are Musicarts, young women representing pieces of classical music; and Conductors, the ones controlling them.
           Takt Asahina, an aloof piano prodigy, finds himself transformed into a Conductor following a spontaneous D2 attack. The same incident kills Anna Schneider's younger sister, Cosette, and brings Takt into contact with his Musicart, Destiny. Searching for a means of stabilizing the pact between themselves, Takt and Destiny—alongside Anna—embark on a perilous journey to the Symphonica Headquarters in New York City.
           Takt is in a hurry to reach the city so that he can play the piano again, even though his passion attracts the creatures he has come to despise. Meanwhile, Destiny's sense of duty drags the group into trouble along the way. With a D2-infested path and many more arduous obstacles ahead of them, will the trio make it to New York City in one piece?`,

    Teekyu: `Teekyuu is all about the wacky antics of four schoolgirls—Kanae Shinjou gets bored easily and often breaks the laws of physics to get what she wants; Nasuno Takamiya is incredibly rich and knows how to make things go her way; Marimo Bandou would probably get arrested from her actions like eating panties or kidnapping children; and Yuri Oshimoto, their ordinary junior, rounds out the eccentric bunch that forms the sole members of their school's tennis club.
             Despite their interest in learning the sport, the older girls prefer messing around, while Yuri, being the only one who actually knows how to play and the most mature in spite of being younger, has to deal with her seniors' out of control behavior.
             When these four girls come together, insanity ensues in this lightning-paced comedy about a tennis club that doesn't really play tennis.`,

    Teekyu2: `Second season of Teekyu series.`,

    Teekyu3: `Third season of Teekyuu series.`,

    Teekyu4: `Fourth season of Teekyuu series.`,

    Teekyu5: `Fifth season of Teekyuu series.`,

    Teekyu6: `Sixth season of Teekyuu series.`,

    Teekyu7: `Seventh season of Teekyuu series.`,

    Teekyu8: `Eighth season of Teekyuu series.`,

    Teekyu9: `Ninth season of Teekyuu series.`,

    MachikadoMazoku: `After a strange dream of a mysterious ancestor, high school student Yuuko Yoshida wakes to see that she has grown demonic horns and a tail. Dazed and confused, her mother reveals to her a dark family secret: her family is descended from a Dark Clan that was banished to live powerless and destitute by their mortal enemies, the magical girls of the Light Clan. The only way to lift their ancestry's curse is for Yuuko to find a magical girl, murder her, and splatter her blood all over her ancestor's Demon God statue.
                      Fortunately for "Shadow Mistress Yuuko," a magical girl saves her from being run over by an oncoming truck. Unfortunately, Momo Chiyoda happens to be Yuuko's classmate at Sakuragaoka High and is much stronger than her in both strength and endurance. Taking pity on her wimpy assailant, the magical girl agrees to train Yuuko and help her unlock her dormant powers. Now, Yuuko must rise up and defeat her generous frenemy to save her family from the terrible grip of poverty.`,

    FamiliarZero: `Louise Françoise Le Blanc de La Vallière is a self-absorbed mage in a world of wands, cloaks, and royalty. Although she studies at Tristain Academy, a prestigious school for magicians, she has a major problem: Louise is unable to cast magic properly, earning her the nickname of "Louise the Zero" from her classmates.
                   When the first year students are required to perform a summoning ritual, Louise's summoning results in a catastrophic explosion! Everyone deems this to be yet another failure, but when the smoke clears, a boy named Saito Hiraga appears. Now Louise's familiar, Saito is treated as a slave, forced to clean her clothes and eat off the ground. But when an unfamiliar brand is found etched on Saito's hand from the summoning ritual, it is believed to be the mark of a powerful familiar named Gandalfr.
                   Wild, adventurous, and explosive, Zero no Tsukaima follows Saito as he comes to terms with his new life and as Louise proves that there is more to her than her nickname suggests.`,

    FamiliarZero2: `Revered as heroes for their role in defending Tristain, Louise Françoise and her familiar Saito Hiraga face heavy pressure to continue protecting the Kingdom. With an uneasy peace now established within Albion, the newly crowned Queen Henrietta must deal with a political struggle brewing on the horizon. To make matters worse, a new villain has begun plotting in the shadows against the Crown.
                    With the continuing threats that face the Kingdom, Louise and Saito are compelled to work together once more. No longer "Louise the Zero," the young mage's newfound aptitude for Void magic gives her enough power to wipe out an entire village; however, wielding these abilities comes with its share of challenges. As more conflicts arise, the idea of placing honor above oneself is put into question—regardless of their answer, their only choice is to see it through until the end.`,

    FamiliarZero3: `Following his brave sacrifice in the war against Albion, Saito Hiraga is knighted and treated as an aristocrat, something that proves difficult for Louise Françoise Le Blanc de La Vallière. With their relationship no longer defined as the mighty Void mage and clueless familiar, she wonders what exactly this means for them.
                    While venturing to a castle, Louise is ambushed by a powerful mage named Sheffield. Battling alone, the young mage nearly faces defeat until Saito makes his appearance. The mystical and unknown nature of Void magic seems to be at work in the battle, and Louise begins to believe in the possibility of another Void user. Moreover, she realizes that Saito's magical rune is fading, and so a new adventure begins as they search for the elf who revived Saito in the past. The relationship between former master and servant faces a new challenge as they work to restore the runes and redefine the bond which holds them together.`,

    FamiliarZero4: `Saito Hiraga and Louise Françoise Le Blanc de La Vallière go on the offensive after the events of Zero no Tsukaima: Princesses no Rondo. Together, they face off against King Joseph in the Holy City of Romalia with the help of two others who control the power of the "void." But in the midst of the many conflicts ahead of them, an ancient evil begins to stir in the shadows.
                    Will their close bonds blossom into something more or will they be shattered through the ever increasing difficulty of the tasks that they must undertake? Zero no Tsukaima F follows the story of Louise and Saito as they face their final challenges together.`,

    JahySama: `The great Jahy will not be defeated! Simultaneously combating starvation, the lack of A/C, and the unavoidable weakness of turning child-sized, Jahy—previously the second strongest being in the Dark Realm—is under great stress. If it weren't for the destruction of the mana crystal which used to power the Dark Realm, Jahy would still be living a life of power and luxury.
               And yet, at the moment, brawling with the landlady over rent is a recurring event for Jahy. Just to have a place to stay and food to eat, Jahy must work part-time. However, her immense pride will not allow her to live under such poor conditions for any longer than necessary. Vowing to reinstate the Dark Realm to its former glory, Jahy continues her journey to reassemble the mana crystal.`,

    GreatestDemonLord: `Having reached the pinnacle of human potential, Varvatos was so powerful that the rest of humankind began calling him the Demon Lord, both fearing and respecting his overwhelming influence. As a result, he felt alienated from his fellow humans, leading him to desire true companionship—an equal he could call a friend.
                        Hoping his fate will change in his next life, Varvatos decides to start anew and reincarnates three thousand years later as Ard Meteor, the son of a seemingly ordinary couple in a rural town. Unfortunately, he realizes that even after weakening himself, his strength still overshadows everyone in this era. Moreover, his lack of social skills bars him from achieving his goal of making friends. But worst of all, the repercussions of suddenly abandoning his former position have begun to bite him back in some of the most unimaginable ways possible.`,

    SenkoSan: `Like many hardworking members of the workforce, Kuroto Nakano is perpetually stressed out by his job. Still, since he lives alone, he must carry on to sustain himself. Little do humans like Kuroto know, this stress takes the form of darkness residing within a person's body and will bring one's life to ruin.
               Fox deities can see this darkness and have the duty to save people before it is too late. To help rid Kuroto of his stress, Senko-san, an eight hundred-year-old foxgirl, volunteers to take care of him, and will do everything she can to ease the tension in his weary soul.`,

    HiddenDungeon: `Despite his noble title, Noir Stalgia is at the bottom of the social hierarchy. Because of this, his fellow nobles oppress him and treat him like garbage. However, he possesses a rare yet powerful ability to communicate with the Great Sage, an oracle who grants Noir the answer to absolutely anything.
                    After failing to secure a job as a librarian, Noir decides to join the Hero Academy. He knows he must become stronger to enter the institution. The Great Sage advises him to explore a hidden dungeon deep within the mountains. There, Noir meets Olivia Servant, a beautiful yet enchained maiden trapped within the labyrinth. Olivia bestows upon Noir a set of ridiculously powerful skills that grants him virtually total control over reality. Naturally, there is a catch—every time Noir attempts to use his powers, his life points decrease, putting his life at risk. To replenish his energy, he must give in to worldly pleasures such as kissing his childhood friend!
                    With his newfound powers, Noir begins his journey as a student in the Hero Academy, meeting new acquaintances and helping them through the dire situations ahead.`,

    IrregularMagicHighSchool: `In the dawn of the 21st century, magic, long thought to be folklore and fairy tales, has become a systematized technology and is taught as a technical skill. In First High School, the institution for magicians, students are segregated into two groups based on their entrance exam scores: "Blooms," those who receive high scores, are assigned to the First Course, while "Weeds" are reserve students assigned to the Second Course.
                               Mahouka Koukou no Rettousei follows the siblings, Tatsuya and Miyuki Shiba, who are enrolled in First High School. Upon taking the exam, the prodigious Miyuki is placed in the First Course, while Tatsuya is relegated to the Second Course. Though his practical test scores and status as a "Weed" show him to be magically inept, he possesses extraordinary technical knowledge, physical combat capabilities, and unique magic techniques—making Tatsuya the irregular at a magical high school.`,

    MisfitOfDemonKingAcademy: `In the distant past, a war between humans and demons brought about widespread chaos and bloodshed. To put an end to this seemingly endless conflict, Demon King Anos Voldigoad willingly sacrificed his life, hoping to be reborn in a peaceful future.
                               In preparation for their king's return, the demon race created the Demon King Academy, an elite institution tasked with determining Anos' identity when he reawakens. He reincarnates two millennia later, but to his surprise, he soon learns that the level of magic in the world has drastically waned during his absence. Moreover, when he enrolls at the academy to reclaim his rightful title, he finds out that demonkind remembers him differently. His personality, his deeds, and even his legacy are all falsified—masked beneath the name of an impostor. This "lack" of common knowledge renders him the academy's outlier—a misfit never before seen in history.
                               Despite these drawbacks, Anos remains unfazed. As he sets out to uncover those altering his glorious past, he takes it upon himself to make his descendants recognize that their ruler has finally returned.`,

    ShieldHero: `The Four Cardinal Heroes are a group of ordinary men from modern-day Japan summoned to the kingdom of Melromarc to become its saviors. Melromarc is a country plagued by the Waves of Catastrophe that have repeatedly ravaged the land and brought disaster to its citizens for centuries. The four heroes are respectively bestowed a sword, spear, bow, and shield to vanquish these Waves. Naofumi Iwatani, an otaku, becomes cursed with the fate of being the "Shield Hero." Armed with only a measly shield, Naofumi is belittled and ridiculed by his fellow heroes and the kingdom's people due to his weak offensive capabilities and lackluster personality.
                 When the heroes are provided with resources and comrades to train with, Naofumi sets out with the only person willing to train alongside him, Malty Melromarc. He is soon betrayed by her, however, and becomes falsely accused of taking advantage of her. Naofumi then becomes heavily discriminated against and hated by the people of Melromarc for something he didn't do. With a raging storm of hurt and mistrust in his heart, Naofumi begins his journey of strengthening himself and his reputation. Further along however, the difficulty of being on his own sets in, so Naofumi buys a demi-human slave on the verge of death named Raphtalia to accompany him on his travels.
                 As the Waves approach the kingdom, Naofumi and Raphtalia must fight for the survival of the kingdom and protect the people of Melromarc from their ill-fated future.`,

    ShieldHero2: `With another Wave happening in a week, Naofumi Iwatani and his party have no time to waste. However, when bat familiars raid Lurolona Village and the Wave countdown comes to a halt, the Four Cardinal Heroes reconvene with the queen, Mirelia Q Melromarc, for a quick briefing. The queen presumes that the odd occurrences are linked to the Spirit Tortoise—a threatening creature that has awakened from its slumber, back to cause havoc once again. A plan to put the Spirit Tortoise to rest is devised—but out of the four men, only the cursed Shield Hero agrees to help.`,

    StrongestSage: `At birth, mages randomly acquire one of the four "crests" that represents the extent of their magical capability. Equipped with a crest specializing in creation, a man named Gaius reached the ceiling of his potential, becoming known as the world's strongest sage. Despite his overwhelming power, he is unsatisfied with his abilities and desires to possess the mark suitable for close combat. Knowing that a person's crest is unchangeable, Gaius decides to reincarnate far into the future, hoping to alter his fate.
                    Thousands of years later, Gaius is reborn as Mathias Hildesheimer, successfully obtaining his long-coveted crest. However, he is surprised to learn that in these times, magic has vastly waned, and the techniques that were once widely used are now nothing more than just a speck of legend. Moreover, the crest that he painstakingly strived to attain is now considered the weakest—merely dubbed the "Crest of Failure."
                    Nevertheless, Mathias naturally exceeds all expectations. He enrolls into the royal capital's Second Academy, acing every trial that comes his way. But soon after, Mathias discovers the dark truth behind humanity's downfall into magical mediocrity—demons—and endeavors to remedy the consequence of his millennia-long absence once and for all.`,

    WorldFinestAssassin: `The world's greatest assassin had sworn lifelong allegiance to the organization that raised him. However, despite his loyalty, that very same organization takes action to silence him, ultimately leading to his demise. Drowning in frustration and regrets he can no longer suppress, he finds himself in an audience with a goddess attracted by his exceptional skills. The goddess offers him reincarnation into a magnificent world of swords and magic so he can perform a crucial mission: prevent that world's destruction by slaying its hero.
                          Accepting the goddess' request, he is reborn as Lugh Tuatha Dé, the son of a noble family of assassins serving the Alvan Kingdom. Under the guidance of his father, Lugh learns new assassination techniques that significantly differ from the cold-blooded and unsympathetic killing style of his previous life. Furthermore, his other talents bloom, allowing him to meet new allies and acquaintances. Even so, Lugh knows that his efforts are far from adequate, because a monumental adversary such as the hero can only be defeated with perfection.`,

    ArtClubHasAProblem: `Mizuki Usami is a passionate member of her school's art club, but the club has a problem—Usami is the only member who takes her craft seriously! The lazy club president constantly sleeps through activities and Collette hasn't regularly attended club activities in quite some time. Uchimaki Subaru, despite being an exceptional artist who could win an award if he tried, is obsessed with drawing the perfect 2D wife.
                         Light-hearted and comedic in tone, Kono Bijutsubu ni wa Mondai ga Aru! follows Usami as she struggles to do art club-like activities, often obstructed by her motley crew of good-for-nothings and her distracting crush on Subaru.`,

    ThreeLeavesThreeColors: `Having gone from pampered to poor after the bankruptcy of her father's company, Youko Nishikawa struggles to drop her princess-like persona and make friends at her all-girls high school. One day, while eating alone in a nearby forest, she has a chance encounter with Futaba Odagiri, the super-energetic transfer student, and Teru Hayama, an innocent-looking girl with a surprisingly direct and sometimes mean personality. Despite their differing personalities, the three girls who all have the kanji for "leaf" in their name begin an unlikely friendship as they try to navigate through an amusing and spontaneous adventure known as high school life.
                             Sansha Sanyou is a cheerful, cute series revolving around three close but very different friends as they try to balance the everyday challenges that school and adolescence have to offer.`,

    TodaysMenuForEmiyaFamily: `With the threat of the Holy Grail War no longer looming over Fuyuki City, its inhabitants can finally enjoy a time of peace. Now that all of the Masters and Servants have adjusted to their new mundane lives, Shirou has taken it upon himself to cook for his household and show Saber the wonders of modern cuisine. Every day, he ventures into the marketplace to see what kind of different meals he can cook up with unique ingredients and a limited budget. However, his legendary skills often attract uninvited guests from all over the city, so there is never a dull moment at dinner with the Emiya family.
                               As his guests entertain themselves in the living room, Shirou walks through the step-by-step process of creating some of his favorite meals. With delicacies such as his savory New Year soba with shrimp tempura, steamy foil-baked salmon, and cheesy bamboo shoot gratin, everything is up for grabs on his menu. Itadakimasu!`,

    TomoChan: `Childhood friends Tomo Aizawa and Junichirou "Jun" Kubota do everything together, whether it be training or just enjoying a fun day out. Anyone would think that these two are best friends for life. The only issue is that the tomboyish Tomo is in love with Jun, but he regards her like a brother.
               At the start of their first year of high school, Tomo confesses her feelings to Jun. However, her rough mannerisms and lack of hesitance to throw a punch do nothing to sway Jun's heart. Realizing that he will remain indifferent to her affections unless she does something about it, Tomo must find a way to knock some sense into Jun and open his eyes to what is right in front of him.`,

    Tonikawa: `Nasa Yuzaki is determined to leave his name in the history books. Ranking first in the national mock exam and aiming for a distinguished high school, he is certain that he has his whole life mapped out. However, fate is a fickle mistress. On his way home one snowy evening, Nasa's eyes fall upon a peerless beauty across the street. Bewitched, Nasa tries to approach her—only to get blindsided by an oncoming truck.
               Thankfully, his life is spared due to the girl's swift action. Bleeding by the side of an ambulance, he watches as the girl walks away under the moonlight—reminiscent of Princess Kaguya leaving for the moon. Refusing to let this chance meeting end, he forces his crippled body to chase after her and asks her out. Surprised by his foolhardiness and pure resolve, the girl accepts his confession under a single condition: they can only be together if he marries her!`,

    Tonikawa2: `In the wake of their first home burning down, Nasa and Tsukasa Yuzaki are seeking temporary shelter at the Arisugawas' bathhouse. Though they have only been married for a short time, their relationship has only become sweeter by the day. Nasa is determined to spend as much time with his wife as possible, basking in the happiness of their marriage.
                The newlyweds find new ways to explore their relationship. From adopting a cat, going to an amusement park, and even watching an impromptu romantic comedy featuring Nasa's former teacher, every day is a new experience. But while Tsukasa continues to meet the people in Nasa's life, Nasa has yet to meet more of Tsukasa's family. Though they appear to be the picture-perfect couple to everyone around them, Nasa begins to wonder if he will ever learn more about his wife's mysterious past.`,

    Toradora: `Ryuuji Takasu is a gentle high school student with a love for housework; but in contrast to his kind nature, he has an intimidating face that often gets him labeled as a delinquent. On the other hand is Taiga Aisaka, a small, doll-like student, who is anything but a cute and fragile girl. Equipped with a wooden katana and feisty personality, Taiga is known throughout the school as the "Palmtop Tiger."
               One day, an embarrassing mistake causes the two students to cross paths. Ryuuji discovers that Taiga actually has a sweet side: she has a crush on the popular vice president, Yuusaku Kitamura, who happens to be his best friend. But things only get crazier when Ryuuji reveals that he has a crush on Minori Kushieda—Taiga's best friend!
               Toradora! is a romantic comedy that follows this odd duo as they embark on a quest to help each other with their respective crushes, forming an unlikely alliance in the process.`,

    TsuredureChildren: `Young love—it takes many unique and fascinating forms that flourish as children begin to mature into adults. From being unable to confess to not knowing what real love actually feels like, various obstacles can arise when learning about romantic attraction for the first time. But underneath all that, young love is something truly beautiful to behold, leading to brand new experiences for those young and in love.
                        Tsurezure Children depicts various scenarios of young love coming to fruition, along with the struggles and joys that it entails.`,

    TwinStarExorcists: `Magano, a parallel realm filled with monsters known as "Kegare," is a place where exorcists deal with all impurities. Benio Adashino is a prodigy exorcist who is recognized for her strength and is summoned to Tokyo by the Exorcist Union. On her way, she plummets into the arms of Rokuro Enmadou, a young exorcist with a troubled past.
                        But the impurities of Magano do not rest. When these two exorcists witness a couple of children stolen by a Kegare, Benio rushes to save them, dragging Rokuro along with her into Magano. Engaged in a fight she is on the verge of being defeated in, Benio is saved by Rokuro, revealing himself capable of being her rival in talent.
                        Sousei no Onmyouji tells the story of two talented exorcists who are destined to become the "Twin Star Exorcists" and the prophesised parents of the Miko—the reincarnation of Abe no Seimei—who will cleanse the world of all impurities.`,


}