import { Anime } from "@/lib/Anime";
import { Synopsis } from "./fSynopsis";

export const f_anime = [
    new Anime(
        "Fate/Grand Carnival",
        "",
        "https://cdn.myanimelist.net/images/anime/1239/117596.jpg",
        4,
        "PG-13 - Teens 13 or older",
        Synopsis.FateGrandCarnival,
        [""],
        "OVA",
        "Dec 31 2020 to Oct 13 2021",
        "Winter 2020",
        "Lerche",
        "Game",
        ["Comedy", "Fantasy", "Supernatural"],
        ["Parody"],
        "15 minutes",
    ),
    new Anime(
        "Fate/Kaleid liner Prisma Illya",
        "Fate/kaleid liner Prisma☆Illya",
        "https://cdn.myanimelist.net/images/anime/1773/121542.jpg",
        10,
        "PG-13 - Teens 13 or older",
        Synopsis.FateKaleidLiner,
        [""],
        "TV",
        "Jul 13 2013 to Sep 14 2013",
        "Summer 2013",
        "SILVER LINK",
        "Manga",
        ["Action", "Comedy", "Fantasy"],
        ["Mahou Shoujo"],
        "24 minutes",
    ),
    new Anime(
        "Fate/Kaleid Liner Prisma Illya 2Wei!",
        "Fate/kaleid liner Prisma☆Illya 2wei!",
        "https://cdn.myanimelist.net/images/anime/12/64175.jpg",
        10,
        "PG-13 - Teens 13 or older",
        Synopsis.FateKaleidLiner2,
        [""],
        "TV",
        "Jul 10 2014 to Sep 11 2014",
        "Summer 2014",
        "SILVER LINK",
        "Manga",
        ["Action", "Comedy", "Fantasy"],
        ["Mahou Shoujo"],
        "23 minutes",
    ),
    new Anime(
        "Fate/Kaleid Liner Prisma Illya 2Wei Herz!",
        "Fate/kaleid liner Prisma☆Illya 2wei Herz!",
        "https://cdn.myanimelist.net/images/anime/7/75297.jpg",
        10,
        "PG-13 - Teens 13 or older",
        Synopsis.FateKaleidLiner2_5,
        [""],
        "TV",
        "Jul 25 2015 to Sep 26 2015",
        "Summer 2015",
        "SILVER LINK",
        "Manga",
        ["Action", "Comedy", "Ecchi"],
        ["Mahou Shoujo"],
        "23 minutes",
    ),
    new Anime(
        "Fate/kaleid liner Prisma Illya 3rei!!",
        "Fate/kaleid liner Prisma☆Illya 3rei!!",
        "https://cdn.myanimelist.net/images/anime/7/80834.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.FateKaleidLiner3,
        [""],
        "TV",
        "Jul 6 2016 to Sep 21 2016",
        "Summer 2016",
        "SILVER LINK",
        "Manga",
        ["Action", "Comedy", "Fantasy"],
        ["Mahou Shoujo"],
        "24 minutes",
    ),
    new Anime(
        "Food Wars! Shokugeki no Soma",
        "Shokugeki no Souma",
        "https://cdn.myanimelist.net/images/anime/3/72943.jpg",
        24,
        "PG-13 - Teens 13 or older",
        Synopsis.FoodWars,
        [""],
        "TV",
        "Apr 4 2015 to Sep 26 2015",
        "Spring 2015",
        "J.C. Staff",
        "Manga",
        ["Gourmet", "Ecchi"],
        ["School"],
        "25 minutes",
    ),
    new Anime(
        "Food Wars! The Second Plate",
        "Shokugeki no Souma: Ni no Sara",
        "https://cdn.myanimelist.net/images/anime/8/79353.jpg",
        13,
        "PG-13 - Teens 13 or older",
        Synopsis.FoodWars2,
        [""],
        "TV",
        "Jul 2 2016 to Sep 24 2016",
        "Summer 2016",
        "J.C. Staff",
        "Manga",
        ["Gourmet", "Ecchi"],
        ["School"],
        "24 minutes",
    ),
    new Anime(
        "Food Wars! The Third Plate",
        "Shokugeki no Souma: San no Sara",
        "https://cdn.myanimelist.net/images/anime/3/88434.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.FoodWars3,
        [""],
        "TV",
        "Oct 4 2017 to Dec 20 2017",
        "Fall 2017",
        "J.C. Staff",
        "Manga",
        ["Gourmet", "Ecchi"],
        ["School"],
        "24 minutes",
    ),
    new Anime(
        "Food Wars! The Third Plate: Totsuki Train Arc",
        "Shokugeki no Souma: San no Sara - Tootsuki Ressha-hen",
        "https://cdn.myanimelist.net/images/anime/1604/93531.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.FoodWars3_5,
        [""],
        "TV",
        "Apr 9 2018 to Jun 25 2018",
        "Spring 2018",
        "J.C. Staff",
        "Manga",
        ["Gourmet", "Ecchi"],
        ["School"],
        "24 minutes",
    ),
    new Anime(
        "Food Wars! The Fourth Plate",
        "Shokugeki no Souma: Shin no Sara",
        "https://cdn.myanimelist.net/images/anime/1072/110175.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.FoodWars4,
        [""],
        "TV",
        "Oct 12 2019 to Dec 28 2019",
        "Fall 2019",
        "J.C. Staff",
        "Manga",
        ["Gourmet", "Ecchi"],
        ["School"],
        "24 minutes",
    ),
    new Anime(
        "Food Wars! The Fifth Plate",
        "Shokugeki no Souma: Gou no Sara",
        "https://cdn.myanimelist.net/images/anime/1756/108000.jpg",
        13,
        "PG-13 - Teens 13 or older",
        Synopsis.FoodWars5,
        [""],
        "TV",
        "Apr 11 2020 to Sep 26 2020",
        "Spring 2020",
        "J.C. Staff",
        "Manga",
        ["Gourmet", "Ecchi"],
        ["School"],
        "23 minutes",
    ),
    new Anime(
        "Fullmetal Alchemist",
        "",
        "https://cdn.myanimelist.net/images/anime/10/75815.jpg",
        51,
        "R - 17+ (violence & profanity)",
        Synopsis.FullmetalAlchemist,
        [""],
        "TV",
        "Oct 4 2003 to Oct 2 2004",
        "Fall 2003",
        "Bones",
        "Manga",
        ["Action", "Adventure", "Award Winning", "Drama", "Fantasy"],
        ["Military"],
        "24 minutes",
    ),
    new Anime(
        "Fullmetal Alchemist: Brotherhood",
        "",
        "https://cdn.myanimelist.net/images/anime/1208/94745.jpg",
        64,
        "R - 17+ (violence & profanity)",
        Synopsis.FullmetalAlchemistBrotherhood,
        [""],
        "TV",
        "Apr 5 2009 to Jul 4 2010",
        "Spring 2009",
        "Bones",
        "Manga",
        ["Action", "Adventure", "Drama", "Fantasy"],
        ["Military"],
        "24 minutes",
    ),
]