export const Synopsis = {

    FateGrandCarnival: `The first episode of "season" one was pre-aired on the Fate Project New Year's Eve TV Special 2020 program.`,

    FateKaleidLiner: `Mage's Association members Rin Toosaka and Luviagelita "Luvia" Edelfelt are tasked with finding and retrieving seven Class Cards, medieval artifacts containing the life essence of legendary Heroic Spirits. To aid them in their mission, they are granted the power of Ruby and Sapphire, two sentient Kaleidosticks that would enable them to transform themselves into magical girls and drastically increase their abilities. However, the two mages are on anything but good terms, prompting the Kaleidosticks to abandon them in search for new masters. They stumble upon two young schoolgirls—Illyasviel von Einzbern and Miyu—and quickly convince them to form a contract. With their new powers and responsibilities, Illya and Miyu set forth to collect all the Class Cards.`,

    FateKaleidLiner2: `Another lovely summer goes by for Illyasviel von Einzbern. Taking a break from her magical girl duties, she enjoys her time off after collecting the Class Cards with her best friend Miyu Edelfelt.
                       However, her break comes to an abrupt end when she and Miyu are abducted by Rin Toosaka and Luviagelita Edelfelt, while out with her friends. The magical girls learn that their work is far from over, as Clock Tower informs them that the out of control mana thought to have been sealed continues to be dispersing throughout Fuyuki City. After heading to the origin point of the out of control mana, Illya and Miyu are tasked with solving the anomaly.
                       But after casting their spell, Illyasviel discovers that she's split into two people! As this mysterious new form darts off, she can only wonder: what is to come from the existence of her dopplegänger, running amok in the unsuspecting town?`,

    FateKaleidLiner2_5: `Based on the Fate/Kaleid Liner Prisma☆Illya 2wei! manga by Hiroshi Hiroyama, which is a spin-off of the Fate/stay night erotic visual novel by Type-Moon.`,

    FateKaleidLiner3: `Waking up to find herself in a parallel version of Fuyuki City, Illyasviel "Illya" von Einzbern is lost and alone. She discovers her home in ruins, with a massive crater lying in the center of her hometown. With snow falling in the middle of summer, confusion consumes the young elementary schooler, who has no knowledge of where her friends or her wand Ruby may be.
                       Making it to the remains of her house, she is suddenly tackled by an amnesiac girl. Wearing a gym uniform as the icy temperature sets in, the mysterious girl has no idea of where she is or why she showed up. However, this stranger, known as Tanaka, apparently has information about the location of Rin Toosaka, Miyu Edelfelt, and the rest of Illya's missing friends.
                       Fleeing from agents of the Ainsworth family⁠—those in control of this parallel realm—where will these two end up, and how will Illya restore the present back to the world she once knew?`,

    FoodWars: `Souma Yukihira has been cooking alongside his father Jouichirou for as long as he can remember. As a sous chef at his father's restaurant, he has spent years developing his culinary expertise and inventing new dishes to amaze their customers. He aspires to exceed his father's skill and take over the restaurant one day, but he is shocked to learn that Jouichirou is closing up the shop to take a job in New York.
               Rather than tagging along with his father, Souma finds himself enrolling at the prestigious Tootsuki Culinary Academy, where only 10 percent of its students end up graduating. The school is famous for its "Shokugeki"—intense cooking competitions between students often used to settle debates and arguments. Jouichirou tells Souma that to surpass him and survive the next three years at Tootsuki and graduate there.
               The academy's brutal curriculum and fiercely competitive student body await the young chef, who must learn to navigate the treacherous environment if he wants to stand a chance at realizing his dreams. But is skill alone enough to let him rise to the top?`,

    FoodWars2: `The qualifiers of the Autumn Elections are now over, and only eight talented chefs remain. Now, they face off in one-on-one food wars, each with their own unique themes. Met with both new judges and new opponents all with their own specialties, Souma must stay on his toes if he hopes to make it to the top of both the Autumn Elections and Tootsuki Culinary Academy.`,

    FoodWars3: `The Moon Festival is Tootsuki Academy's annual gourmet gala, where students compete against each other to earn the most profit through selling their cuisine of choice. But for Souma Yukihira, it is also his first opportunity to challenge the Elite Ten, the supreme council that rules over the academy.
                However, this is only the beginning of Souma's war against the Elite Ten; a nefarious plot is underway that will provide Souma with the challenge he desires but will also shake the very foundations of Tootsuki Academy itself.`,

    FoodWars3_5: `A dark age of cooking befalls Tootsuki Culinary Academy. With the Elite Ten's devastating coup d'état, Azami Nakiri is now the director of the prestigious school. Students must now conform to Azami's ideology of "true gourmet food" and are forbidden to express creativity, or else face expulsion.
                  However, Souma Yukihira and the members of the Polar Star Dormitory refuse to accept these changes. Aided by other rebellious first-years, including the tenth seat, Erina Nakiri, Souma and his allies band together to fight off supporters of Azami's regime. But corrupt instructors and the menacing Central organization stand in their way, and so they must work together, harder than ever before, to survive every underhanded plot designed to banish them from the school.`,

    FoodWars4: `At Tootsuki Culinary Academy, a heated eight-on-eight Shokugeki known as the Régiment de Cuisine rages on between Central and the rebel forces led by Souma Yukihira and Erina Nakiri. Though they won a stunning perfect victory in the first bout, the rebels face an uphill battle ahead, as they must now face off against the rest of the Elite Ten Council. With the future of Tootsuki at stake, Souma and Erina must push far beyond the limits of their abilities, using everything they learned from their mentors and ultimately drawing from their experiences cooking together as friends.`,

    FoodWars5: `Thanks to Souma Yukihira, Erina Nakiri, and the rebel forces overthrowing the regime of Azami Nakiri—the previous school director—and the former Elite Ten, Tootsuki Culinary Academy is back in order. However, its students have one more great battle ahead of them: the BLUE, a competition where young chefs seeking world-class fame compete. Faced with new trials and rivals, Souma and his friends will fight to conquer the BLUE and to defeat Asahi Saiba, the leader of an underworld organization of chefs known as Noir, who once defeated Souma and his father in a Shokugeki.`,

    Frieren: `During their decade-long quest to defeat the Demon King, the members of the hero's party—Himmel himself, the priest Heiter, the dwarf warrior Eisen, and the elven mage Frieren—forge bonds through adventures and battles, creating unforgettable precious memories for most of them.
    However, the time that Frieren spends with her comrades is equivalent to merely a fraction of her life, which has lasted over a thousand years. When the party disbands after their victory, Frieren casually returns to her "usual" routine of collecting spells across the continent. Due to her different sense of time, she seemingly holds no strong feelings toward the experiences she went through.
    As the years pass, Frieren gradually realizes how her days in the hero's party truly impacted her. Witnessing the deaths of two of her former companions, Frieren begins to regret having taken their presence for granted; she vows to better understand humans and create real personal connections. Although the story of that once memorable journey has long ended, a new tale is about to begin.`,

    FullmetalAlchemist: `Edward Elric, a young, brilliant alchemist, has lost much in his twelve-year life: when he and his brother Alphonse try to resurrect their dead mother through the forbidden act of human transmutation, Edward loses his brother as well as two of his limbs. With his supreme alchemy skills, Edward binds Alphonse's soul to a large suit of armor.
                         A year later, Edward, now promoted to the fullmetal alchemist of the state, embarks on a journey with his younger brother to obtain the Philosopher's Stone. The fabled mythical object is rumored to be capable of amplifying an alchemist's abilities by leaps and bounds, thus allowing them to override the fundamental law of alchemy: to gain something, an alchemist must sacrifice something of equal value. Edward hopes to draw into the military's resources to find the fabled stone and restore his and Alphonse's bodies to normal. However, the Elric brothers soon discover that there is more to the legendary stone than meets the eye, as they are led to the epicenter of a far darker battle than they could have ever imagined.`,

    FullmetalAlchemistBrotherhood: `After a horrific alchemy experiment goes wrong in the Elric household, brothers Edward and Alphonse are left in a catastrophic new reality. Ignoring the alchemical principle banning human transmutation, the boys attempted to bring their recently deceased mother back to life. Instead, they suffered brutal personal loss: Alphonse's body disintegrated while Edward lost a leg and then sacrificed an arm to keep Alphonse's soul in the physical realm by binding it to a hulking suit of armor.
                                    The brothers are rescued by their neighbor Pinako Rockbell and her granddaughter Winry. Known as a bio-mechanical engineering prodigy, Winry creates prosthetic limbs for Edward by utilizing "automail," a tough, versatile metal used in robots and combat armor. After years of training, the Elric brothers set off on a quest to restore their bodies by locating the Philosopher's Stone—a powerful gem that allows an alchemist to defy the traditional laws of Equivalent Exchange.
                                    As Edward becomes an infamous alchemist and gains the nickname "Fullmetal," the boys' journey embroils them in a growing conspiracy that threatens the fate of the world.`,


}