import { Anime } from "@/lib/class/Anime";
import { Synopsis } from "./ySynopsis";

export const y_anime = [
    new Anime(
        "Yu-Gi-Oh! Arc-V",
        "Yu☆Gi☆Oh! Arc-V",
        "https://cdn.myanimelist.net/images/anime/10/62939.jpg",
        148,
        "PG-13 - Teens 13 or older",
        Synopsis.YugiohArcV,
        [""],
        "TV",
        "Apr 6 2014 to Mar 26 2017",
        "Spring 2014",
        "Gallop",
        "Manga",
        ["Action", "Fantasy"],
        ["Strategy Game"],
        "24 minutes",
    ),
    new Anime(
        "Yurumates 3D",
        "",
        "https://cdn.myanimelist.net/images/anime/3/36705.jpg",
        13,
        "PG-13 - Teens 13 or older",
        Synopsis.Yurumates,
        [""],
        "TV",
        "Apr 3 2012 to Jun 26 2012",
        "Spring 2012",
        "C2C",
        "4-koma manga",
        ["Comedy", "Slice of Life"],
        [""],
        "3 minutes",
    ),
    new Anime(
        "Yuri is My Job!",
        "Watashi no Yuri wa Oshigoto desu!",
        "https://cdn.myanimelist.net/images/anime/1708/133360.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.YuriIsMyJob,
        [""],
        "TV",
        "Apr 6 2023 to Jun 22 2023",
        "Spring 2023",
        "Passione, Studio Lings",
        "Manga",
        ["Comedy", "Girls Love"],
        ["Workplace"],
        "23 minutes",
    ),
    new Anime(
        "YuruYuri: Happy Go Lily",
        "Yuru Yuri",
        "https://cdn.myanimelist.net/images/anime/12/75173.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.YuruYuri,
        [""],
        "TV",
        "Jul 5 2011 to Sep 20 2011",
        "Summer 2011",
        "Doga Kobo",
        "Manga",
        ["Award Winning", "Comedy", "Girls Love"],
        ["CGDCT", "Gag Humor", "School"],
        "23 minutes",
    ),
    new Anime(
        "YuruYuri: Happy Go Lily ♪♪",
        "Yuru Yuri♪♪",
        "https://cdn.myanimelist.net/images/anime/8/75174.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.YuruYuri2,
        [""],
        "TV",
        "Jul 3 2012 to Sep 18 2012",
        "Summer 2012",
        "Doga Kobo",
        "Manga",
        ["Comedy", "Girls Love"],
        ["CGDCT", "Gag Humor", "School"],
        "23 minutes",
    ),
    new Anime(
        "Yuru Yuri San☆Hai!",
        "",
        "https://cdn.myanimelist.net/images/anime/7/76667.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.YuruYuri3,
        [""],
        "TV",
        "Oct 6 2015 to Dec 22 2015",
        "Fall 2015",
        "TYO Animations",
        "Manga",
        ["Comedy", "Girls Love"],
        ["CGDCT", "Gag Humor", "School"],
        "23 minutes",
    ),
    new Anime(
        "Yuru Yuri,",
        "",
        "https://cdn.myanimelist.net/images/anime/1138/99547.jpg",
        1,
        "PG-13 - Teens 13 or older",
        Synopsis.YuruYuriSpecial,
        [""],
        "OVA",
        "Sep 18 2019",
        "Fall 2019",
        "Lay-duce",
        "Manga",
        ["Comedy", "Girls Love"],
        ["CGDCT", "Gag Humor", "School"],
        "31 minutes",
    ),
]