export const Synopsis = {
    YugiohArcV: `Action Duels, which allow duelists to soar and swing alongside their Duel Monsters, are taking the world by storm. Due to an evolutionary breakthrough, the "Solid Vision" system is now able to provide Duel Monsters with mass.
                 Yuuya Sakaki is Yuusho Sakaki's son, the latter being the founder of You Show Duel School in Miami City. Yuusho insists that duels are not a tool of war, but rather are to bring smiles to people and thus introduced the concept of Entertainment Dueling. However, at the height of his fame, Yuusho disappears and fails to attend his duel with Strong Ishijima, the Action Duel champion. Although scarred by this sudden leave, Yuuya vows to become an Entertainment Duelist like his father.
                 Several years later, in the midst of a battle with Strong Ishijima, Yuuya's desperation to win brings forth a miracle. His pendant begins glowing, turning his cards into Pendulum Cards, which enables him to perform a Pendulum Summon—a summoning method unknown to the world and himself—gaining him fame overnight. As a result, Reiji Akaba, CEO of Leo Corporation and founder of the elite Leo Duel School, starts producing new Pendulum Cards to incorporate Pendulum Summoning into the system. Thus, the mysteries that surround Pendulum Summoning and Yuuya's father start to unravel, and Yuuya learns bit by bit what it takes to become an Entertainment Duelist.`,

    Yurumates: `Yurume, an 18-year-old "ronin" and recent high school graduate, has high hopes of being accepted and attending Tokyo University. She moves into an apartment complex, the Maison du Wish, located on the outskirts of Tokyo where other ronins living there are studying for upcoming college acceptance exams.`,

    YuriIsMyJob: `Hime Shiraki appears to have it all: an angelic voice, an innocent personality, and an adorable face that enamors all onlookers. However, her cuteness is all a lie—it is purely an act to achieve her self-centered goal of marrying a rich suitor. Though she often plays up her innocence to gain favor from those around her, Hime's facade does not absolve her of responsibility when an accident leaves Mai Koshiba injured.
                  Learning that Mai is the manager of Café Liebe—a cafe themed as an all-girls academy—Hime is coerced into taking up a part-time position until Mai recovers. However, Hime's facade cannot cover up her shortcomings at being a waitress, earning her the ire of one of her coworkers, Mitsuki Yano, the elegant "onee-sama" who often berates Hime over her mistakes. As Hime struggles to adjust to her new job in addition to Mitsuki's unrelenting hostility, her real personality begins seeping through the cracks.`,

    YuruYuri: `After a year in grade school without her childhood friends, first year student Akari Akaza is finally reunited with second years Yui Funami and Kyouko Toshinou at their all-girls' middle school. During the duo's first year, Yui and Kyouko formed the "Amusement Club" which occupies the now nonexistent Tea Club's room. Shortly after Akari joins, one of her fellow classmates, Chinatsu Yoshikawa, pays the trio a visit under the impression that they are the Tea Club; it is only once the three girls explain that the Tea Club has been disbanded that they can convince Chinatsu to join the Amusement Club—a group with no purpose other than to provide entertainment for its members.
               Based on the slice-of-life manga by Namori, Yuru Yuri is an eccentric comedy about a group of girls who spend their spare time drinking tea and fawning over each other, all while completely failing to even notice the supposed main character Akari amongst them.`,

    YuruYuri2: `The girls of the Amusement Club return in Yuru Yuri♪♪, finding new ways to make passing time even more enjoyable. Their members consist of the always energetic Kyouko Toshinou; calm and sensible Yui Funami; polite but often overlooked Akari Akaza; and Chinatsu Yoshikawa, who stumbled upon the others while looking for the Tea Ceremony Club. Together they are the Amusement Club, which has the deceptively simple task of keeping its members entertained.
                Along with the Student Council and the odd family member, they strive to enjoy their youth to the fullest. Whether it's a trip to a hot spring or finishing overdue homework, their lives are never dull, and they will always find an excuse to spend time together.`,

    YuruYuri3: `The members of the Amusement Club are back with more of Kyouko Toshinou's antics, Chinatsu Yoshikawa's schemes, Yui Funami's retorts, and Akari Akaza's small social presence as they strive to make each day as fun as the last! Whether the activity is an arm wrestling contest or making pancakes together, the group of entertainment-seekers are sure to give it their all.
                The club members are often joined by their friends in the Student Council, who know how to have a good time as well. While it can get a little chaotic when all eight girls get together, it sure doesn't stop them from meeting up and having fun!`,

    YuruYuriSpecial: `Akari Akaza, Chinatsu Yoshikawa, Kyouko Toshinou, and Yui Funami return to commemorate an exciting occasion! Despite their initial bizarre celebration ideas, they decide to hold a party at their Amusement Club room. With the help of friends from the Student Council, they start preparing for the big day—with a surprise planned for a special someone.
                      Join the girls as they work together to create an enjoyable and memorable party, all the while interacting with one another with their cute and unique quirks.`,


}