import { Anime } from "@/lib/Anime";
import { Synopsis } from "./lSynopsis";

export const l_anime = [
    new Anime(
        "Laid-Back Camp",
        "Yuru Camp△",
        "https://cdn.myanimelist.net/images/anime/4/89877.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.YuruCamp,
        [""],
        "TV",
        "Jan 4 2018 to Mar 22 2018",
        "Winter 2018",
        "C-Station",
        "Manga",
        ["Slice of Life"],
        ["CGDCT", "Iyashikei"],
        "23 minutes",
    ),
    new Anime(
        "Laid-Back Camp Season 2",
        "Yuru Camp△ Season 2",
        "https://cdn.myanimelist.net/images/anime/1255/110636.jpg",
        13,
        "PG-13 - Teens 13 or older",
        Synopsis.YuruCamp2,
        [""],
        "TV",
        "Jan 7 2021 to Apr 1 2021",
        "Winter 2021",
        "C-Station",
        "Manga",
        ["Slice of Life"],
        ["CGDCT", "Iyashikei"],
        "23 minutes",
    ),
    new Anime(
        "Life With an Ordinary Guy Who Reincarnated Into a Total Fantasy Knockout",
        "Fantasy Bishoujo Juniku Ojisan to",
        "https://cdn.myanimelist.net/images/anime/1430/120065.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.FantasyBishoujo,
        [""],
        "TV",
        "Jan 12 2022 to Mar 30 2022",
        "Winter 2022",
        "OLM",
        "Web manga",
        ["Adventure", "Comedy", "Fantasy"],
        ["Isekai", "Magical Sex Shift", "Parody"],
        "23 minutes",
    ),
    new Anime(
        "Little Witch Academia",
        "",
        "https://cdn.myanimelist.net/images/anime/13/83934.jpg",
        25,
        "G - All Ages",
        Synopsis.LittleWitchAcademia,
        [""],
        "TV",
        "Jan 9 2017 to Jun 26 2017",
        "Winter 2017",
        "Trigger",
        "Original",
        ["Adventure", "Comedy", "Fantasy"],
        ["School"],
        "24 minutes",
    ),
    new Anime(
        "Love, Chunibyo & Other Delusions!",
        "Chuunibyou demo Koi ga Shitai!",
        "https://cdn.myanimelist.net/images/anime/1905/142840.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Chuunibyou,
        [""],
        "TV",
        "Oct 4 2012 to Dec 20 2012",
        "Fall 2012",
        "Kyoto Animation",
        "Light novel",
        ["Comedy", "Romance"],
        ["School"],
        "24 minutes",
    ),
    new Anime(
        "Love, Chunibyo & Other Delusions!: Heart Throb",
        "Chuunibyou demo Koi ga Shitai! Ren",
        "https://cdn.myanimelist.net/images/anime/7/56643.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Chuunibyou2,
        [""],
        "TV",
        "Jan 9 2014 to Mar 27 2014",
        "Winter 2014",
        "Kyoto Animation",
        "Light novel",
        ["Comedy", "Romance"],
        ["School"],
        "23 minutes",
    ),
    new Anime(
        "Love is Like a Cocktail",
        "Osake wa Fuufu ni Natte kara",
        "https://cdn.myanimelist.net/images/anime/1684/108627.jpg",
        13,
        "PG-13 - Teens 13 or older",
        Synopsis.Cocktail,
        [""],
        "TV",
        "Oct 4 2017 to Dec 27 2017",
        "Fall 2017",
        "Creators in Pack",
        "Web manga",
        ["Comedy", "Gourmet", "Romance"],
        ["Adult Cast"],
        "3 minutes",
    ),
    new Anime(
        "Love Live! Nijigasaki High School Idol Club",
        "Love Live! Nijigasaki Gakuen School Idol Doukoukai",
        "https://cdn.myanimelist.net/images/anime/1393/109203.jpg",
        13,
        "PG-13 - Teens 13 or older",
        Synopsis.Nijigasaki,
        [""],
        "TV",
        "Oct 3 2020 to Dec 26 2020",
        "Fall 2020",
        "Sunrise",
        "Other",
        ["Slice of Life"],
        ["Idols (Female)", "Music", "School"],
        "24 minutes",
    ),
    new Anime(
        "Love Live! Nijigasaki High School Idol Club Season 2",
        "Love Live! Nijigasaki Gakuen School Idol Doukoukai 2nd Season",
        "https://cdn.myanimelist.net/images/anime/1586/121947.jpg",
        13,
        "PG-13 - Teens 13 or older",
        Synopsis.Nijigasaki2,
        [""],
        "TV",
        "Apr 2 2022 to Jun 25 2022",
        "Spring 2022",
        "Sunrise",
        "Other",
        ["Slice of Life"],
        ["Idols (Female)", "Music", "School"],
        "24 minutes",
    ),
    new Anime(
        "Lycoris Recoil",
        "",
        "https://cdn.myanimelist.net/images/anime/1261/127311.jpg",
        13,
        "PG-13 - Teens 13 or older",
        Synopsis.LycorisRecoil,
        [""],
        "TV",
        "Jul 2 2022 to Sep 24 2022",
        "Summer 2022",
        "A-1 Pictures",
        "Original",
        ["Action"],
        [""],
        "24 minutes",
    ),
]