export const Synopsis = {
    YuruCamp: `While the perfect getaway for most girls her age might be a fancy vacation with their loved ones, Rin Shima's ideal way of spending her days off is camping alone at the base of Mount Fuji. From pitching her tent to gathering firewood, she has always done everything by herself, and has no plans of leaving her little solitary world.
               However, what starts off as one of Rin's usual camping sessions somehow ends up as a surprise get-together for two when the lost Nadeshiko Kagamihara is forced to take refuge at her campsite. Originally intending to see the picturesque view of Mount Fuji for herself, Nadeshiko's plans are disrupted when she ends up falling asleep partway to her destination. Alone and with no other choice, she seeks help from the only other person nearby. Despite their hasty introductions, the two girls nevertheless enjoy the chilly night together, eating ramen and conversing while the campfire keeps them warm. And even after Nadeshiko's sister finally picks her up later that night, both girls silently ponder the possibility of another camping trip together.`,

    YuruCamp2: `Having spent Christmas camping with her new friends, Rin Shima embarks on a solo-camping trip to see the New Year sunrise by the sea. All goes according to plan until unforeseen weather blocks the roads back home, making a return trip impossible. Rin, who is now stranded for a few days, is invited by Nadeshiko Kagamihara to stay at her grandmother's house.
                What is supposed to be a two-day trip becomes an extended period of sightseeing and new experiences for Rin, and she encounters some new and old faces along the way. Yuru Camp△ Season 2 continues the story of Rin, Nadeshiko, and their friends as they further explore the joys of camping.`,

    FantasyBishoujo: `Since their days as students, Tsukasa Jinguuji has had incredible luck with women due to his good looks; Hinata Tachibana has had almost none, overshadowed by Jinguuji's brilliance. However, while Jinguuji has never shown interest in the opposite sex, Tachibana is always desperate for a girlfriend. Despite their polar differences, they continue to be best friends even in their thirties as salarymen.
                      One night, the two are returning home from a mixer where Jinguuji was the center of attention as usual. In his drunken rambles, a frustrated Tachibana inadvertently wishes to become a beautiful girl with irresistible charm. As if the heavens were listening, a goddess suddenly shows herself before Jinguuji and Tachibana, transporting them to another world to defeat the Demon Lord and simultaneously granting Tachibana's desire.
                      Tachibana—now in the body of an impossibly perfect woman—has become so attractive that even Jinguuji is captivated. Moreover, Tachibana grows aware of Jinguuji's stunning appearance, finally understanding his popularity. Before they fall in love with each other, the duo must complete their mission or risk remaining prisoners to their infatuations forever.`,

    LittleWitchAcademia: `"A believing heart is your magic!"—these were the words that Atsuko "Akko" Kagari's idol, the renowned witch Shiny Chariot, said to her during a magic performance years ago. Since then, Akko has lived by these words and aspired to be a witch just like Shiny Chariot, one that can make people smile. Hence, even her non-magical background does not stop her from enrolling in Luna Nova Magical Academy.
                           However, when an excited Akko finally sets off to her new school, the trip there is anything but smooth. After her perilous journey, she befriends the shy Lotte Yansson and the sarcastic Sucy Manbavaran. To her utmost delight, she also discovers Chariot's wand, the Shiny Rod, which she takes as her own. Unfortunately, her time at Luna Nova will prove to be more challenging than Akko could ever believe. She absolutely refuses to stay inferior to the rest of her peers, especially to her self-proclaimed rival, the beautiful and gifted Diana Cavendish, so she relies on her determination to compensate for her reckless behavior and ineptitude in magic.
                           In a time when wizardry is on the decline, Little Witch Academia follows the magical escapades of Akko and her friends as they learn the true meaning of being a witch.`,

    Chuunibyou: `Everybody has had that stage in their life where they have thought themselves to be special, different from the masses of ordinary humans. They might go as far as seeing themselves capable of wielding mystical powers, or maybe even believe themselves to have descended from a fantasy realm. This "disease" is known as "chuunibyou" and is often the source of some of the most embarrassing moments of a person's life.
                 For Yuuta Togashi, the scars that his chuunibyou has left behind are still fresh. Having posed as the "Dark Flame Master" during his middle school years, he looks back at those times with extreme embarrassment, so much so that he decides to attend a high school far away where nobody will recognize him. Putting his dark history behind him, he longs to live a normal high school life.
                 Unfortunately, he hasn't escaped his past yet: enter Rikka Takanashi, Yuuta's new classmate and self-declared vessel of the "Wicked Eye." As this eccentric young girl crashes into Yuuta's life, his dream of an ordinary, chuunibyou-free life quickly crumbles away. In this hilarious and heartwarming story of a boy who just wants to leave his embarrassing memories behind, the delusions of old are far from a thing of the past.`,

    Chuunibyou2: `The awkward lovebirds, Yuuta Togashi and Rikka Takanashi are now living together as they enter a new school year, but their adorable relationship remains stagnant. Yuuta struggles to adapt to having a chuuni girlfriend while the gang—Sanae Dekomori, Shinka Nibutani and Kumin Tsuyuri—are still keeping up with their quirks despite having advanced a grade. Making matters worse, another chuuni girl from Yuuta's middle school, Satone Shichimiya, appears...
                  With the various events revolving around Yuuta, will he be able to develop his relationship with Rikka?`,

    Cocktail: `Chisato Mizusawa is a calm and collected assistant office manager who apparently dislikes drinking alcohol. But she actually likes it and has a secret side to her that emerges only when drunk: her cute persona, which she only reveals to her husband, the bartender Sora. Each day when Chisato comes home, Sora takes care of his beloved wife, providing her with a good meal and a fresh drink. These drinks include Plum Splet, Irish Coffee, Orange Breeze, and many more tasty concoctions that she eagerly gulps down. But as much as she likes alcohol, she loves her kindhearted husband more. Together, they share a life that is filled with happiness—and the more-than-occasional cocktail.`,

    Nijigasaki: `Buried within the numerous clubs at Nijigasaki High School lies the school idol club. The club, while lacking popularity, definitely does not lack potential. During their debut performance, they were able to seize a sizable audience, along with the attention of their schoolmates Ayumu Uehara and Yuu Takasaki.
                 Enamored, the duo makes their way to join the club; however, they are disappointed to find out that the club had just been disbanded. Nevertheless, Ayumu does not believe that it should have ended there. Together with Yuu, they begin restoring the school idol club, hoping to recreate the idol performances that dazzled them before.
                 Love Live! Nijigasaki Gakuen School Idol Doukoukai shines its spotlight over the reformed school idol club as they recruit both former members of the club alongside newcomers. Taking the first step towards their dreams, how will these girls achieve idol stardom?`,

    Nijigasaki2: `The Nijigasaki High School Idol Club continues to gain popularity as its reputation grows, even catching the attention of aspiring school idol Zhong Lanzhu. However, when Lanzhu visits the club and interacts with its members, she realizes that their ideals differ from her own. This sparks the beginning of a rivalry between Lanzhu and the club members, as she challenges them to see who can captivate a larger audience at the upcoming School Idol Festival.
                  Thus, the school idol club starts a new chapter in its quest to achieve idol stardom. Being more united than ever before, the girls continue to practice for the festival—wanting to show Lanzhu what it truly means to be a school idol.`,

    LycorisRecoil: `The number of terrorist acts in Japan has never been lower, thanks to the efforts of a syndicate called Direct Attack (DA). The organization raises orphaned girls as killers to carry out assassinations under their "Lycoris" program. Takina Inoue is an exceptional Lycoris with a strong sense of purpose and a penchant for perfection. Unfortunately, a hostage situation tests her patience, and the resulting act of insubordination leads to her transfer out of DA. Not thrilled about losing the only place she belonged to, she reluctantly arrives at her new base of operations—LycoReco, a cafe in disguise.
                    Takina's new partner, however, turns out to be quite different from what she imagined. Despite being the famed Lycoris prodigy, Chisato Nishikigi appears almost unconcerned with her duties. She drags Takina along on all kinds of odd jobs under the simple explanation of helping people in need. Takina is even more puzzled when Chisato takes down a group of armed assailants without killing any of them. Feeling like a fish out of water, Takina itches to get reinstated into DA—but Chisato is determined to prove to her that there is more to a life than just taking them.`,


}