import { Anime } from "@/lib/Anime";
import { Synopsis } from "./kSynopsis";

export const k_anime = [
    new Anime(
        "K-On!",
        "",
        "https://cdn.myanimelist.net/images/anime/10/76120.jpg",
        13,
        "PG-13 - Teens 13 or older",
        Synopsis.Kon,
        [""],
        "TV",
        "Apr 3 2009 to Jun 26 2009",
        "Spring 2009",
        "Kyoto Animation",
        "4-koma manga",
        ["Comedy"],
        ["CGDCT", "Music", "School"],
        "24 minutes",
    ),
    new Anime(
        "K-ON! Season 2",
        "K-On!!",
        "https://cdn.myanimelist.net/images/anime/12/76121.jpg",
        26,
        "PG-13 - Teens 13 or older",
        Synopsis.Kon2,
        [""],
        "TV",
        "Apr 7 2010 to Sep 29 2010",
        "Spring 2010",
        "Kyoto Animation",
        "4-koma manga",
        ["Award Winning", "Comedy"],
        ["CGDCT", "Music", "School"],
        "24 minutes",
    ),
    new Anime(
        "Kaginado",
        "",
        "https://cdn.myanimelist.net/images/anime/1558/118634.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Kaginado,
        [""],
        "TV",
        "Oct 13 2021 to Dec 29 2021",
        "Fall 2021",
        "LIDENFILMS Kyoto Studio",
        "Original",
        ["Comedy", "Slice of Life"],
        [""],
        "4 minutes",
    ),
    new Anime(
        "KAGI-NADO",
        "Kaginado Season 2",
        "https://cdn.myanimelist.net/images/anime/1452/123859.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Kaginado2,
        [""],
        "TV",
        "Apr 13 2022 to Jun 29 2022",
        "Spring 2022",
        "LIDENFILMS Kyoto Studio",
        "Original",
        ["Comedy"],
        [""],
        "4 minutes",
    ),
    new Anime(
        "Kaguya-sama: Love is War",
        "Kaguya-sama wa Kokurasetai: Tensai-tachi no Renai Zunousen",
        "https://cdn.myanimelist.net/images/anime/1295/106551.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Kaguya,
        [""],
        "TV",
        "Jan 12 2019 to Mar 30 2019",
        "Winter 2019",
        "A-1 Pictures",
        "Manga",
        ["Comedy"],
        ["Psychological", "Romantic Subtext", "School"],
        "25 minutes",
    ),
    new Anime(
        "Kaguya-sama: Love is War Season 2",
        "Kaguya-sama wa Kokurasetai? Tensai-tachi no Renai Zunousen",
        "https://cdn.myanimelist.net/images/anime/1764/106659.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Kaguya2,
        [""],
        "TV",
        "Apr 11 2020 to Jun 27 2020",
        "Spring 2020",
        "A-1 Pictures",
        "Manga",
        ["Comedy"],
        ["Psychological", "Romantic Subtext", "School"],
        "24 minutes",
    ),
    new Anime(
        "Kaguya-sama: Love is War - Ultra Romantic",
        "Kaguya-sama wa Kokurasetai: Ultra Romantic",
        "https://cdn.myanimelist.net/images/anime/1160/122627.jpg",
        13,
        "PG-13 - Teens 13 or older",
        Synopsis.Kaguya3,
        [""],
        "TV",
        "Apr 9 2022 to Jun 25 2022",
        "Spring 2022",
        "A-1 Pictures",
        "Manga",
        ["Comedy", "Romance"],
        ["School"],
        "23 minutes",
    ),
    new Anime(
        "KanColle: Kantai Collection",
        "Kantai Collection: KanColle",
        "https://cdn.myanimelist.net/images/anime/4/73954.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.KanColle,
        [""],
        "TV",
        "Jan 8 2015 to Mar 26 2015",
        "Winter 2015",
        "Diomedea",
        "Game",
        ["Action", "Sci-Fi"],
        ["Anthropomorphic", "Military", "School"],
        "24 minutes",
    ),
    new Anime(
        "Keijo!!!!!!!!",
        "",
        "https://cdn.myanimelist.net/images/anime/10/81906.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Keijo,
        [""],
        "TV",
        "Oct 6 2016 to Dec 22 2016",
        "Fall 2016",
        "Xebec",
        "Manga",
        ["Sports", "Ecchi"],
        ["Combat Sports"],
        "23 minutes",
    ),
    new Anime(
        "Kill la Kill",
        "",
        "https://cdn.myanimelist.net/images/anime/1464/111943.jpg",
        24,
        "PG-13 - Teens 13 or older",
        Synopsis.KillLaKill,
        [""],
        "TV",
        "Oct 4 2013 to Mar 28 2014",
        "Fall 2013",
        "Trigger",
        "Original",
        ["Action", "Comedy", "Fantasy", "Ecchi"],
        ["School", "Super Power"],
        "24 minutes",
    ),
    new Anime(
        "KINMOZA!",
        "Kiniro Mosaic",
        "https://cdn.myanimelist.net/images/anime/1793/117610.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Kinmoza,
        [""],
        "TV",
        "Jul 6 2013 to Sep 21 2013",
        "Summer 2013",
        "Studio Gokumi",
        "4-koma manga",
        ["Slice of Life"],
        ["CGDCT", "School"],
        "24 minutes",
    ),
    new Anime(
        "Hello!! KINMOZA!",
        "Hello!! Kiniro Mosaic",
        "https://cdn.myanimelist.net/images/anime/1107/117611.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Kinmoza2,
        [""],
        "TV",
        "Apr 6 2015 to Jun 22 2015",
        "Spring 2015",
        "Studio Gokumi",
        "4-koma manga",
        ["Slice of Life"],
        ["CGDCT", "School"],
        "23 minutes",
    ),
    new Anime(
        "Kino's Journey -the Beautiful World- the Animated Series",
        "Kino no Tabi: The Beautiful World - The Animated Series",
        "https://cdn.myanimelist.net/images/anime/13/87235.jpg",
        12,
        "R - 17+ (violence & profanity)",
        Synopsis.KinoJourney,
        [""],
        "TV",
        "Oct 6 2017 to Dec 22 2017",
        "Fall 2017",
        "Lerche",
        "Light novel",
        ["Adventure", "Drama", "Fantasy"],
        [""],
        "23 minutes",
    ),
    new Anime(
        "Kiznaiver",
        "",
        "https://cdn.myanimelist.net/images/anime/6/78466.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Kiznaiver,
        [""],
        "TV",
        "Apr 9 2016 to Jun 25 2016",
        "Spring 2016",
        "Trigger",
        "Original",
        ["Drama", "Romance", "Sci-Fi"],
        [""],
        "24 minutes",
    ),
    new Anime(
        "Kokoro Connect",
        "",
        "https://cdn.myanimelist.net/images/anime/2/39665.jpg",
        13,
        "PG-13 - Teens 13 or older",
        Synopsis.KokoroConnect,
        [""],
        "TV",
        "Jul 8 2012 to Sep 30 2012",
        "Summer 2012",
        "SILVER LINK",
        "Light novel",
        ["Drama", "Romance", "Supernatural"],
        ["Love Polygon", "School"],
        "24 minutes",
    ),
    new Anime(
        "Kokoro Connect OVA",
        "Kokoro Connect: Michi Random",
        "https://cdn.myanimelist.net/images/anime/10/45526.jpg",
        4,
        "PG-13 - Teens 13 or older",
        Synopsis.KokoroConnectOVA,
        [""],
        "Special",
        "Nov 19 2012 to Dec 10 2012",
        "Fall 2012",
        "SILVER LINK",
        "Light novel",
        ["Drama", "Romance", "Supernatural"],
        ["School"],
        "27 minutes",
    ),
    new Anime(
        "Komi Can't Communicate",
        "Komi-san wa, Comyushou desu.",
        "https://cdn.myanimelist.net/images/anime/1899/117237.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Komi,
        [""],
        "TV",
        "Oct 7 2021 to Dec 23 2021",
        "Fall 2021",
        "OLM",
        "Manga",
        ["Comedy"],
        ["Romantic Subtext", "School"],
        "23 minutes",
    ),
    new Anime(
        "Komori-san Can't Decline!",
        "Komori-san wa Kotowarenai!",
        "https://cdn.myanimelist.net/images/anime/7/78082.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Komori,
        [""],
        "TV",
        "Oct 4 2015 to Dec 20 2015",
        "Fall 2015",
        "Artland",
        "4-koma manga",
        ["Comedy"],
        [""],
        "2 minutes",
    ),
    new Anime(
        "KonoSuba: An Explosion on This Wonderful World!",
        "Kono Subarashii Sekai ni Bakuen wo!",
        "https://cdn.myanimelist.net/images/anime/1626/135844.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.KonosubaMegumin,
        [""],
        "TV",
        "Apr 6 2023 to Jun 22 2023",
        "Spring 2023",
        "Drive",
        "Light novel",
        ["Comedy", "Fantasy"],
        [""],
        "23 minutes",
    ),
    new Anime(
        "KonoSuba - God's Blessing on This Wonderful World!",
        "Kono Subarashii Sekai ni Shukufuku wo!",
        "https://cdn.myanimelist.net/images/anime/1895/142748.jpg",
        10,
        "PG-13 - Teens 13 or older",
        Synopsis.Konosuba,
        [""],
        "TV",
        "Jan 14 2016 to Mar 17 2016",
        "Winter 2016",
        "Studio Deen",
        "Light novel",
        ["Adventure", "Comedy", "Fantasy"],
        ["Isekai", "Parody"],
        "23 minutes",
    ),
    new Anime(
        "KonoSuba: God's Blessing on This Wonderful World! 2",
        "Kono Subarashii Sekai ni Shukufuku wo! 2",
        "https://cdn.myanimelist.net/images/anime/2/83188.jpg",
        10,
        "PG-13 - Teens 13 or older",
        Synopsis.Konosuba2,
        [""],
        "TV",
        "Jan 12 2017 to Mar 16 2017",
        "Winter 2017",
        "Studio Deen",
        "Light novel",
        ["Adventure", "Comedy", "Fantasy"],
        ["Isekai", "Parody"],
        "23 minutes",
    ),
    new Anime(
        "KonoSuba: God's Blessing on This Wonderful World! - Legend of Crimson",
        "Kono Subarashii Sekai ni Shukufuku wo! Movie: Kurenai Densetsu",
        "https://cdn.myanimelist.net/images/anime/1638/119321.jpg",
        1,
        "PG-13 - Teens 13 or older",
        Synopsis.KonosubaMovie,
        [""],
        "Movie",
        "Aug 30 2019",
        "Summer 2019",
        "J.C. Staff",
        "Light novel",
        ["Adventure", "Comedy", "Fantasy"],
        ["Isekai", "Parody"],
        "1 hour 30 minutes",
    ),
    new Anime(
        "Kuromukuro",
        "",
        "https://cdn.myanimelist.net/images/anime/12/82281.jpg",
        26,
        "R - 17+ (violence & profanity)",
        Synopsis.Kuromukuro,
        [""],
        "TV",
        "Apr 7 2016 to Sep 29 2016",
        "Spring 2016",
        "P.A. Works",
        "Original",
        ["Action", "Sci-Fi"],
        ["Mecha"],
        "24 minutes",
    ),
]