export const Synopsis = {
    Kon: `A fresh high school year always means much to come, and one of those things is joining a club. Being in a dilemma about which club to join, Yui Hirasawa stumbles upon and applies for the Light Music Club, which she misinterprets to be about playing simple instruments, such as castanets. Unable to play an instrument, she decides to visit to apologize and quit.
          Meanwhile, the Light Music Club faces disbandment due to a lack of members. This causes the club members to offer anything, from food to slacking off during club time, in order to convince Yui to join. Despite their efforts, Yui insists on leaving due to her lack of musical experience. As a last resort, they play a piece for Yui, which sparks her fiery passion and finally convinces her to join the club.
          From then onward, it is just plain messing around with bits and pieces of practice. The members of the Light Music Club are ready to make their time together a delightful one!`,

    Kon2: `It is the new year, which means that the senior members of the Light Music Club are now third-years, with Azusa Nakano being the only second-year. The seniors soon realize that Azusa will be the only member left once they graduate and decide to recruit new members. Despite trying many methods of attracting underclassmen—handing out fliers, bringing people into the clubroom, and performing at the welcoming ceremony—there are no signs of anyone that plans to join.
           While heading to the clubroom, Azusa overhears Yui Hirasawa say that the club is fine with only five people and that they can do many fun things together. Changing her mind, she decides that they do not need to recruit any members for the time being.
           K-On!! revolves around the members of the Light Music Club as they experience their daily high school life. From rehearsing for concerts to just messing around, they are ready to make their last year together an exciting one!`,

    Kaginado: `People from various worlds and across different universes attend Kaginado Academy, a school of which its creation can only be attributed to a miracle. While everyone is trying to lead a normal school life, the clash of bustling personalities causes many of the students to beg questions about their world and the complexes they brought with them.
               Ryou Fujibayashi feels like her life is dictated by how she is judged by others, expressing her jealousy toward other girls. Yukito Kunisaki constantly finds himself out of place and neglected, continuing to wander around unemployed and penniless. Meanwhile, Ayu Tsukimiya keeps running into the most untimely of situations—all while crashing into her surroundings along the way. Such is life at Kaginado Academy, and all the fourth wall breaking and comedic antics that come with it!`,

    Kaginado2: `Although it is a miracle that Kaginado Academy remains standing, Yuri Nakamura and her cohorts vow to retaliate against the god that created their universe. Pointing out its many absurdities, she proposes that the academy is actually a stand-in for the afterlife.
                Yuri's theory makes everyone restless; some begin questioning and even second-guessing their own memories. However, not all agree with the notion, defending the fact that their current existence is a result of their past rather than the interference of an omniscient being. Life at Kaginado Academy continues to be frenetic—despite how much the students want it to be otherwise!`,

    Kaguya: `At the renowned Shuchiin Academy, Miyuki Shirogane and Kaguya Shinomiya are the student body's top representatives. Ranked the top student in the nation and respected by peers and mentors alike, Miyuki serves as the student council president. Alongside him, the vice president Kaguya—eldest daughter of the wealthy Shinomiya family—excels in every field imaginable. They are the envy of the entire student body, regarded as the perfect couple.
             However, despite both having already developed feelings for the other, neither are willing to admit them. The first to confess loses, will be looked down upon, and will be considered the lesser. With their honor and pride at stake, Miyuki and Kaguya are both equally determined to be the one to emerge victorious on the battlefield of love!`,

    Kaguya2: `After a slow but eventful summer vacation, Shuchiin Academy's second term is now starting in full force. As August transitions into September, Miyuki Shirogane's birthday looms ever closer, leaving Kaguya Shinomiya in a serious predicament as to how to celebrate it. Furthermore, the tenure of the school's 67th student council is coming to an end. Due to the council members being in different classes, the only time Kaguya and Miyuki have to be together will soon disappear, putting all of their cunning plans at risk.
              A long and difficult election that will decide the fate of the new student council awaits, as multiple challengers fight for the coveted title of president.`,

    Kaguya3: `The elite members of Shuchiin Academy's student council continue their competitive day-to-day antics. Council president Miyuki Shirogane clashes daily against vice-president Kaguya Shinomiya, each fighting tooth and nail to trick the other into confessing their romantic love. Kaguya struggles within the strict confines of her wealthy, uptight family, rebelling against her cold default demeanor as she warms to Shirogane and the rest of her friends.
              Meanwhile, council treasurer Yuu Ishigami suffers under the weight of his hopeless crush on Tsubame Koyasu, a popular upperclassman who helps to instill a new confidence in him. Miko Iino, the newest student council member, grows closer to the rule-breaking Ishigami while striving to overcome her own authoritarian moral code.
              As love further blooms at Shuchiin Academy, the student council officers drag their outsider friends into increasingly comedic conflicts.`,

    KanColle: `With the seas under constant threat from the hostile "Abyssal Fleet," a specialized naval base is established to counter them. Rather than standard naval weaponry, however, the base is armed with "Kanmusu"—girls who harbor the spirits of Japanese warships—possessing the ability to don weaponized gear that allows them to harness the powerful souls within themselves. Fubuki, a young Destroyer-type Kanmusu, joins the base as a new recruit; unfortunately for her, despite her inexperience and timid nature, she is assigned to the famous Third Torpedo Squadron and quickly thrust into the heat of battle. When she is rescued from near annihilation, the rookie warship resolves to become as strong as the one who saved her.`,

    Keijo: `Japan's latest competitive sport, keijo, is dictated by a simple set of rules: female-only participants must stand on circular platforms floating in a pool—referred to as "lands"—with the goal being to knocking off opponents using only their breasts and butts. Despite this outlandish premise, the sport attracts millions of viewers across the country and boasts a lavish prize pool. Many aspiring athletes take up the challenge in hopes of becoming the next national champion.
            After graduating from high school, the lively 17-year-old Nozomi Kaminashi enters the world of keijo, hoping to bring home a fortune to her poor family. As a gifted gymnast, Nozomi quickly proves herself a tough competitor after stealing the spotlight in her debut tournament. Meeting new friends and rivals as she climbs the ranks, Nozomi discovers that the path to stardom as a keijo player is filled with intense competition that will challenge not only her body, but also her soul.`,

    KillLaKill: `After the murder of her father, Ryuuko Matoi has been wandering the land in search of his killer. Following her only lead—the missing half of his invention, the Scissor Blade—she arrives at the prestigious Honnouji Academy, a high school unlike any other. The academy is ruled by the imposing and cold-hearted student council president Satsuki Kiryuuin alongside her powerful underlings, the Elite Four. In the school's brutally competitive hierarchy, Satsuki bestows upon those at the top special clothes called "Goku Uniforms," which grant the wearer unique superhuman abilities.
                 Thoroughly beaten in a fight against one of the students in uniform, Ryuuko retreats to her razed home where she stumbles across Senketsu, a rare and sentient "Kamui," or God Clothes. After coming into contact with Ryuuko's blood, Senketsu awakens, latching onto her and providing her with immense power. Now, armed with Senketsu and the Scissor Blade, Ryuuko makes a stand against the Elite Four, hoping to reach Satsuki and uncover the culprit behind her father's murder once and for all.`,

    Kinmoza: `Shinobu Oomiya once left Japan to participate in a homestay in England. During her time there, she became close friends with Alice Cartelet, the daughter of the family she was living with. However, when it was time for Shinobu to return to Japan, the two were able to express their sorrow despite the language barrier between them.
              Five years later, now a first year student in high school, Shinobu receives a letter by air mail in a language she does not understand. This letter is penned by none other than Alice, detailing her own homestay in Japan. In fact, Alice will be attending Shinobu's high school and living with her! Alongside their friends Youko Inokuma, Aya Komichi, and Karen Kujou, the five girls attend school together and learn about what their different cultures have to offer, day after day.`,

    Kinmoza2: `Although learning different languages continues to be an interest for Shinobu and her friends, the new school year brings unexpected difficulties. Not only is there always something new and different to distract them from their studies, but Alice and Yoko also are having trouble adjusting to being in a different class from Shinobu and Aya.
               Meanwhile, Karen isn't getting along at all with her new homeroom teacher, and it doesn't help that the teacher is having trouble figuring out how to make herself seem friendlier to her students as well. Craziness may ensue, but sometimes, all it takes is the right mutual experience to bring everyone together.
               While some of those experiences may not be as well-thought-out as others (like when Alice and Aya act like juvenile delinquents to seem more grown up), the gang's new adventures are certain to warm everyone's heart as the fun and friendships keep growing in HELLO!! KINMOZA!`,

    KinoJourney: `When 15-year-old Kino is feeling weighed down by heavy thoughts, one thing always manages to cheer her up: traveling. Nothing fills her heart with joy like exploring the beautiful, wonderful world around her and the fascinating ways people find to live. However, Kino is not as helpless as her cute appearance and courteous demeanor suggest. Armed with "Cannon" and "Woodsman," her trusted handguns, Kino isn't afraid to kill anyone who would dare to get in her way. Always by her side is her best friend and loyal companion Hermes, a sentient motorcycle, who supports Kino through the sorrows and hardships of their journey. Together, they travel the vast countryside with the shared goal of always moving forward, and a single rule: never stay in one country for more than three days.
                  As Kino and Hermes encounter new people and learn the rules of their civilizations, they grow and find out more about their own values and virtues. But as Kino slowly discovers the world around her, she also finds herself facing dangers that linger within the vast unknown.`,

    Kiznaiver: `Katsuhira Agata is a quiet and reserved teenage boy whose sense of pain has all but vanished. His friend, Chidori Takashiro, can only faintly remember the days before Katsuhira had undergone this profound change. Now, his muffled and complacent demeanor make Katsuhira a constant target for bullies, who exploit him for egregious sums of money. But their fists only just manage to make him blink, as even emotions are far from his grasp.
                However, one day Katsuhira, Chidori, and four other teenagers are abducted and forced to join the Kizuna System as official "Kiznaivers." Those taking part are connected through pain: if one member is injured, the others will feel an equal amount of agony. These individuals must become the lab rats and scapegoats of an incomplete system designed with world peace in mind. With their fates literally intertwined, the Kiznaivers must expose their true selves to each other, or risk failing much more than just the Kizuna System.`,

    KokoroConnect: `When five students at Yamaboshi Academy realize that there are no clubs where they fit in, they band together to form the Student Cultural Society, or "StuCS" for short. The club consists of: Taichi Yaegashi, a hardcore wrestling fan; Iori Nagase, an indecisive optimist; Himeko Inaba, a calm computer genius; Yui Kiriyama, a petite karate practitioner; and Yoshifumi Aoki, the class clown.
                    One day, Aoki and Yui experience a strange incident when, without warning, they switch bodies for a short period of time. As this supernatural phenomenon continues to occur randomly amongst the five friends, they begin to realize that it is not just fun and games. Now forced to become closer than ever, they soon discover each other's hidden secrets and emotional scars, which could end up tearing the StuCS and their friendship apart.`,

    KokoroConnectOVA: `Not long after putting the previous supernatural incident behind them, the members of Yamaboshi Academy's Student Cultural Society (StuCS) must deal with Fuusenkazura's newest trial—emotion transmission. This phenomenon allows the club members to hear each others' true thoughts, but with one catch: the timing, sender, and recipient are all completely random. To make matters worse, the club's supervisor, Ryuuzen Gotou, may have to step down due to his responsibilities for the upcoming school year. With emotions running high and Valentine's Day around the corner, the seemingly close bonds of the StuCS will be tested when their true feelings for each other are laid bare.`,

    Komi: `Hitohito Tadano is an ordinary boy who heads into his first day of high school with a clear plan: to avoid trouble and do his best to blend in with others. Unfortunately, he fails right away when he takes the seat beside the school's madonna—Shouko Komi. His peers now recognize him as someone to eliminate for a chance to sit next to the most beautiful girl in class.
           Gorgeous and graceful with long, dark hair, Komi is universally adored and immensely popular despite her mysterious persona. However, unbeknownst to everyone, she has crippling anxiety and a communication disorder which prevents her from wholeheartedly socializing with her classmates.
           When left alone in the classroom, a chain of events forces Komi to interact with Tadano through writing on the blackboard, as if in a one-way conversation. Being the first person to realize she cannot communicate properly, Tadano picks up the chalk and begins to write as well. He eventually discovers that Komi's goal is to make one hundred friends during her time in high school. To this end, he decides to lend her a helping hand, thus also becoming her first-ever friend.`,

    Komori: `Fifteen-year-old Komori Shuri is a junior high school girl who is too nice to decline requests. Constantly doing favors for other people has given her incredible strength?! But even so, she is also an adolescent junior high school girl.
             An anime overflowing with the ups and downs of everyday life!`,

    KonosubaMegumin: `Megumin is a young and passionate wizard from the Crimson Demon Village, a remote community of mages with red eyes and a flair for the dramatic. She has devoted her life to mastering explosion magic, a powerful but impractical spell that leaves her drained of mana and unable to move for the rest of the day. Regardless, she refuses to learn any other skills.
                      Along with her childhood friend and self-proclaimed rival, Yunyun, Megumin enrolls in the Red Prison: a prestigious academy for Crimson Demon magic users. There, she learns more about the secrets and history of her clan, as well as the threats and challenges they must face. As she polishes her power at the Red Prison with the help of her loyal familiar Chomusuke and her adorable little sister Komekko, Megumin aims to become the greatest explosion wizard of all time!`,

    Konosuba: `After dying a laughable and pathetic death on his way back from buying a game, high school student and recluse Kazuma Satou finds himself sitting before a beautiful but obnoxious goddess named Aqua. She provides the NEET with two options: continue on to heaven or reincarnate in every gamer's dream—a real fantasy world! Choosing to start a new life, Kazuma is quickly tasked with defeating a Demon King who is terrorizing villages. But before he goes, he can choose one item of any kind to aid him in his quest, and the future hero selects Aqua. But Kazuma has made a grave mistake—Aqua is completely useless!
               Unfortunately, their troubles don't end here; it turns out that living in such a world is far different from how it plays out in a game. Instead of going on a thrilling adventure, the duo must first work to pay for their living expenses. Indeed, their misfortunes have only just begun!`,

    Konosuba2: `When Kazuma Satou died, he was given two choices: pass on to heaven or be revived in a fantasy world. After choosing the new world, the goddess Aqua tasked him with defeating the Demon King, and let him choose any weapon to aid him. Unfortunately, Kazuma chose to bring Aqua herself and has regretted the decision ever since then.
                Not only is he stuck with a useless deity turned party archpriest, the pair also has to make enough money for living expenses. To add to their problems, their group continued to grow as more problematic adventurers joined their ranks. Their token spellcaster, Megumin, is an explosion magic specialist who can only cast one spell once per day and refuses to learn anything else. There is also their stalwart crusader, Lalatina Ford "Darkness" Dustiness, a helpless masochist who makes Kazuma look pure in comparison.
                Kono Subarashii Sekai ni Shukufuku wo! 2 continues to follow Kazuma and the rest of his party through countless more adventures as they struggle to earn money and have to deal with one another's problematic personalities. However, things rarely go as planned, and they are often sidetracked by their own idiotic tendencies.`,

    KonosubaMovie: `It is not strange that the Demon Lord's forces fear the Crimson Demons, the clan from which Megumin and Yunyun originate. Even if the Demon Lord's generals attack their village, the Crimson Demons can just easily brush them off with their supreme mastery of advanced and overpowered magic.
                    When Yunyun receives a seemingly serious letter regarding a potential disaster coming to her hometown, she immediately informs Kazuma Satou and the rest of his party. After a series of wacky misunderstandings, it turns out to be a mere prank by her fellow demon who wants to be an author. Even so, Megumin becomes worried about her family and sets out toward the Crimson Demons' village with the gang.
                    There, Kazuma and the others decide to sightsee the wonders of Megumin's birthplace. However, they soon come to realize that the nonsense threat they received might have been more than just a joke.`,

    Kuromukuro: `During the dawn of the 21st century, the United Nations Kurobe Research Institute was established in Japan to investigate an ancient artifact, which was discovered during the construction of the Kurobe Dam. Scientists from around the world have gathered in the facility to study the object, while their children enjoy their everyday lives attending Mt. Tate International Senior High School.
                 Yukina Shirahane, a reserved high school girl, is the daughter of the facility's head scientist. While visiting her mother at the facility, Yukina manages to solve part of the artifact's puzzle. To her surprise, what appears before her is Kennosuke Tokisada Ouma, a young samurai from the Sengoku era.
                 As a threat approaches from outer space, Yukina, along with Kennosuke, finds herself defending Earth against the invading forces. Along the way, she discovers the mystery behind Kennosuke and the reason he is determined to protect her.`,


}