import { Anime } from "@/lib/class/Anime";
import { Synopsis } from "./aSynopsis";

export const a_anime = [
    new Anime(  
        "A Bridge to the Starry Skies", 
        "Hoshizora e Kakaru Hashi", 
        "https://cdn.myanimelist.net/images/anime/3/73521.jpg", 
        12, 
        "R+ - Mild Nudity", 
        Synopsis.Hoshizora_e_Kakaru_Hashi,
        ["Crunchyroll"],
        "TV",
        "Apr 11 2011 to Jun 27 2011",
        "Spring 2011",
        "Doga Kobo",
        "Visual novel",
        ["Comedy", "Romance", "Ecchi"],
        ["Harem", "School"],
        "25 minutes"
    ),
    new Anime(  
        "Ace Attorney",
        'Gyakuten Saiban: Sono "Shinjitsu", Igi Ari!',
        "https://cdn.myanimelist.net/images/anime/5/79448.jpg",
        24,
        "PG-13 - Teens 13 or older",
        Synopsis.Ace_Attorney,
        ["Crunchyroll", "Apple TV", "Google Play Movie"],
        "TV",
        "April 2 2016 to Sep 24 2016",
        "Spring 2016",
        "A-1 Pictures",
        "Game",
        ["Comedy", "Drama", "Mystery"],
        ["Adult Cast", "Detective", "Workplace"],
        "24 minutes",
    ),
    new Anime(  
        "Ace Attorney Season 2",
        'Gyakuten Saiban: Sono "Shinjitsu", Igi Ari! Season 2',
        "https://cdn.myanimelist.net/images/anime/1861/91089.jpg",
        23,
        "PG-13 - Teens 13 or older",
        Synopsis.Ace_Attorney2,
        ["Crunchyroll", "Apple TV", "Google Play Movie"],
        "TV",
        "Oct 6 2018 to Mar 30 2019",
        "Fall 2018",
        "CloverWorks",
        "Game",
        ["Comedy", "Drama", "Mystery"],
        ["Adult Cast", "Detective", "Workplace"],
        "24 minutes",
    ),
    new Anime(
        "AHO-GIRL",
        "Aho Girl",
        "https://cdn.myanimelist.net/images/anime/7/86665.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Aho_Girl,
        ["Crunchyroll"],
        "TV",
        "Jul 4 2017 to Sep 19 2017",
        "Summer 2017",
        "Diomedea",
        "4-koma manga",
        ["Comedy"],
        ["Gag Humor", "School"],
        "12 minutes",
    ),
    new Anime(
        "Ai-Mai-Mi",
        "Choboraunyopomi Gekijou Ai Mai Mii",
        "https://cdn.myanimelist.net/images/anime/7/45306.jpg",
        13,
        "PG-13 - Teens 13 or older",
        Synopsis.Ai_Mai_Mi,
        [""],
        "TV",
        "Jan 3 2013 to Mar 27 2013",
        "Winter 2013",
        "Seven",
        "4-koma manga",
        ["Comedy"],
        [""],
        "3 minutes",
    ),
    new Anime(
        "Ai-Mai-Mi Mousou Catastrophe",
        "Choboraunyopomi Gekijou Dai Ni Maku Ai Mai Mii: Mousou Catastrophe",
        "https://cdn.myanimelist.net/images/anime/6/65753.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Ai_Mai_Mi2,
        [""],
        "TV",
        "Jul 8 2014 to Sep 23 2014",
        "Summer 2014",
        "Seven",
        "4-koma manga",
        ["Comedy"],
        [""],
        "3 minutes",
    ),
    new Anime(
        "Ai-Mai-Mi Surgical Friends",
        "Choboraunyopomi Gekijou Dai San Maku Ai Mai Mii: Surgical Friends",
        "https://cdn.myanimelist.net/images/anime/11/83846.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Ai_Mai_Mi3,
        [""],
        "TV",
        "Jan 3 2017 to Mar 21 2017",
        "Winter 2017",
        "Seven",
        "4-koma manga",
        ["Comedy"],
        [""],
        "3 minutes",
    ),
    new Anime(
        "Aiura",
        "",
        "https://cdn.myanimelist.net/images/anime/4/60699.jpg",
        12,
        "G - All Ages",
        Synopsis.Aiura,
        [""],
        "TV",
        "Apr 10 2013 to Jun 26 2013",
        "Spring 2013",
        "LIDENFILMS",
        "4-koma manga",
        ["Slice of Life"],
        ["CGDCT", "Iyashikei", "School"],
        "4 minutes",
    ),
    new Anime(
        "Akashic Records of Bastard Magic Instructor",
        "Rokudenashi Majutsu Koushi to Akashic Records",
        "https://cdn.myanimelist.net/images/anime/8/85593.jpg",
        12,
        "R - 17+ (violence & profanity)",
        Synopsis.Akashic,
        [""],
        "TV",
        "Apr 4 2017 to Jun 20 2017",
        "Spring 2017",
        "LIDENFILMS",
        "Light novel",
        ["Action", "Fantasy"],
        ["School"],
        "24 minutes",
    ),
    new Anime(
      "Akiba's Trip The Animation",
      "",
      "https://cdn.myanimelist.net/images/anime/9/83185.jpg",
      13,
      "PG-13 - Teens 13 or older",
      Synopsis.Akiba,
      [""],
      "TV",
      "Jan 4 2017 to Mar 29 2017",
      "Winter 2017",
      "Gonzo",
      "Game",
      ["Action", "Comedy", "Supernatural", "Ecchi"],
      ["Otaku Culture"],
      "23 minutes",
    ),
    new Anime(
      "Akebi's Sailor Uniform",
      "Akebi-chan no Sailor-fuku",
      "https://cdn.myanimelist.net/images/anime/1820/120520.jpg",
      12,
      "PG-13 - Teens 13 or older",
      Synopsis.Akebi,
      [""],
      "TV",
      "Jan 9 2022 to Mar 27 2022",
      "Winter 2022",
      "CloverWorks",
      "Web manga",
      ["Slice of Life"],
      ["CGDCT", "School"],
      "23 minutes",
    ),
    new Anime(
      "Alice or Alice",
      "",
      "https://cdn.myanimelist.net/images/anime/1033/116744.jpg",
      12,
      "PG-13 - Teens 13 or older",
      Synopsis.Alice,
      [""],
      "TV",
      "Apr 4 2018 to Jun 20 2018",
      "Spring 2018",
      "EMT Squared",
      "4-koma manga",
      ["Slice of Life"],
      ["CGDCT"],
      "3 minutes",
    ),
    new Anime(
      "Amagi Brilliant Park",
      "",
      "https://cdn.myanimelist.net/images/anime/5/85435.jpg",
      13,
      "PG-13 - Teens 13 or older",
      Synopsis.Amagi,
      [""],
      "TV",
      "Oct 7 2014 to Dec 26 2014",
      "Fall 2014",
      "Kyoto Animation",
      "Light novel",
      ["Comedy", "Fantasy"],
      ["Workplace"],
      "24 minutes",
    ),
    new Anime(
      "Angels of Death",
      "Satsuriku no Tenshi",
      "https://cdn.myanimelist.net/images/anime/1862/95624.jpg",
      16,
      "R - 17+ (violence & profanity)",
      Synopsis.Angels,
      [""],
      "TV",
      "Jul 6 2018 to Oct 26 2018",
      "Summer 2018",
      "J.C. Staff",
      "Game",
      ["Adventure", "Horror", "Suspense"],
      ["Gore", "Psychological"],
      "23 minutes",
    ),
    new Anime(
      "Anima Yell!",
      "",
      "https://cdn.myanimelist.net/images/anime/1051/93862.jpg",
      12,
      "PG-13 - Teens 13 or older",
      Synopsis.Anima,
      [""],
      "TV",
      "Oct 7 2018 to Dec 23 2018",
      "Fall 2018",
      "Doga Kobo",
      "4-koma manga",
      ["Comedy", "Sports"],
      ["CGDCT", "Performing Arts", "School"],
      "23 minutes",
    ),
    new Anime(
      "Anne-Happy",
      "Anne Happy♪",
      "https://cdn.myanimelist.net/images/anime/9/78701.jpg",
      12,
      "PG-13 - Teens 13 or older",
      Synopsis.Anne,
      [""],
      "TV",
      "Apr 7 2016 to Jun 23 2016",
      "Spring 2016",
      "SILVER LINK",
      "Manga",
      ["Slice of Life"],
      ["CGDCT", "School"],
      "23 minutes",
    ),
    new Anime(
      "Another",
      "",
      "https://cdn.myanimelist.net/images/anime/4/75509.jpg",
      12,
      "R - 17+ (violence & profanity)",
      Synopsis.Another,
      [""],
      "TV",
      "Jan 10 2012 to Mar 27 2012",
      "Winter 2012",
      "P.A. Works",
      "Novel",
      ["Horror", "Mystery", "Supernatural"],
      ["Gore", "School"],
      "24 minutes",
    ),
    new Anime(
"Ao-chan Can't Study!",
      "Midara na Ao-chan wa Benkyou ga Dekinai",
      "https://cdn.myanimelist.net/images/anime/1718/98214.jpg",
      12,
      "PG-13 - Teens 13 or older",
      Synopsis.Ao,
      [""],
      "TV",
      "Apr 6 2019 to Jun 22 2019",
      "Spring 2019",
      "SILVER LINK",
      "Manga",
      ["Comedy", "Romance", "Ecchi"],
      ["School"],
      "12 minutes",
    ),
    new Anime(
      "Aria the Scarlet Ammo",
      "Hidan no Aria",
      "https://cdn.myanimelist.net/images/anime/9/30095.jpg",
      12,
      "PG-13 - Teens 13 or older",
      Synopsis.Aria,
      [""],
      "TV",
      "Apr 15 2011 to Jul 1 2011",
      "Spring 2011",
      "J.C. Staff",
      "Light novel",
      ["Action", "Comedy", "Romance", "Ecchi"],
      ["Harem", "School"],
      "24 minutes",
    ),
    new Anime(
      "Armed Girl's Machiavellism",
      "Busou Shoujo Machiavellianism",
      "https://cdn.myanimelist.net/images/anime/3/83995.jpg",
      12,
      "PG-13 - Teens 13 or older",
      Synopsis.Armed,
      [""],
      "TV",
      "Apr 5 2017 to Jun 21 2017",
      "Spring 2017",
      "SILVER LINK, Connect",
      "Manga",
      ["Action", "Comedy", "Ecchi"],
      ["Harem", "Martial Arts", "School"],
      "23 minutes",
    ),
    new Anime(
      "Assassination Classroom",
      "Ansatsu Kyoushitsu",
      "https://cdn.myanimelist.net/images/anime/5/75639.jpg",
      22,
      "PG-13 - Teens 13 or older",
      Synopsis.Assassination,
      [""],
      "TV",
      "Jan 10 2015 to Jun 20 2015",
      "Winter 2015",
      "Lerche",
      "Manga",
      ["Action", "Comedy"],
      ["School"],
      "23 minutes",
    ),
    new Anime(
        "Assassination Classroom Second Season",
        "Ansatsu Kyoushitsu 2nd Season",
        "https://cdn.myanimelist.net/images/anime/8/77966.jpg",
        25,
        "PG-13 - Teens 13 or older",
        Synopsis.Assassination2,
        [""],
        "TV",
        "Jan 7 2016 to Jul 1 2016",
        "Winter 2016",
        "Lerche",
        "Manga",
        ["Action", "Comedy"],
        ["School"],
        "23 minutes",
    ),
    new Anime(
      "ASSASSINS PRIDE",
      "",
      "https://cdn.myanimelist.net/images/anime/1267/103421.jpg",
      12,
      "PG-13 - Teens 13 or older",
      Synopsis.Assassins,
      [""],
      "TV",
      "Oct 10 2019 to Dec 26 2019",
      "Fall 2019",
      "Sentai Filmworks",
      "Light novel",
      ["Fantasy"],
      [""],
      "24 minutes",
    ),
    new Anime(
      "Astarotte's Toy",
      "Astarotte no Omocha!",
      "https://cdn.myanimelist.net/images/anime/3/75562.jpg",
      12,
      "PG-13 - Teens 13 or older",
      Synopsis.Astarotte,
      [""],
      "TV",
      "Apr 11 2011 to Jun 26 2011",
      "Spring 2011",
      "Diomedea",
      "Manga",
      ["Comedy", "Fantasy", "Romance", "Ecchi"],
      ["Harem", "Isekai"],
      "23 minutes",
    ),
    new Anime(
      "Asteroid in Love",
      "Koisuru Asteroid",
      "https://cdn.myanimelist.net/images/anime/1142/111693.jpg",
      12,
      "PG-13 - Teens 13 or older",
      Synopsis.Asteroid,
      [""],
      "TV",
      "Jan 3 2020 to Mar 27 2020",
      "Winter 2020",
      "Doga Kobo",
      "4-koma manga",
      ["Slice of Life"],
      ["CGDCT", "School"],
      "23 minutes",
    ),
    new Anime(
      "Attack on Titan",
      "Shingeki no Kyojin",
      "https://cdn.myanimelist.net/images/anime/10/47347.jpg",
      25,
      "R - 17+ (violence & profanity)",
      Synopsis.AttackOnTitan,
      [""],
      "TV",
      "Apr 7 2013 to Sep 29 2013",
      "Spring 2013",
      "Wit Studio",
      "Manga",
      ["Action", "Award Winning", "Drama", "Suspense"],
      ["Gore", "Military", "Survival"],
      "24 minutes"
    ),
    new Anime(
      "Attack on Titan Season 2",
      "Shingeki no Kyojin Season 2",
      "https://cdn.myanimelist.net/images/anime/4/84177.jpg",
      12,
      "R - 17+ (violence & profanity)",
      Synopsis.AttackOnTitan2,
      [""],
      "TV",
      "Apr 1 2017 to Jun 17 2017",
      "Spring 2017",
      "Wit Studio",
      "Manga",
      ["Action", "Drama", "Suspense"],
      ["Gore", "Military", "Survival"],
      "24 minutes"
    ),
    new Anime(
      "Attack on Titan Season 3",
      "Shingeki no Kyojin Season 3",
      "https://cdn.myanimelist.net/images/anime/1173/92110.jpg",
      12,
      "R - 17+ (violence & profanity)",
      Synopsis.AttackOnTitan3,
      [""],
      "TV",
      "Jul 23 2018 to Oct 15 2018",
      "Summer 2018",
      "Wit Studio",
      "Manga",
      ["Action", "Drama", "Suspense"],
      ["Gore", "Military", "Survival"],
      "23 minutes"
    ),
    new Anime(
      "Attack on Titan: Junior High",
      "Shingeki! Kyojin Chuugakkou",
      "https://cdn.myanimelist.net/images/anime/3/75467.jpg",
      12,
      "PG-13 - Teens 13 or older",
      Synopsis.AttackOnTitanJrHigh,
      [""],
      "TV",
      "Oct 4 2015 to Dec 20 2015",
      "Fall 2015",
      "Production I.G",
      "Manga",
      ["Comedy"],
      ["Parody", "School"],
      "17 minutes",
    ),
    new Anime(
      "AzurLane: Slow Ahead!",
      "Azur Lane: Bisoku Zenshin!",
      "https://cdn.myanimelist.net/images/anime/1137/113872.jpg",
      12,
      "PG-13 - Teens 13 or older",
      Synopsis.AzurLaneSlowAhead,
      [""],
      "TV",
      "Jan 12 2021 to Mar 30 2021",
      "Winter 2021",
      "Studio CANDY BOX",
      "4-koma manga",
      ["Comedy", "Sci-Fi"],
      ["Anthropomorphic", "CGDCT", "Military"],
      "8 minutes",
    ),
];