export const Synopsis = {
  Hoshizora_e_Kakaru_Hashi: `Kazuma Hoshino is preparing himself for a new stage of his life as a teenager. Because of his brother Ayumu's weaker than average health, their parents thought it best for the family to move out from the city to a more rural environment. Now the two brothers are off to the Yorozuyo Inn where they’ll be staying until their parents can settle affairs back in the city and set up their new home.
                               Their arrival to the inn doesn't go as planned though when they catch the wrong bus, wind up in the middle of nowhere, Ayumu gets his hat stolen by a wild monkey, and Kazuma gets lost in the woods trying to track the animal down. It all leads to a chance encounter with a spirited young girl named Ui, who Kazuma ends up accidentally falling onto and kissing while she tries leading him back to the bus stop. This hardly sits well with Ui’s friend Ibuki who swiftly kicks Kazuma and sends him on his way. Much to Kazuma's continued horror, his bad luck is perpetuated at the inn thanks to its landlady Senka and her slightly perverted sense of humor, and then finding out that two of his classmates are the girls he embarrassed himself in front of back in the woods!
                               Hoshizora e Kakaru Hashi finds Kazuma adapting to his new school, dealing with the multiple women who have entered his life, providing emotional support for his younger brother, and coping with living with his new landlady. However, for some reason, something about this place is bringing whispers of the past into Kazuma's mind. Small flashes back to a more innocent time and a friendship long forgotten. What could this déjà vu mean?`,

  Ace_Attorney: `Since he was a child, Ryuuichi Naruhodou's dream was to become a defense attorney, protecting the innocent when no one else would. However, when the rookie lawyer finally takes on his first case under the guidance of his mentor Chihiro Ayasato, he realizes that the courtroom is a battlefield. In these fast paced trials, Ryuuichi is forced to think outside the box to uncover the truth of the crimes that have taken place in order to prove the innocence of his clients.
                   Gyakuten Saiban: Sono "Shinjitsu", Igi Ari! follows Ryuuichi as he tackles cases to absolve the falsely accused of the charges they face. It will not be easy—standing in his path is the ruthless Reiji Mitsurugi, a prosecutor who will stop at nothing to hand out guilty verdicts. With his back against the wall, the defense attorney must carefully examine both evidence and witness testimony, sifting through lies to solve the mystery behind each case. With a shout of "objection!," the battle in the courtroom begins!`,

  Ace_Attorney2: `Defense attorney Ryuuichi Naruhodou is still hard at work defending the falsely accused with his knack for last-minute turnabouts. With his trusty assistant and medium-in-training Mayoi Ayasato in tow, Ryuuichi's fame as a champion for the innocent steadily grows. But this newfound success attracts the attention of the coffee-loving, masked Godot⁠—a mysterious rookie prosecutor who bears an inexplicable grudge against Ryuuichi.
                    With the help of their allies, Ryuuichi and Mayoi take this new challenger head-on and search for the reason behind his appearance. But before long, the first two cases from the career of Mayoi's late sister Chihiro Ayasato become critical to solving a fantastical murder mystery, continuing the bloody saga of the tumultuous Ayasato clan. Will Ryuuichi once again be able to overcome the odds and find the truths hidden within the web of lies?`,

  Aho_Girl: `Yoshiko Hanabatake is an idiot beyond all belief. Somehow managing to consistently score zeroes on all of her tests and consumed by an absurd obsession with bananas, her senseless acts have caused even her own mother to lose all hope. Only one person is up to the task of keeping her insanity in check: childhood friend Akuru "A-kun" Akutsu. Though he bemoans the ridiculous behavior he has to endure, the studious but terrifying A-kun is always ready to put an end to any stupidity Yoshiko gets up to, with no qualms about using physical force. Unfortunately, no matter how many times he attempts to knock some sense into her, the girl bounces right back to her usual shenanigans, even dragging in some other eccentrics along for the ride. Try as he might to rein in her nonsense, every moment is unpredictable with Yoshiko and her profound idiocy on the loose.`,

  Ai_Mai_Mi: `The anime adaptation of the four-panel manga "Ai Mai Mii". The story follows girls in a manga club—Ai, Mai, Mii, and Ponoka-senpai—who might be fighting evil invaders threatening Earth, facing off against rivals in tournaments, and dealing with other absurd situations when they are not drawing manga.`,

  Ai_Mai_Mi2: `Second season of Ai Mai Mii.`,

  Ai_Mai_Mi3: `Third season of Ai Mai Mii.`,

  Aiura: `As spring vacation comes to a close, a new school semester approaches. Deciding to make the most of the remaining holiday, Ayuko Uehara takes a stroll into her neighborhood and stops by a small cafe. However, her peaceful day is abruptly disturbed when a girl clumsily bumps into her. Left puzzled by the encounter, Ayaku is even more surprised when she meets them again as freshmen at the same high school she attends. Recognizing her from the store, the girls introduce themselves as Kanaka Amaya and Saki Iwasawa, and the three quickly become friends. As they go through their daily lives as high school girls, the trio's distinct personalities—Kanaka's happy-go-lucky attitude, Saki's tomboyish behavior, and Ayuko's easygoingness—are sure to make every mundane school day filled with silly and fun interactions.`,

  Akashic: `The Alzano Empire is home to one of the most distinguished magic schools in the world: the Alzano Imperial Magic Academy. Here, ambitious young students undergo training to become competent magicians. Sistine Fibel—a stern noble girl—and her bright-eyed best friend Rumia Tingel attend the Academy, determined to cultivate their magical skills.
              However, their world is thrown for a loop when their favorite teacher suddenly retires and the enigmatic Glenn Radars replaces him. His lazy and indifferent attitude toward life and magic quickly puts him at odds with his class. What's more, nefarious forces hidden within the empire's walls start to become active, and Sistine, Rumia, and Glenn find themselves caught up in their schemes.
              Rokudenashi Majutsu Koushi to Akashic Records follows Sistine, who is captivated by a mysterious floating Sky Castle; Rumia, who is haunted by a troubled past; and Glenn, who may be more than meets the eye. Though completely different on the surface, they are inexplicably bound together by a thread of fate.`,

  Akiba: `Otaku siblings Tamotsu and Niwaka Denkigai are shopping in Akihabara when it is overrun by vampiric cosplaying monsters! These creatures, known as "Bugged Ones," can possess anyone they bite and soon they begin causing mayhem across the city. As Tamotsu finds himself at the mercy of one of these creatures, he is rescued by the mysterious baseball bat-wielding Matome Mayonaka. Together, they fight through several more encounters with the Bugged Ones, but before long, Tamotsu is fatally wounded protecting Matome. With no other choice, she revives him as a high level Bugged One—just like her!
            Tamotsu and Matome, along with excitable otaku cosplayer Arisa Ahokainen, make up the group "The Electric Mayonnaise" and they begin dispatching the Bugged Ones in the only way they know how: by ripping off their clothes and exposing them to sunlight!`,

  Akebi: `Ever since she was young, Komichi Akebi has always adored sailor uniforms, even going so far as to ask her mother to sew one if she succeeds in getting into her mother's alma mater, Roubai Academy. And thus, when she gets accepted into the prestigious school, Komichi is ecstatic. However, much to her surprise, the middle school no longer uses sailor uniforms as its dress code—making Komichi stand out from her schoolmates. Despite this, Komichi is granted permission to continue wearing the traditional attire.
            With renewed confidence, Komichi meets fascinating classmates as they experience school life together. Under the colorful shower of blossoming prospects, an exciting tomorrow awaits them!`,

  Alice: `This story gives a look at the daily life of a pair of Alice twins and their older brother who has a sister complex. Them eating meals, getting into fights, playing with friends... Would you like to peek at the heart-full daily life of the cute Alices?`,

  Alya: `Seirei Academy is a prestigious school attended by the very best students in Japan. Alisa Mikhailovna "Alya" Kujou, the half-Russian and half-Japanese treasurer of the school's student council, is known for her intelligence, stunning looks, and rigid personality. Contrasting her near-flawless persona, Alya's unmotivated classmate Masachika Kuze slacks off during lessons and seems to show no interest in her.
         Initially irritated, Alya gradually becomes more intrigued by Masachika and starts expressing her affection for him in Russian. However, she is oblivious to his secret—he understands the language fluently! Due to a childhood friend who was temporarily staying in Japan, Masachika has been studying Russian in hopes of reuniting with her.
         As the two spend more time together, the playful and eccentric relationship between them quickly deepens. In the meantime, both must learn to navigate their new growing feelings for one another.`,

  Amagi: `Seiya Kanie, a smart and extremely narcissistic high school student, believes that the beautiful but reserved Isuzu Sento has invited him on a date at an amusement park called Amagi Brilliant Park. Much to his chagrin, not only is the location a run-down facility, the supposed date is merely a recruitment tour where Sento and Princess Latifa Fleuranza, the owner of the theme park, ask him to become the park's new manager. Their cause for desperation? As stipulated in a land-use contract, Amagi has less than three months to meet a quota of 500,000 guests, or the park will be closed for good and the land redeveloped by a greedy real-estate company.
            Seiya is won over by the revelation that Amagi is no ordinary amusement park; many of its employees are Maple Landers—mysterious magical beings who live in the human world and are nourished by the energy created by people having fun. Entrusted with the hopes and dreams of this far-off enchanted land, Seiya must now use his many skills to bring Amagi back on its feet, or watch it crumble before his eyes.`,

  Angels: `With dead and lifeless eyes, Rachel Gardner wishes only to die. Waking up in the basement of a building, she has no idea how or why she's there. She stumbles across a bandaged murderer named Zack, who is trying to escape. After promising to kill her as soon as he is free, Rachel and Zack set out to ascend through the building floor by floor until they escape.
             However, as they progress upward, they meet more twisted people, and all of them seem familiar with Rachel. What is her connection to the building, and why was she placed in it? Facing a new boss on each floor, can Rachel and Zack both achieve their wishes?`,

  Anima: `Kohane Hatoya’s most lovable trait is also her greatest flaw. She loves to help others no matter how far she has to go in order to get the job done. Her biggest inspiration to do so comes to light when she sees what cheerleading looks like for the first time in middle school. Now a highschooler but as enthusiastic as ever, Kohane wants nothing more than to start her very own cheerleading squad. She's encouraged by her best friend, Uki Sawatari, who often has to help her get out of trouble.
            There is just one problem: Kohane does not have any experience in cheerleading. She has absolutely no idea what to do, what to wear, or how to perform. To make matters worse, she has been scared of heights since childhood, and this new sport is full of stunts pulled far from the ground for a girl her size. Enter Hizume Arima, a former cheerleader who wishes to leave her pastime behind. Unfortunately for her, Kohane recognizes Hizume, and will stop at nothing just so she can lead the new squad, even if it means facing her childhood fear.`,

  Anne: `Tennomifune Academy is an elite institution for the best and the brightest, with the exception of Class 1-7, the so-called "Happiness Class." Each member of the classroom copes with personal misfortunes, and the special class is geared to help them move past their issues and find true happiness.
           After being accepted into the academy, An Hanakoizumi, Ruri Hibarigaoka, and Botan Kumegawa find themselves placed into the Happiness Class, plagued by dreadful luck, love problems, and bad health respectively. Alongside their classmates, they do their best to overcome the difficulties they are faced with in pursuit of a life filled with joy.`,

  Another: `In class 3-3 of Yomiyama North Junior High, transfer student Kouichi Sakakibara makes his return after taking a sick leave for the first month of school. Among his new classmates, he is inexplicably drawn toward Mei Misaki—a reserved girl with an eyepatch whom he met in the hospital during his absence. But none of his classmates acknowledge her existence; they warn him not to acquaint himself with things that do not exist. Against their words of caution, Kouichi befriends Mei—soon learning of the sinister truth behind his friends' apprehension.
              The ominous rumors revolve around a former student of the class 3-3. However, no one will share the full details of the grim event with Kouichi. Engrossed in the curse that plagues his class, Kouichi sets out to discover its connection to his new friend. As a series of tragedies arise around them, it is now up to Kouichi, Mei, and their classmates to unravel the eerie mystery—but doing so will come at a hefty price.`,

  Ao: `"Show them your A-O face!" As an innocent child, Ao Horie would unhesitantly proclaim the origins of her name. Now that she is in high school, she is determined to study hard in order to one day escape the influence of her lascivious father, a famous erotic author. However, when the amiable Takumi Kijima confesses to Horie, her mind runs wild with scandalous thoughts.
         Moans eager to escape, legs crossing, and a warmth spreading through her body, Horie cannot help but misconstrue Kijima's rather pure motivations. To make things worse, no matter how hard she tries to ward off Kijima, his advances do not stop. Now, if only she could just study!`,

  Aria: `In response to the worsening crime rate, Japan creates Tokyo Butei High, an elite academy where "Butei" or armed detectives hone their deadly skills in hopes of becoming mercenary-like agents of justice. One particular Butei is Kinji Tooyama, an anti-social and curt sophomore dropout who was once a student of the combat-centric Assault Division. Kinji now lives a life of leisure studying logistics in order to cover up his powerful but embarrassing special ability. However, his peaceful days soon come to an end when he becomes the target of the infamous "Butei Killer," and runs into an emotional hurricane and outspoken prodigy of the highest rank, Aria Holmes Kanzaki, who saves Kinji's life and demands that he become her partner after seeing what he is truly capable of.`,

  Armed: `The Private Aichi Symbiosis Academy was originally a high school for high-class girls. When it became co-ed, the girls, out of fear, asked to be permitted to bring weapons to school. When that was enforced, a five-member vigilante corps-like organization called the "Supreme Five Swords" was also formed.
            After many generations, the five swords eventually became a group which corrected problematic students, and the academy started proactively accepting such students in order to correct them.
            Nomura Fudou was sent to this school after being part of a huge brawl. What will he do when the only options he has after enrolling are being expelled from that school or being corrected the way the rest of the male students there were...by being forced to dress and act like a girl!`,

  Assassination: `Tucked in the mountains near the elite Kunugigaoka Middle School lies a small derelict building that houses the delinquents and dropouts of Class 3-E. Looked down upon by their peers, the students in this class appear to have little hope in advancing their academic careers. That is, until the national government tasks them with eliminating the greatest threat to their planet: their new teacher.
                    Having already destroyed the moon, the octopus-like professor—dubbed "Koro-sensei"—has now threatened to destroy the Earth by March of the following year. In light of their mission, the students have found that killing him is easier said than done. Not only can Koro-sensei move at speeds of up to Mach 20, but he can also resist almost every earthly weapon. Ironically, he also proves to be one of the best teachers Class 3-E has ever had. Training the class to excel in both their studies as students and skills as assassins, Koro-sensei is confident that his students' ingenuity and indomitable will could return them to the main campus.
                    Through trial and error, Nagisa Shiota, as well as the other students of Class 3-E, must figure out Koro-sensei's weaknesses—and fast, for the very fate of the world depends upon it.`,

  Assassination2: `Returning from their summer vacation, the students of Class 3-E at the prestigious Kunugigaoka Middle School find themselves up against unbeatable odds. Faced with the possibility of world annihilation, the students must come up with increasingly elaborate and creative ways to kill their teacher, the cunning yet optimistic and helpful Koro-sensei.
                     However, eliminating Koro-sensei is not the only objective the students need to worry about. Gakuhou Asano, the academy's merciless and cruel principal, seeks to prevent Class 3-E's success by brainwashing his other hard-working pupils into ruthlessly competitive studying machines. Hostility begins to linger in the air as traitors and killers alike attempt to claim the bounty on Koro-sensei's head for themselves.
                     Nagisa Shiota, one of Class 3-E's most skilled assassins, finds himself in the middle of the conflict. While he works to maintain his academic standing and prevent the end of the world, domestic affairs jeopardize his place in Class 3-E. Together with his dedicated classmates, he must now face the threats head-on.`,

  Assassins: `On the brink of extinction, mankind has downsized and now solely resides in the city-state of Flandore, living in cities encased by glass domes. Beyond the domes exist vicious lycanthropes who thrive in the darkness; among the citizens inside, a clear distinction between the nobility and commoners is in place. The blood of nobles enables them to utilize mana, granting them abilities that exceed human limits and greatly assist them in defeating lycanthropes.
                Already 13 years of age, noble Melida Angel has yet to manifest her mana, and attends an elite academy where she is mistreated for her lack thereof. In order to help her, Kufa Vampir is ordered by the Angel family to become Melida's tutor. While Kufa seems to be a mere mentor, an ulterior motive lurks behind his job—he is to assassinate her if he confirms that she does not possess mana.
                Kufa's investigation eventually leads him to determine he must eliminate Melida. However, Kufa is struck by her unwavering determination, spirit, and belief in herself when he witnesses her in a fight, choosing instead to offer a way she can manifest her magic. As Melida learns to use mana with the help of Kufa's teachings, Kufa forsakes his mission and jeopardizes everything to keep his discovery of Melida unknown to the Angel family and his own guild. However, both Kufa and Melida will soon realize that hiding their secret will not be the only challenge they face, as unforeseen trouble is waiting just around the corner.`,

  Astarotte: `Succubi, like the young princess Astarotte "Lotte" Ygvar, require the life seed from men to survive, replenish their magic, and continue the royal lineage of the magical realm. This means succubi are required to keep a harem of men close at hand. Ironically, Lotte despises men, which will put her life at risk once she matures. To convince her to fulfill her duties, one of her attendants, Judith Snorrevik, goes to the human realm to find a human male whom Lotte can tolerate.
                Judith returns with 23-year-old Naoya Touhara, a single father who unfortunately leaves his daughter, Asuha, behind in the human realm. As the first member of Lotte's harem, Naoya quickly adapts to this new environment, serving the princess to make her happy, rather than viewing her with sexual intent. Unfortunately, when his daughter is allowed to arrive in the magical realm, Naoya's relationship quickly worsens with Lotte. Even so, he strives to patch up their relationship.
                It soon becomes clear, however, that Naoya's presence in the magical realm is more than just mere coincidence. As he develops his bond with Lotte, fate begins to pull together the connections that tie him and everyone else within this enchanting world.`,

  Asteroid: `In a fateful childhood encounter, Mira Kinohata met a stargazing dreamer named Ao Manaka. Though their time together was short, Ao showed Mira the wonders of astronomy, from orbiting planets to distant stars. Before they parted, Mira learned that a star with her name exists, but there are none with Ao's. And so, she forged a promise: one day, she would discover a new asteroid and name it after Ao.
               Years later, Mira is still fascinated with astronomy. Now in high school at Hoshizaki Academy, she tries to join the Astronomy Club. Unfortunately, she finds out that the club has been merged with the Geology Club to form a single Earth Sciences Club. She joins this new club and finds a pleasant surprise—she reunites with Ao after years of separation.
               Alongside their new clubmates, Mira and Ao begin their journey together to fulfill their promise. How hard could it possibly be to find an asteroid?`,

  AttackOnTitan: `Centuries ago, mankind was slaughtered to near extinction by monstrous humanoid creatures called Titans, forcing humans to hide in fear behind enormous concentric walls. What makes these giants truly terrifying is that their taste for human flesh is not born out of hunger but what appears to be out of pleasure. To ensure their survival, the remnants of humanity began living within defensive barriers, resulting in one hundred years without a single titan encounter. However, that fragile calm is soon shattered when a colossal Titan manages to breach the supposedly impregnable outer wall, reigniting the fight for survival against the man-eating abominations.
                  After witnessing a horrific personal loss at the hands of the invading creatures, Eren Yeager dedicates his life to their eradication by enlisting into the Survey Corps, an elite military unit that combats the merciless humanoids outside the protection of the walls. Eren, his adopted sister Mikasa Ackerman, and his childhood friend Armin Arlert join the brutal war against the Titans and race to discover a way of defeating them before the last walls are breached.`,

  AttackOnTitan2: `For centuries, humanity has been hunted by giant, mysterious predators known as the Titans. Three mighty walls—Wall Maria, Rose, and Sheena—provided peace and protection for humanity for over a hundred years. That peace, however, was shattered when the Colossal Titan and Armored Titan appeared and destroyed the outermost wall, Wall Maria. Forced to retreat behind Wall Rose, humanity waited with bated breath for the Titans to reappear and destroy their safe haven once more.
                   In Shingeki no Kyojin Season 2, Eren Yeager and others of the 104th Training Corps have just begun to become full members of the Survey Corps. As they ready themselves to face the Titans once again, their preparations are interrupted by the invasion of Wall Rose—but all is not as it seems as more mysteries are unraveled. As the Survey Corps races to save the wall, they uncover more about the invading Titans and the dark secrets of their own members.`,

  AttackOnTitan3: `Still threatened by the "Titans" that rob them of their freedom, mankind remains caged inside the two remaining walls. Efforts to eradicate these monsters continue; however, threats arise not only from the Titans beyond the walls, but from the humans within them as well.
                   After being rescued from the Colossal and Armored Titans, Eren Yaeger devotes himself to improving his Titan form. Krista Lenz struggles to accept the loss of her friend, Captain Levi chooses Eren and his friends to form his new personal squad, and Commander Erwin Smith recovers from his injuries. All seems well for the soldiers, until the government suddenly demands custody of Eren and Krista. The Survey Corps' recent successes have drawn attention, and a familiar face from Levi's past is sent to collect the wanted soldiers. Sought after by the government, Levi and his new squad must evade their adversaries in hopes of keeping Eren and Krista safe.
                   Eren and his fellow soldiers are not only fighting for their survival against the terrifying Titans, but also against the terror of a far more conniving foe: their fellow humans.`,

  AttackOnTitanJrHigh: `On his first day of junior high, Eren Yeager comes face-to-face with a titan—and has his lunch stolen! From that day on, he holds a grudge against titans for taking his favorite food from him, a cheeseburger, vowing to eliminate their kind once and for all. Along with his adoptive sister Mikasa Ackerman and their friend Armin Arlert, the trio traverse the halls of Titan Junior High, encountering familiar faces and participating in various extracurricular activities as part of the Wall Cleanup Club.
                          A parody of the immensely popular parent series, Shingeki! Kyojin Chuugakkou places beloved characters as junior high school students, fighting to protect their lunches from gluttonous titans.`,

  AzurLaneSlowAhead: `In a seemingly peaceful time without looming threats of Sirens or war, shipgirls from different nations live together in harmony. Some girls, such as the destroyers Ayanami, Javelin, Laffey, and Z23, attend school. Others immerse themselves into various other activities, including sports, foraging, training, going to formal parties, or even vying for the commander's attention! But one thing is for certain: the girls will continue to deepen their friendship in the pleasant port of Azur Lane!`,
};
