import { Anime } from "@/lib/Anime";
import { Synopsis } from "./jSynopsis";

export const j_anime = [
    new Anime(
        "Jingai-san no Yome",
        "",
        "https://cdn.myanimelist.net/images/anime/1050/108631.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Jingai,
        [""],
        "TV",
        "Oct 3 2018 to Dec 18 2018",
        "Fall 2018",
        "Saetta",
        "4-koma manga",
        ["Comedy", "Fantasy", "Romance"],
        ["School"],
        "3 minutes",
    ),
    new Anime(
        "Jojo's Bizarre Adventure",
        "JoJo no Kimyou na Bouken",
        "https://cdn.myanimelist.net/images/anime/3/40409.jpg",
        26,
        "R - 17+ (violence & profanity)",
        Synopsis.Jojo,
        [""],
        "TV",
        "Oct 6 2012 to Apr 6 2013",
        "Fall 2012",
        "David Production",
        "Manga",
        ["Action", "Adventure", "Supernatural"],
        ["Historical", "Vampire"],
        "24 minutes",
    ),
    new Anime(
        "JoJo's Bizarre Adventure: Stardust Crusaders",
        "JoJo no Kimyou na Bouken Part 3: Stardust Crusaders",
        "https://cdn.myanimelist.net/images/anime/11/55267.jpg",
        24,
        "R - 17+ (violence & profanity)",
        Synopsis.Jojo3,
        [""],
        "TV",
        "Apr 5 2014 to Sep 13 2014",
        "Spring 2014",
        "David Production",
        "Manga",
        ["Action", "Adventure", "Supernatural"],
        [""],
        "24 minutes",
    ),
    new Anime(
        "JoJo's Bizarre Adventure: Stardust Crusaders - Battle in Egypt",
        "JoJo no Kimyou na Bouken Part 3: Stardust Crusaders 2nd Season",
        "https://cdn.myanimelist.net/images/anime/11/75045.jpg",
        24,
        "R - 17+ (violence & profanity)",
        Synopsis.Jojo3_5,
        [""],
        "TV",
        "Jan 10 2015 to Jun 20 2015",
        "Winter 2015",
        "David Production",
        "Manga",
        ["Action", "Adventure", "Supernatural"],
        [""],
        "23 minutes",
    ),
    new Anime(
        "JoJo's Bizarre Adventure: Diamond Is Unbreakable",
        "JoJo no Kimyou na Bouken Part 4: Diamond wa Kudakenai",
        "https://cdn.myanimelist.net/images/anime/3/79156.jpg",
        39,
        "R - 17+ (violence & profanity)",
        Synopsis.Jojo4,
        [""],
        "TV",
        "Apr 2 2016 to Dec 24 2016",
        "Spring 2016",
        "David Production",
        "Manga",
        ["Action", "Adventure", "Supernatural"],
        [""],
        "23 minutes",
    ),
    new Anime(
        "JoJo's Bizarre Adventure: Golden Wind",
        "JoJo no Kimyou na Bouken Part 5: Ougon no Kaze",
        "https://cdn.myanimelist.net/images/anime/1572/95010.jpg",
        39,
        "R - 17+ (violence & profanity)",
        Synopsis.Jojo5,
        [""],
        "TV",
        "Oct 6 2018 to Jul 28 2019",
        "Fall 2018",
        "David Production",
        "Manga",
        ["Action", "Adventure", "Supernatural"],
        ["Organized Crime"],
        "23 minutes",
    ),
    new Anime(
        "JoJo's Bizarre Adventure: Stone Ocean",
        "JoJo no Kimyou na Bouken Part 6: Stone Ocean",
        "https://cdn.myanimelist.net/images/anime/1896/119844.jpg",
        12,
        "R - 17+ (violence & profanity)",
        Synopsis.Jojo6,
        [""],
        "ONA",
        "Dec 1 2021",
        "Fall 2021",
        "David Production",
        "Manga",
        ["Action", "Adventure", "Supernatural"],
        [""],
        "24 minutes",
    ),
    new Anime(
        "Joshikausei",
        "",
        "https://cdn.myanimelist.net/images/anime/1660/98376.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Joshikausei,
        [""],
        "TV",
        "Apr 6 2019 to Jun 22 2019",
        "Spring 2019",
        "Seven",
        "Web manga",
        ["Comedy", "Slice of Life"],
        ["CGDCT", "School"],
        "3 minutes",
    ),
]