export const Synopsis = {
    Jingai: `High schooler Tomari Hinowa is called to the principal's office one day to hear some shocking news: he's getting married! A mysterious fluffy creature called Kanenogi has chosen him as their wife, and despite Tomari's initial misgivings, he decides to accept. What follows are a series of delightful tales from this new couple's monstrous married life.`,

    Jojo: `The year is 1868; English nobleman George Joestar and his son Jonathan become indebted to Dario Brando after being rescued from a carriage incident. What the Joestars don't realize, however, is that Dario had no intention of helping them; he believed they were dead and was trying to ransack their belongings. After Dario's death 12 years later, George—hoping to repay his debt—adopts his son, Dio.
           While he publicly fawns over his new father, Dio secretly plans to steal the Joestar fortune. His first step is to create a divide between George and Jonathan. By constantly outdoing his foster brother, Dio firmly makes his place in the Joestar family. But when Dio pushes Jonathan too far, Jonathan defeats him in a brawl.
           Years later, the two appear to be close friends to the outside world. But trouble brews again when George falls ill, as Jonathan suspects that Dio is somehow behind the incident—and it appears he has more tricks up his sleeve.`,

    Jojo3: `Years after an ancient evil was salvaged from the depths of the sea, Joutarou Kuujou sits peacefully within a Japanese jail cell. He's committed no crime yet demands he not be released, believing he's been possessed by an evil spirit capable of harming those around him. Concerned for her son, Holy Kuujou asks her father, Joseph Joestar, to convince Joutarou to leave the prison. Joseph informs his grandson that the "evil spirit" is in fact something called a "Stand," the physical manifestation of one's fighting spirit which can adopt a variety of deadly forms. After a fiery brawl with Joseph's friend Muhammad Avdol, Joutarou is forced out of his cell and begins learning how to control the power of his Stand.
            However, when a Stand awakens within Holy and threatens to consume her in 50 days, Joutarou, his grandfather, and their allies must seek out and destroy the immortal vampire responsible for her condition. They must travel halfway across the world to Cairo, Egypt and along the way, do battle with ferocious Stand users set on thwarting them. If Joutarou and his allies fail in their mission, humanity is destined for a grim fate.`,

    Jojo3_5: `Joutarou Kuujou and his allies have finally made it to Egypt, where the immortal Dio awaits. Upon their arrival, the group gains a new comrade: Iggy, a mutt who wields the Stand "The Fool." It's not all good news however, as standing in their path is a new group of Stand users who serve Dio, each with a Stand representative of an ancient Egyptian god. As their final battle approaches, it is a race against time to break Joutarou's mother free from her curse and end Dio's reign of terror over the Joestar family once and for all.`,

    Jojo4: `The year is 1999. Morioh, a normally quiet and peaceful town, has recently become a hotbed of strange activity. Joutarou Kuujou, now a marine biologist, heads to the mysterious town to meet Jousuke Higashikata. While the two may seem like strangers at first, Jousuke is actually the illegitimate child of Joutarou's grandfather, Joseph Joestar. When they meet, Joutarou realizes that he may have more in common with Jousuke than just a blood relation.
            Along with the mild-mannered Kouichi Hirose and the boisterous Okuyasu Nijimura, the group dedicates themselves to investigating recent disappearances and other suspicious occurrences within Morioh. Aided by the power of Stands, the four men will encounter danger at every street corner, as it is up to them to unravel the town's secrets, before another occurs.`,

    Jojo5: `In the coastal city of Naples, corruption is teeming—the police blatantly conspire with outlaws, drugs run rampant around the youth, and the mafia governs the streets with an iron fist. However, various fateful encounters will soon occur.
            Enter Giorno Giovanna, a 15-year-old boy with an eccentric connection to the Joestar family, who makes a living out of part-time jobs and pickpocketing. Furthermore, he is gifted with the unexplained Stand ability to give and create life—growing plants from the ground and turning inanimate objects into live animals, an ability he has dubbed "Gold Experience." Fascinated by the might of local gangsters, Giorno has dreamed of rising up in their ranks and becoming a "Gang-Star," a feat made possible by his encounter with Bruno Bucciarati, a member of the Passione gang with his own sense of justice.`,

    Jojo6: `Conspiring forces frame Jolyne Kuujou for a reckless crime, landing her in the infamous Green Dolphin Street Jail. Much like her father Joutarou, Jolyne is brash, brave, and just; she rails against her unfair sentence and quickly discovers the sinister circumstances that led to her incarceration.
            A gift from her absent father grants Jolyne the power of Stone Free, a supernatural ability known as a Stand that allows her to unravel her body into string. Jolyne uses Stone Free to battle her way through the prison, recruiting new allies—Ermes Costello and Foo Fighters—to assist in her investigation. Together, the fearless women fight to uncover the menace behind Whitesnake, an enemy Stand responsible for the increasingly dangerous prisoners who are after Jolyne's life.
            Through Jolyne, the Joestar lineage confronts the legacy of its one true enemy. Jolyne and her friends race to stop a disastrous plot and put an end to a culminating evil.`,

    Joshikausei: `Momoko Futo is an average high-school girl going about her everyday life. Though laid-back and cheerful, her life is anything but mundane as her eccentricity and clumsiness never fail to spice up her days. Her two best friends are always with her: the cute and innocent Mayumi Furui, and the calm and cool Shibumi Shibusawa. Without any spoken dialogue or narration, Joshikausei aims to recount the comedic shenanigans these girls get up to through the expressive sounds and gestures that they make.`,


}