import { Anime } from "@/lib/Anime";
import { Synopsis } from "./bSynopsis";

export const b_anime = [
    new Anime(
        "Beast Tamer",
                  "Yuusha Party wo Tsuihou sareta Beast Tamer, Saikyoushu no Nekomimi Shoujo to Deau",
        "https://cdn.myanimelist.net/images/anime/1084/126652.jpg",
        13,
        "PG-13 - Teens 13 or older",
        Synopsis.Beast,
        [""],
        "TV",
        "Oct 2 2022 to Dec 25 2022",
        "Fall 2022",
        "EMT Squared",
        "Web manga",
        ["Action", "Fantasy"],
        ["Harem"],
        "23 minutes",
    ),
    new Anime(
        "Black Bullet",
        "",
        "https://cdn.myanimelist.net/images/anime/1292/94693.jpg",
        13,
        "R - 17+ (violence & profanity)",
        Synopsis.Black,
        [""],
        "TV",
        "Apr 8 2014 to Jul 1 2014",
        "Spring 2014",
        "Kinema Citrus, Orange",
        "Light novel",
        ["Action", "Mystery", "Sci-Fi"],
        [""],
        "24 minutes",
    ),
    new Anime(
        "BLEND-S",
        "Blend S",
        "https://cdn.myanimelist.net/images/anime/6/88286.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.BlendS,
        [""],
        "TV",
        "Oct 8 2017 to Dec 24 2017",
        "Fall 2017",
        "A-1 Pictures",
        "4-koma manga",
        ["Comedy"],
        ["Otaku Culture", "Romantic", "Subtext", "Workplace"],
        "23 minutes",
    ),
    new Anime(
        "Blue Exorcist",
        "Ao no Exorcist",
        "https://cdn.myanimelist.net/images/anime/10/75195.jpg",
        25,
        "PG-13 - Teens 13 or older",
        Synopsis.Blue,
        [""],
        "TV",
        "Apr 17 2011 to Oct 2 2011",
        "Spring 2011",
        "A-1 Pictures",
        "Manga",
        ["Action", "Fantasy"],
        ["Mythology", "School"],
        "24 minutes",
    ),
    new Anime(
        "Bocchi the Rock!",
        "",
        "https://cdn.myanimelist.net/images/anime/1448/127956.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Bocchi,
        [""],
        "TV",
        "Oct 9 2022 to Dec 25 2022",
        "Fall 2022",
        "CloverWorks",
        "4-koma manga",
        ["Comedy"],
        ["CDGCT", "Music"],
        "23 minutes",
    ),
    new Anime(
        "Brave Witches",
        "",
        "https://cdn.myanimelist.net/images/anime/6/81854.jpg",
        12,
        "R+ - Mild Nudity",
        Synopsis.BraveWitches,
        [""],
        "TV",
        "Oct 6 2016 to Dec 29 2016",
        "Fall 2016",
        "SILVER LINK",
        "Original",
        ["Action", "Sci-Fi", "Ecchi"],
        ["Military"],
        "23 minutes",
    ),
    new Anime(
        "BUILD-DIVIDE -#000000- CODE BLACK",
        "Build Divide: Code Black",
        "https://cdn.myanimelist.net/images/anime/1014/117452.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.BuildDivideBlack,
        [""],
        "TV",
        "Oct 10 2021 to Dec 26 2021",
        "Fall 2021",
        "LIDENFILMS",
        "Mixed media",
        ["Fantasy"],
        ["Strategy Game"],
        "23 minutes",
    ),
    new Anime(
        "Build Divide -#FFFFFF- Code White",
        "Build Divide: Code White",
        "https://cdn.myanimelist.net/images/anime/1194/121459.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.BuildDivideWhite,
        [""],
        "TV",
        "Apr 3 2022 to Jun 26 2022",
        "Spring 2022",
        "LIDENFILMS",
        "Mixed media",
        ["Fantasy"],
        ["Strategy Game"],
        "23 minutes",
    )
]