export const Synopsis = {
    Beast: `Among all the beasts that roam the world, there are unique types of "ultimate species" that harbor immense strength and magical prowess considered to be at the top of the power scale. As such, many humans covet their abilities, leading some of these species to the brink of extinction.
            As a beast tamer, Rein Shroud can employ the assistance of various animals for many tasks, such as reconnaissance and logistics. By virtue of his ability, he joins a party led by the vile and manipulative hero Arios Orlando, only to be banished after six months due to his uselessness as a non-combative class.
            However, unbeknownst to the team that cast him away, Rein is an exception among beast tamers. His potential becomes apparent when he meets Kanade—a cat spirit who is also one of the ultimate species—and is able to form a contract with her. With Kanade by his side, Rein sets out on his journey as an adventurer, steadily rising up the ranks and meeting more ultimate species along the way.`,

    Black: `In the year 2021, a parasitic virus known as "Gastrea" infects humans and turns them into monsters. What is left of mankind now lives within the Monolith walls, walls that are made of Varanium, the only material that can hurt Gastrea.
            To counter the threat that the Gastrea pose, "Cursed Children"—female children whose bodies contain trace amounts of the virus which grant them superhuman abilities—officially called Initiators by the Tendo Civil Security, are given partners called Promoters, people who work to guide and protect the young Initiators. These teams of two are sent out on missions to fight the monsters created by the Gastrea virus and keep them at bay.
            Black Bullet revolves around the team of Enju Aihara, an Initiator, and Satomi Rentaro, a Promoter, as they go on missions to fight the growing threat of Gastrea in their hometown of Tokyo.`,

    BlendS: `Wishing to be independent, 16-year-old Maika Sakuranomiya is desperate to nail down a part-time job so that she can afford to study abroad. Unfortunately, her applications are constantly rejected due to the menacing look she unintentionally makes whenever she smiles, despite her otherwise cheerful disposition.
             After yet another failed interview, she chances upon Café Stile, a coffee shop where the servers interact with the customers while roleplaying distinctive characteristics. The Italian store manager, Dino, becomes infatuated with Maika's cuteness at first sight, and offers her a job as a waitress with a sadistic nature. Coupled with her inherent clumsiness, she successfully manages to serve a pair of masochistic customers in accordance with her new, ruthless persona. Alongside Kaho Hinata as the tsundere and Mafuyu Hoshikawa as the younger sister, Maika decides to make the most out of her unique quirk and cements her position in the cafe with merciless cruelty!`,

    Blue: `Humans and demons are two sides of the same coin, as are Assiah and Gehenna, their respective worlds. The only way to travel between the realms is by the means of possession, like in ghost stories. However, Satan, the ruler of Gehenna, cannot find a suitable host to possess and therefore, remains imprisoned in his world. In a desperate attempt to conquer Assiah, he sends his son instead, intending for him to eventually grow into a vessel capable of possession by the demon king.
           Ao no Exorcist follows Rin Okumura who appears to be an ordinary, somewhat troublesome teenager—that is until one day he is ambushed by demons. His world turns upside down when he discovers that he is in fact the very son of Satan and that his demon father wishes for him to return so they can conquer Assiah together. Not wanting to join the king of Gehenna, Rin decides to begin training to become an exorcist so that he can fight to defend Assiah alongside his brother Yukio.`,

    Bocchi: `Yearning to make friends and perform live with a band, lonely and socially anxious Hitori "Bocchi" Gotou devotes her time to playing the guitar. On a fateful day, Bocchi meets the outgoing drummer Nijika Ijichi, who invites her to join Kessoku Band when their guitarist, Ikuyo Kita, flees before their first show. Soon after, Bocchi meets her final bandmate—the cool bassist Ryou Yamada.
             Although their first performance together is subpar, the girls feel empowered by their shared love for music, and they are soon rejoined by Kita. Finding happiness in performing, Bocchi and her bandmates put their hearts into improving as musicians while making the most of their fleeting high school days.`,

    BraveWitches: `As humanity's war with the Neuroi—a mysterious, hostile alien race possessing weapons of unparalleled power—continues being fought across Europe and Africa, a new fighter squadron is formed. The 502nd Joint Fighter Wing, also known as the Brave Witches, operates on the eastern front, scouring the icy vastness of Orussia in search of alien invaders.
                   However, one of the Brave Witches' members suffers severe injuries on her way to the squadron's headquarters, rendering her unable to participate in any operations. As a result, her sister, Hikari Karibuchi, volunteers to take her place. Though not possessing any special abilities or significant magical powers, she is determined to live up to the expectations of her new comrades and prove herself worthy of the name of a Witch.`,

    BuildDivideBlack: `Neo Kyoto is a place where everything is decided through the card game "Build Divide." From resolving personal conflicts to determining social status, success in Build Divide means success in life. The biggest ambition of every player is to become the King, whose peerless skills grant them near-total rule over the city.
                       One day, a young man wakes up in Neo Kyoto—with the knowledge of just his name, Teruto Kurabe, and carrying only a deck for a card game he no longer knows. Teruto soon encounters another player, Sakura Banka, who helps him remember both how to play Build Divide and his original mission: that no matter what, he must meet the King. Teaming up together, Teruto and Sakura find that their best chance for a royal audience is with the Rebuild tournament, where the one who collects twenty-one tokens from other competitors can challenge the King for their throne. However, as Teruto continues to play, he begins to regain his lost memories that call into question the very nature of Neo Kyoto.`,

    BuildDivideWhite: `Second season of Build Divide.`,

}