import { Anime } from "@/lib/Anime";
import { Synopsis } from "./dSynopsis";

export const d_anime = [
    new Anime(
        "Daily Lives of High School Boys",
        "Danshi Koukousei no Nichijou",
        "https://cdn.myanimelist.net/images/anime/3/33257.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.DailyLivesHighSchoolBoys,
        [""],
        "TV",
        "Jan 10 2012 to Mar 27 2012",
        "Winter 2012",
        "Sunrise",
        "Web manga",
        ["Comedy"],
        ["Gag Humor", "School"],
        "24 minutes",        
    ),
    new Anime(
        "Danchigai",
        "",
        "https://cdn.myanimelist.net/images/anime/7/74879.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Danchigai,
        [""],
        "TV",
        "Jul 10 2015 to Sep 25 2015",
        "Summer 2015",
        "Creators in Pack",
        "4-koma manga",
        ["Comedy", "Slice of Life"],
        ["Iyashikei"],
        "3 minutes",
    ),
    new Anime(
        "Darling in the FranXX",
        "",
        "https://cdn.myanimelist.net/images/anime/1614/90408.jpg",
        24,
        "PG-13 - Teens 13 or older",
        Synopsis.Darling,
        [""],
        "TV",
        "Jan 13 2018 to Jul 7 2018",
        "Winter 2018",
        "A-1 Pictures, Trigger, CloverWorks",
        "Original",
        ["Action", "Drama", "Romance", "Sci-Fi"],
        ["Mecha"],
        "24 minutes",
    ),
    new Anime(
        "Death March to the Parallel World Rhapsody",
        "Death March kara Hajimaru Isekai Kyousoukyoku",
        "https://cdn.myanimelist.net/images/anime/4/88911.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.DeathMarch,
        [""],
        "TV",
        "Jan 11 2018 to Mar 29 2018",
        "Winter 2018",
        "SILVER LINK, Connect",
        "Light novel",
        ["Adventure", "Fantasy"],
        ["Harem", "Isekai"],
        "23 minutes",
    ),
    new Anime(
        "Death Note",
        "",
        "https://cdn.myanimelist.net/images/anime/1079/138100.jpg",
        37,
        "R - 17+ (violence & profanity)",
        Synopsis.DeathNote,
        [""],
        "TV",
        "Oct 4 2006 to Jun 27 2007",
        "Fall 2006",
        "Madhouse",
        "Manga",
        ["Supernatural", "Suspense"],
        ["Psychological"],
        "23 minutes",
    ),
    new Anime(
        "Diary of Our Days at the Breakwater",
        "Houkago Teibou Nisshi",
        "https://cdn.myanimelist.net/images/anime/1216/111637.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.DiaryBreakWater,
        [""],
        "TV",
        "Apr 7 2020 to Sep 22 2020",
        "Spring 2020",
        "Doga Kobo",
        "Manga",
        ["Gourmet", "Slice of Life"],
        ["CGDCT", "Iyashikei", "School"],
        "23 minutes",
    ),
    new Anime(
        "Didn't I Say to Make my Abilities Average in the Next Life",
        "Watashi, Nouryoku wa Heikinchi de tte Itta yo ne!",
        "https://cdn.myanimelist.net/images/anime/1205/111403.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.AbilitiesAverage,
        [""],
        "TV",
        "Oct 7 2019 to Dec 23 2019",
        "Fall 2019",
        "Project No.9",
        "Light novel",
        ["Adventure", "Comedy", "Fantasy"],
        ["Isekai", "Reincarnation"],
        "23 minutes",
    ),
    new Anime(
        "Domestic Girlfriend",
        "Domestic na Kanojo",
        "https://cdn.myanimelist.net/images/anime/1021/95670.jpg",
        12,
        "R+ - Mild Nudity",
        Synopsis.DomesticGirlfriend,
        [""],
        "TV",
        "Jan 12 2019 to Mar 30 2019",
        "Winter 2019",
        "Diomedea",
        "Manga",
        ["Drama", "Romance"],
        ["Love Polygon", "School"],
        "25 minutes",
    ),
    new Anime(
        "Don't Toy with Me, Miss Nagatoro",
        "Ijiranaide, Nagatoro-san",
        "https://cdn.myanimelist.net/images/anime/1900/110097.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.Nagatoro,
        [""],
        "TV",
        "Apr 11 2021 to Jun 27 2021",
        "Spring 2021",
        "Telecom Animation Film",
        "Web manga",
        ["Comedy"],
        ["Romantic Subtext", "School"],
        "23 minutes",
    ),
    new Anime(
        "Drug Store in Another World: The Slow Life of a Cheat Pharmacist",
        "Cheat Kusushi no Slow Life: Isekai ni Tsukurou Drugstore",
        "https://cdn.myanimelist.net/images/anime/1787/115817.jpg",
        12,
        "PG-13 - Teens 13 or older",
        Synopsis.DrugStore,
        [""],
        "TV",
        "Jul 7 2021 to Sep 22 2021",
        "Summer 2021",
        "EMT Squared",
        "Light novel",
        ["Comedy", "Fantasy"],
        ["Harem", "Isekai", "Medical"],
        "23 minutes",
    ),
]